import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { AbiCoder, Interface, ZeroAddress, ZeroHash, getAddress, id, keccak256 } from "ethers";
import * as pure from "../dist/current-mint-fallback.js";
import * as flow from "../dist/current-mint-fallback-workflow.js";
import { buildMintContinuityArtifact, mintCounterSubjectKey } from "../dist/current-mint-continuity.js";

const fixture = JSON.parse(readFileSync(new URL("./fixtures/current-mint-fallback-abi.json", import.meta.url), "utf8"));
const abi = Object.fromEntries(Object.entries(fixture.abis).map(([k,v]) => [k,new Interface(v)]));
abi.recorder = new Interface(JSON.parse(readFileSync(new URL("./fixtures/current-mint-fallback-recorder-abi.json", import.meta.url), "utf8")).abi);
const coder = AbiCoder.defaultAbiCoder(), A = n => getAddress(`0x${BigInt(n).toString(16).padStart(40,"0")}`), code = "0x6001600055", codeHash = keccak256(code), actor = A(30), manifest = A(40), root = A(41), chunk = A(42), pub = A(43);
const c = { chainId: 31337n, core:A(1), ledger:A(2), primary:A(3), fallbackManager:A(4), registry:A(5), governance:A(6), coreCodeHash:codeHash, ledgerCodeHash:codeHash, primaryCodeHash:codeHash, fallbackCodeHash:codeHash, registryCodeHash:codeHash, governanceCodeHash:codeHash, moduleVersion:id("v"), deploymentManifestHash:id("deployment"), moduleManifestHash:id("module"), moduleManifestURI:"ipfs://CaseSensitive", moduleGasLimit:1000000n, recorder:ZeroAddress, recorderCodeHash:ZeroHash };
const hashBlock = n => id(`block:${n}`), timestamp = n => n >= 20 ? 200000 : 1000+n;
function pointer(target, type, revision=1n) { return [target,codeHash,false,id(type),type==="MINT_MANAGER"?"0xb4074ed7":"0x00000000",c.registry,1n,c.moduleManifestHash,c.deploymentManifestHash,revision]; }
const discovery = Object.fromEntries(["eventCatalogHash","compatibilityMatrixHash","numericIdCatalogHash","schemaCatalogHash","canonicalizationCatalogHash","specBundleHash","reconstructionClientHash"].map(k=>[k,id(k)]));
const modules = { revenueResolver:A(50),metadataRouter:A(51),collectionMetadata:A(52),entropyCoordinator:A(53),mintManager:c.primary,mintLedger:c.ledger,artistRegistry:A(54),streamAdminsOrGovernance:c.governance,artworkFinalityRegistry:A(55),moduleRegistry:c.registry,stateExportPublisher:A(56) };
const payload="0x7b7d", payloadHash=keccak256(payload), PAYLOAD="0x8844b744a67cdcdb84ea3c6e3d686883da175820b9ff07a19cffa14bf62e6e81", JCS="0x886c7c89c308c459ca8a626e0ef36a5ea9f4c7a7b56aaf86c71a2ddf3b4f9044";
const leaf=keccak256(coder.encode(["bytes32","uint256","uint32","bytes32"],["0x852f4811a2eb32694863d94ba41b545a65ef4c76086a32c35881f0c4e250a7b5",0,2,payloadHash]));
const list=keccak256(coder.encode(["bytes32","uint32","bytes32[]"],["0xa93750a5551ac5668c8f24cca85acaf1d5f8334fac9406f845fce1ce35548839",2,[leaf]]));
const manifestHash=keccak256(coder.encode(["bytes32","uint16","bytes32","bytes32","uint32","uint16","bytes32"],["0xd6ab89b077c61a288c7168cf8f1c9a7a19464b10475735dae37cb46a0c94c40b",1,PAYLOAD,JCS,2,1,list]));
const rootCode="0x00"+coder.encode(["bytes4","uint16","bytes32","bytes32","uint32","uint16","tuple(address,uint32,bytes32)[]"],["0x6c9d2530",1,PAYLOAD,JCS,2,1,[[chunk,2,payloadHash]]]).slice(2);
const update={manifestHash,manifestURI:"ipfs://next",...discovery};
const window={notBefore:173810n,expiresAfter:900000n,reasonHash:id("reason"),reasonURI:"ipfs://reason",manifestHash};
function classifierHash(enabled,hash,revision) { return keccak256(coder.encode(["bytes32","uint256","address","bytes32","address","bytes4","bool","bytes32","uint64"],[id("6529STREAM_GOVERNANCE_CONFIG_STATE_V1"),c.chainId,c.governance,id("6529STREAM_GOVERNANCE_CONFIG_TIGHTENING_CALL"),c.ledger,abi.ledger.getFunction("retireLedgerWriter").selector,enabled,hash,revision])); }
function artifact() { const coordinates={chainId:c.chainId,successorLedger:c.ledger,predecessorLedger:c.ledger,predecessorManager:c.primary,successorManager:c.fallbackManager,snapshotBlock:8n}, x={collectionId:7n,phaseId:id("phase"),counterId:id("counter"),keyMode:1n,subjectBasis:ZeroHash,predecessorSubjectKey:id("placeholder"),value:3n}; x.predecessorSubjectKey=mintCounterSubjectKey(c.chainId,c.ledger,x); return buildMintContinuityArtifact({coordinates,counterLeaves:[x],nullifiers:[id("nullifier")],inventoryCompletenessReviewed:true}); }
function provider(options={}) {
  const config=options.config??c, calls=[], headers=new Map(); let prepared;
  const post = tag => options.executed && tag>=20;
  const obj={calls, setPrepared:v=>{prepared=v;}, async getNetwork(){options.mutate?.();return {chainId:config.chainId};}, async getBlock(n){headers.set(n,(headers.get(n)??0)+1);return {number:n,hash:options.reorg&&headers.get(n)>1?id("reorg"):hashBlock(n),timestamp:timestamp(n)};},
    async getCode(target,tag){if(options.getCode){const x=options.getCode(target,tag);if(x!==undefined)return x;} if(target===root)return rootCode;if(target===chunk)return "0x00"+payload.slice(2);if(target===pub)return prepared?"0x00"+coder.encode(["bytes[]"],[prepared.batch.plan.data]).slice(2):"0x";return code;},
    async call(tx){calls.push(tx);const target=getAddress(tx.to), tag=tx.blockTag;let iface=target===config.core?abi.core:target===config.ledger?abi.ledger:target===config.registry?abi.registry:target===config.governance?abi.executor:target===manifest?abi.manifest:target===config.recorder?abi.recorder:abi.manager; const desc=iface.parseTransaction({data:tx.data}), name=desc.name,args=desc.args;
      const override=options.read?.(name,args,target,tag,tx); if(override?.raw)return override.raw;if(override!==undefined)return iface.encodeFunctionResult(name,override);
      let out;
      if(name==="getSatellitePointer"){const type=args[0]===id("MODULE_REGISTRY")?"MODULE_REGISTRY":args[0]===id("MINT_LEDGER")?"MINT_LEDGER":args[0]===id("SYSTEM_MANIFEST")?"SYSTEM_MANIFEST":"MINT_MANAGER";out=pointer(type==="MODULE_REGISTRY"?config.registry:type==="MINT_LEDGER"?config.ledger:type==="SYSTEM_MANIFEST"?manifest:post(tag)&&options.activation?config.fallbackManager:config.primary,type,post(tag)&&options.activation&&type==="MINT_MANAGER"?2n:1n);}
      else if(name==="owner"||name==="governanceAuthority"||name==="governanceExecutor")out=[config.governance];
      else if(name==="core")out=[config.core];else if(name==="coreCodeHash")out=[config.coreCodeHash];else if(name==="moduleRegistry")out=[config.registry];else if(name==="moduleRegistryCodeHash")out=[config.registryCodeHash];else if(name==="mintLedger")out=[config.ledger];
      else if(name==="isStreamMintLedger"||name==="isStreamMintManager"||name==="isModuleEligible")out=[true];
      else if(name==="supportsInterface")out=[args[0]!=="0xffffffff"];
      else if(name==="gasParameterInfo"){const floor=args[0]===id("6529STREAM_GGP_MINT_GATE_GAS_LIMIT")?400000n:150000n;out=[floor,floor,2n,1n];}
      else if(name==="moduleRecord"){const rec=args[0]===config.recorder;out=[[rec?(options.deprecated?2n:1n):1n,id(rec?"PRIMARY_SALE_SETTLEMENT":"MINT_MANAGER"),rec?id("6529STREAM_PREPARED_NATIVE_SETTLEMENT_V1"):config.moduleVersion,rec?"0xa00dbd02":"0xb4074ed7",config.moduleGasLimit,codeHash,config.deploymentManifestHash,config.moduleManifestHash,config.moduleManifestURI,10n,rec&&options.deprecated?900n:10n,rec?2n:1n]];}
      else if(name==="preparedNativeRecorder")out=[config.recorder,config.recorderCodeHash,800n,1n];
      else if(name==="ledgerWriterRetiredAt")out=[args[0]===config.primary?(options.retired?7n:post(tag)&&options.retirement?20n:0n):0n];
      else if(name==="ledgerWriter")out=[args[0]!==config.primary||!(options.retired||post(tag)&&options.retirement)];
      else if(name==="isMintSuccessorReady"||name==="isCompletedMintDescendant")out=[!!options.ready];
      else if(name==="tighteningCallConfig"){const enabled=!!options.classified||post(tag)&&!!options.classifier,hash=enabled?codeHash:ZeroHash,revision=post(tag)&&options.classifier?2n:1n;out=[enabled,hash,revision,classifierHash(enabled,hash,revision)];}
      else if(name==="governanceNonce")out=[options.nonce??(tag>10?6n:5n)];
      else if(name==="governanceActionPolicyState")out=[id("profile"),options.catalog??id("catalog"),20n,0n];
      else if(name==="preparedMint")out=[post(tag)&&options.activation?[false,ZeroHash,0n]:[true,id("operation"),7n]];
      else if(name==="pendingPreparedMintTokenId")out=[post(tag)&&options.activation?100n:9n];
      else if(name==="tokenCollectionIdentity")out=post(tag)&&options.activation?[false,0n,0n,false]:[true,7n,4n,false];
      else if(name==="lastAllocatedTokenId")out=[post(tag)?100n:9n];else if(name==="collectionNextSerial")out=[post(tag)?99n:5n];else if(name==="collectionMintedEver")out=[post(tag)?80n:3n];else if(name==="totalSupply")out=[post(tag)?1n:3n];else if(name==="tokenData")out=[post(tag)&&options.activation?"0x":"0x1234"];else if(name==="coordinatorAtMint")out=[post(tag)&&options.activation?ZeroAddress:A(70)];
      else if(name==="streamSystemManifest")out=[post(tag)&&options.activation?manifestHash:id("oldmanifest"),post(tag)&&options.activation?update.manifestURI:"ipfs://old",...Object.values({...modules,...(post(tag)&&options.activation?{mintManager:config.fallbackManager}:{})}),...Object.values(discovery),post(tag)&&options.activation?2n:1n];
      else if(name==="streamSystemManifestPointer")out=[post(tag)&&options.activation?root:A(45)];
      else if(name==="mintImportCommitment"){const a=options.artifact;out=[options.committed&&a?[config.ledger,config.primary,config.fallbackManager,8n,a.manifestHash,options.ready?1n:0n,options.ready?1n:0n,!!options.ready]:[ZeroAddress,ZeroAddress,ZeroAddress,0n,ZeroHash,0n,0n,false]];}
      else if(name==="mintImportDefinitionProgress"||name==="mintImportAncestryProgress")out=[options.ready?1n:0n,1n];
      else if(name==="managerDefinitionCount"||name==="mintAncestorCount")out=[1n];
      else if(name==="deriveCounterValueKey")out=[id("valueKey")];else if(name==="counterValue")out=[3n];else if(name==="isManagerNullifierUsed")out=[true];
      else if(name==="publishedCallData")out=[options.unpublished?ZeroAddress:pub];else if(name==="scheduledCallDataPointer")out=[pub];else if(name==="scheduledCallData")out=[prepared.batch.plan.data];
      else if(name==="governanceAction"){const b=prepared.batch, first=b.plan.calls[0];out=[[post(tag)?3n:1n,b.plan.actionClass,first.target,0n,first.selector,b.callsHash,b.scopeHash,b.oldValueHash,b.newValueHash,b.window.notBefore,b.window.expiresAfter,prepared.proposer,post(tag)?actor:ZeroAddress,ZeroAddress,ZeroAddress,b.window.reasonHash,b.window.reasonURI,b.window.manifestHash]];}
      else if(name==="publishGovernanceCallData")out=[pub];else if(name==="scheduleGovernanceBatch")out=[prepared.batch.actionId];else if(name==="executeGovernanceBatch"||name==="importCounterDefinitions"||name==="importMintAncestors"||name==="completeCounterImport")out=[];
      else throw Error(`Unexpected ${name}`);return iface.encodeFunctionResult(name,out);
    }};return obj;
}
async function setup(options={}, kind="classifier") { const p=provider(options), i=await flow.inspectMintFallback(p,options.config??c,{blockTag:10,...(kind==="classifier"?{readiness:"configuration"}:{})}), plan=kind==="classifier"?pure.mintFallbackRetirementClassificationCall(i.configuration,i.classification):pure.mintFallbackRetirementCall(i.configuration,i.classification), prepared=flow.prepareMintFallbackGovernance(i,plan,actor,{...window,...(kind==="retirement"?{notBefore:1010n}:{})});p.setPrepared(prepared);return {p,i,plan,prepared}; }
function receipt(p, operation, eventSpecs, {safe=false,indexed=false,blockNumber=20,success=true}={}) { const hash=id("tx"), bh=hashBlock(blockNumber), safeAbi=new Interface(["function execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes) returns(bool)"]), safeEvents=new Interface([`event ExecutionSuccess(bytes32 ${indexed?"indexed ":""}txHash,uint256 payment)`]);const specs=[...eventSpecs];if(safe&&success)specs.push([operation.caller,safeEvents,"ExecutionSuccess",[id("safeTx"),0n]]);const logs=specs.map(([address,iface,name,args],index)=>({...iface.encodeEventLog(iface.getEvent(name),args),address,index,transactionHash:hash,blockHash:bh,blockNumber,removed:false}));const tx={hash,chainId:c.chainId,blockNumber,blockHash:bh,from:safe?A(99):operation.caller,to:safe?operation.caller:operation.call.to,value:0n,data:safe?safeAbi.encodeFunctionData("execTransaction",[operation.call.to,0n,operation.call.data,0,0,0,0,ZeroAddress,ZeroAddress,"0x"]):operation.call.data};const r={hash,status:1,blockNumber,blockHash:bh,from:tx.from,to:tx.to,logs};p.getTransaction=async()=>tx;p.getTransactionReceipt=async()=>r;return {hash,tx,r}; }
function actionEvents(prepared, execute=false) {const b=prepared.batch,common=[1n,b.actionId,b.plan.actionClass,b.plan.calls[0].target,0n,b.plan.calls[0].selector,b.callsHash,b.scopeHash,b.oldValueHash,b.newValueHash];return [[c.governance,abi.executor,"GovernanceActionPolicyValidated",[1n,b.actionId,execute?2n:1n,id("profile"),id("catalog")]], [c.governance,abi.executor,execute?"GovernanceActionExecuted":"GovernanceActionScheduled",execute?[...common,actor,b.window.manifestHash]:[...common,b.window.notBefore,b.window.expiresAfter,b.nonce,actor,b.window.reasonHash,b.window.reasonURI,b.window.manifestHash]]];}

test("configuration and reserve checks preserve exact marker, gas, URI, authority and code boundaries",async()=>{
  const i=await flow.inspectMintFallback(provider(),c,{blockTag:10});assert.equal(i.readiness,"reserve");assert(Object.isFrozen(i.configuration));
  for(const [name,override] of [["gasParameterInfo",[400000n,399999n,2n,1n]],["owner",[A(999)]],["isStreamMintManager",[false]]])await assert.rejects(flow.inspectMintFallback(provider({read:n=>n===name?override:undefined}),c,{blockTag:10}));
  await assert.rejects(flow.inspectMintFallback(provider({read:(n,a)=>n==="moduleRecord"&&a[0]===c.fallbackManager?[[1n,id("MINT_MANAGER"),c.moduleVersion,"0xb4074ed7",c.moduleGasLimit,codeHash,c.deploymentManifestHash,c.moduleManifestHash,c.moduleManifestURI.toLowerCase(),10n,10n,1n]]:undefined}),c,{blockTag:10}),/URI/);
  const delegated="0xef0100"+A(77).slice(2), dc={...c,coreCodeHash:keccak256(delegated)};await assert.rejects(flow.inspectMintFallback(provider({config:dc,getCode:a=>a===c.core?delegated:undefined}),dc,{blockTag:10}),/runtime/);
});
test("paid recorder admits ACTIVE and qualified DEPRECATED, rejects changed binding and ERC165",async()=>{
  const paid={...c,recorder:A(7),recorderCodeHash:codeHash};for(const deprecated of [false,true])assert.equal((await flow.inspectMintFallback(provider({config:paid,deprecated}),paid,{blockTag:10})).configuration.recorder,paid.recorder);
  await assert.rejects(flow.inspectMintFallback(provider({config:paid,deprecated:true,read:n=>n==="preparedNativeRecorder"?[paid.recorder,codeHash,900n,2n]:undefined}),paid,{blockTag:10}),/binding/);
  await assert.rejects(flow.inspectMintFallback(provider({config:paid,read:(n,a,t)=>n==="supportsInterface"&&t===paid.recorder?[true]:undefined}),paid,{blockTag:10}),/ERC165/);
});
test("canonical returns, pinned block/hash and pre-await cloning fail closed",async()=>{
  await assert.rejects(flow.inspectMintFallback(provider({read:n=>n==="isStreamMintLedger"?{raw:coder.encode(["uint256"],[2])}:undefined}),c,{blockTag:10}),/Noncanonical/);
  await assert.rejects(flow.inspectMintFallback(provider({reorg:true}),c,{blockTag:10}),/Pinned block/);
  const mutable=structuredClone(c), opts={blockTag:10};const result=await flow.inspectMintFallback(provider({mutate:()=>{mutable.primary=A(999);opts.blockTag=99;}}),mutable,opts);assert.equal(result.configuration.primary,c.primary);assert.equal(result.blockNumber,10);
});
test("genuine same-Ledger artifact joins actual snapshot leaves, retired namespace and completed successor",async()=>{
  const a=artifact(), p=provider({artifact:a,retired:true,committed:true,ready:true});const i=await flow.inspectMintFallback(p,c,{blockTag:10,importArtifact:a});assert.equal(i.import.ready,true);assert.equal(i.import.snapshotBlockHash,hashBlock(8));assert.equal(i.import.inventoryCompleteness,"caller-reviewed");
  await assert.rejects(flow.inspectMintFallback(provider({artifact:a,retired:true,read:n=>n==="counterValue"?[2n]:undefined}),c,{blockTag:10,importArtifact:a}),/predecessor counter/);
  await assert.rejects(flow.inspectMintFallback(provider({artifact:a}),c,{blockTag:10,importArtifact:a}),/retirement/);
  const i2=await flow.inspectMintFallback(provider({artifact:a,retired:true}),c,{blockTag:10,importArtifact:a});assert.equal(i2.import.committed,false);
});
test("captures complete original prepared incident facts and canonical manifest payload",async()=>{
  const p=provider(), i=await flow.inspectMintFallback(p,c,{blockTag:10,recovery:{tokenId:9n,operationId:id("operation")}});assert.equal(i.recovery.state.serial,4n);const a=await flow.captureMintFallbackActivation(p,c,{blockTag:10,manifest,payloadRoot:root,update});assert.equal(a.current.modules.mintManager,c.primary);assert.equal(a.previousPointer.revision,1n);
  await assert.rejects(flow.captureMintFallbackActivation(provider({getCode:a=>a===chunk?"0x007b20":undefined}),c,{blockTag:10,manifest,payloadRoot:root,update}),/chunk/);
  const maxData="0x"+"ab".repeat(16384), observed=await flow.inspectMintFallback(provider({read:n=>n==="tokenData"?[maxData]:undefined}),c,{blockTag:10,recovery:{tokenId:9n,operationId:id("operation")}});assert.equal(observed.recovery.state.tokenDataHash,keccak256(maxData));
  await assert.rejects(flow.inspectMintFallback(provider({read:n=>n==="tokenData"?[maxData+"ab"]:undefined}),c,{blockTag:10,recovery:{tokenId:9n,operationId:id("operation")}}),/oversized/);
});
test("ordinary windows retain 48-hour floor, seven-day open window and uint64 headroom",async()=>{
  const {i,plan}=await setup();for(const w of [{...window,notBefore:1010n},{...window,expiresAfter:window.notBefore+1n},{...window,expiresAfter:40000000n}])assert.throws(()=>flow.prepareMintFallbackGovernance(i,plan,actor,w),/window/);
  const p=provider({classified:true}), r=await flow.inspectMintFallback(p,c,{blockTag:10});const rp=pure.mintFallbackRetirementCall(c,r.classification);const near=(1n<<64n)-100n;assert.throws(()=>flow.prepareMintFallbackGovernance({...r,timestamp:near},rp,actor,{...window,notBefore:near,expiresAfter:near+1n}),/window/);
});
test("publish/schedule/execute use original exact caller and catalog, reject nonce and timing drift",async()=>{
  const {p,prepared}=await setup();for(const [stage,tag] of [["publish",10],["schedule",10],["execute",20]]){const op=flow.prepareMintFallbackGovernanceOperation(prepared,stage,actor);const sim=await flow.simulateMintFallbackOperation(p,op,{blockTag:tag});assert.equal(sim.operation.call.value,0n);assert.equal(p.calls.at(-1).from,actor);assert.equal(p.calls.at(-1).data,op.call.data);}
  const op=flow.prepareMintFallbackGovernanceOperation(prepared,"schedule",actor), changed=provider({read:(n,a,t,tag)=>n==="governanceNonce"&&tag===11?[6n]:undefined});changed.setPrepared(prepared);await assert.rejects(flow.simulateMintFallbackOperation(changed,op,{blockTag:11}),/nonce changed/);
  const changedCatalog=provider({read:(n,a,t,tag)=>n==="governanceActionPolicyState"&&tag===20?[id("profile"),id("new-catalog"),21n,1n]:undefined});changedCatalog.setPrepared(prepared);await assert.rejects(flow.simulateMintFallbackOperation(changedCatalog,flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor),{blockTag:20}),/catalog changed/);
});
test("activation can schedule before import but execute needs readiness and unchanged incident commitments",async()=>{
  const p=provider(), i=await flow.inspectMintFallback(p,c,{blockTag:10,recovery:{tokenId:9n,operationId:id("operation")}}), a=await flow.captureMintFallbackActivation(p,c,{blockTag:10,manifest,payloadRoot:root,update}), plan=pure.mintFallbackIncidentActivationCalls(c,a,i.recovery), prepared=flow.prepareMintFallbackGovernance(i,plan,actor,window);p.setPrepared(prepared);
  await flow.simulateMintFallbackOperation(p,flow.prepareMintFallbackGovernanceOperation(prepared,"schedule",actor),{blockTag:10});await assert.rejects(flow.simulateMintFallbackOperation(p,flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor),{blockTag:20}),/not ready/);
  const changed=provider({read:(n,a,t,tag)=>tag===20?(n==="totalSupply"?[4n]:n==="isMintSuccessorReady"?[true]:undefined):undefined});changed.setPrepared(prepared);await assert.rejects(flow.simulateMintFallbackOperation(changed,flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor),{blockTag:20}),/reschedule/);
});
test("permissionless copying keeps original caller while governed calls cannot escape Executor",async()=>{
  const a=artifact(),p=provider({artifact:a,retired:true,committed:true}),i=await flow.inspectMintFallback(p,c,{blockTag:10,importArtifact:a}), plan=pure.mintFallbackCopyDefinitionsCall(c,a,1n),op=flow.prepareMintFallbackPermissionless(i,plan,actor);await flow.simulateMintFallbackOperation(p,op,{blockTag:10});assert.equal(p.calls.at(-1).from,actor);assert.throws(()=>flow.prepareMintFallbackPermissionless(i,pure.mintFallbackImportStateCall(c,a,[0],[]),actor),/boundary/);
});
test("direct and both Safe event layouts bind scheduled action and exact receipt",async()=>{
  for(const safe of [false,true])for(const indexed of safe?[false,true]:[false]){const {p,prepared}=await setup();const op=flow.prepareMintFallbackGovernanceOperation(prepared,"schedule",actor), tx=receipt(p,op,actionEvents(prepared),{safe,indexed,blockNumber:11}), out=await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:safe?"safe":"direct"});assert.equal(out.events.length,safe?3:2);assert(Object.isFrozen(out.observed));}
});
test("receipt rejects absent Safe success, changed calldata, noncanonical event and equal-block capture",async()=>{
  const {p,prepared}=await setup(),op=flow.prepareMintFallbackGovernanceOperation(prepared,"schedule",actor);
  let tx=receipt(p,op,actionEvents(prepared),{safe:true,success:false,blockNumber:11});await assert.rejects(flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"safe"}),/Safe requires/);
  tx=receipt(p,op,actionEvents(prepared),{blockNumber:11});tx.tx.data+="00";await assert.rejects(flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"}),/Direct/);
  tx=receipt(p,op,actionEvents(prepared),{blockNumber:11});tx.r.logs[0].data+="00";await assert.rejects(flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"}),/Noncanonical/);
  tx=receipt(p,op,actionEvents(prepared),{blockNumber:10});await assert.rejects(flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"}),/chronology/);
});
test("publication retry permits eventless exact retained calldata",async()=>{
  const {p,prepared}=await setup(),op=flow.prepareMintFallbackGovernanceOperation(prepared,"publish",actor),tx=receipt(p,op,[],{blockNumber:11});const out=await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"});assert.equal(out.events.length,0);
});
test("class1 classifier execution and class0 retirement have exact original event readback",async()=>{
  const {p,prepared}=await setup({executed:true,classifier:true}),op=flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor), specs=[...actionEvents(prepared,true),[c.governance,abi.executor,"TighteningCallUpdated",[1n,c.ledger,abi.ledger.getFunction("retireLedgerWriter").selector,true,codeHash,2n,prepared.batch.actionId]]],tx=receipt(p,op,specs);assert.equal((await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"})).observed.classification.enabled,true);
  const s=await setup({executed:true,retirement:true,classified:true},"retirement"),ro=flow.prepareMintFallbackGovernanceOperation(s.prepared,"execute",actor),rt=receipt(s.p,ro,[...actionEvents(s.prepared,true),[c.ledger,abi.ledger,"MintLedgerWriterRetired",[c.primary,20n]]]);assert.equal((await flow.inspectMintFallbackOperationReceipt(s.p,ro,{transactionHash:rt.hash,execution:"direct"})).observed.primaryRetiredAt,20n);
});
test("incident receipt binds pointer-abort-recovery-manifest and allows later block mints/supply changes",async()=>{
  const p=provider({executed:true,activation:true,ready:true}),i=await flow.inspectMintFallback(p,c,{blockTag:10,recovery:{tokenId:9n,operationId:id("operation")}}),a=await flow.captureMintFallbackActivation(p,c,{blockTag:10,manifest,payloadRoot:root,update}),plan=pure.mintFallbackIncidentActivationCalls(c,a,i.recovery),prepared=flow.prepareMintFallbackGovernance(i,plan,actor,window);p.setPrepared(prepared);const op=flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor),aid=prepared.batch.actionId,specs=[...actionEvents(prepared,true),[c.core,abi.core,"CoreSatellitePointerUpdated",[1n,id("MINT_MANAGER"),aid,c.fallbackManager,c.primary]],[c.core,abi.core,"TokenCollectionRegistrationReverted",[1n,9n,7n]],[c.fallbackManager,abi.fallback,"MintFallbackPreparedRecovered",[1n,aid,9n,id("operation"),7n]],[manifest,abi.manifest,"StreamSystemManifestPublished",[1n,manifestHash,root,aid]]],tx=receipt(p,op,specs,{safe:true,indexed:true});const out=await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"safe"});assert.equal(out.observed.managerPointer.target,c.fallbackManager);assert.match(out.stateAttribution,/observation/);assert.equal(out.events.length,7);
});
test("same-revision manifest and pointer contradictions are rejected after exact execution events",async()=>{
  let corrupt="pointer";const p=provider({executed:true,activation:true,ready:true,read:(n,args,t,tag)=>tag>=20?(n==="getSatellitePointer"&&args[0]===id("MINT_MANAGER")&&corrupt==="pointer"?[c.fallbackManager,id("wrong hash"),false,id("MINT_MANAGER"),"0xb4074ed7",c.registry,1n,c.moduleManifestHash,c.deploymentManifestHash,2n]:n==="streamSystemManifest"&&corrupt==="manifest"?[manifestHash,"ipfs://WRONG",...Object.values({...modules,mintManager:c.fallbackManager}),...Object.values(discovery),2n]:undefined):undefined});
  const i=await flow.inspectMintFallback(p,c,{blockTag:10}),a=await flow.captureMintFallbackActivation(p,c,{blockTag:10,manifest,payloadRoot:root,update}),plan=pure.mintFallbackActivationCalls(c,a),prepared=flow.prepareMintFallbackGovernance(i,plan,actor,window);p.setPrepared(prepared);const op=flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor),aid=prepared.batch.actionId,tx=receipt(p,op,[...actionEvents(prepared,true),[c.core,abi.core,"CoreSatellitePointerUpdated",[1n,id("MINT_MANAGER"),aid,c.fallbackManager,c.primary]],[manifest,abi.manifest,"StreamSystemManifestPublished",[1n,manifestHash,root,aid]]]);
  await assert.rejects(flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"}),/pointer fields/);corrupt="manifest";await assert.rejects(flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"}),/manifest fields/);
});
test("incident publication simulation retries after recovery without requiring old prepared token",async()=>{
  const p=provider({executed:true,activation:true,ready:true,read:(n,args,t,tag)=>n==="governanceActionPolicyState"&&tag>=20?[id("profile"),id("later-catalog"),21n,1n]:undefined}),i=await flow.inspectMintFallback(p,c,{blockTag:10,recovery:{tokenId:9n,operationId:id("operation")}}),a=await flow.captureMintFallbackActivation(p,c,{blockTag:10,manifest,payloadRoot:root,update}),prepared=flow.prepareMintFallbackGovernance(i,pure.mintFallbackIncidentActivationCalls(c,a,i.recovery),actor,window);p.setPrepared(prepared);const op=flow.prepareMintFallbackGovernanceOperation(prepared,"publish",actor);await flow.simulateMintFallbackOperation(p,op,{blockTag:20});const tx=receipt(p,op,[]);assert.equal((await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"})).events.length,0);
});
test("root commit, actual leaf import and descriptor completion receipts retain exact same-Ledger facts",async()=>{
  const a=artifact();
  for(const stage of ["commit","leaves","complete"]){const options={artifact:a,retired:true,committed:stage!=="commit",executed:true};const p=provider({...options,read:(n,args,t,tag)=>n==="mintImportCommitment"&&tag>=20?[[c.ledger,c.primary,c.fallbackManager,8n,a.manifestHash,stage==="commit"?0n:1n,stage==="commit"?0n:1n,stage==="complete"]]:(n==="mintImportDefinitionProgress"||n==="mintImportAncestryProgress")&&tag>=20?[1n,1n]:undefined}),i=await flow.inspectMintFallback(p,c,{blockTag:10,importArtifact:a}),plan=stage==="commit"?pure.mintFallbackImportCommitCall(c,a):stage==="leaves"?pure.mintFallbackImportStateCall(c,a,[0],[0]):pure.mintFallbackCompleteImportCall(c,a),prepared=flow.prepareMintFallbackGovernance(i,plan,actor,window);p.setPrepared(prepared);const op=flow.prepareMintFallbackGovernanceOperation(prepared,"execute",actor),x=a.counterLeaves[0];const target=stage==="commit"?[[c.ledger,abi.ledger,"MintLedgerImportRootCommitted",[1n,a.importRoot,c.primary,c.fallbackManager,c.ledger,8n,a.manifestHash]]]:stage==="leaves"?[[c.ledger,abi.ledger,"MintLedgerCounterImported",[1n,a.importRoot,id("valueKey"),x.predecessorSubjectKey,x.collectionId,x.phaseId,x.counterId,x.value,x.value]],[c.ledger,abi.ledger,"MintLedgerNullifierImported",[1n,a.importRoot,a.nullifiers[0],c.fallbackManager]]]:[[c.ledger,abi.ledger,"MintLedgerImportCompleted",[a.importRoot,c.fallbackManager,1n,1n]]];const tx=receipt(p,op,[...actionEvents(prepared,true),...target]);assert.equal((await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"})).events.length,2+target.length);}
});
test("permissionless copy receipt reports end-block progress without inventing skipped ancestry events",async()=>{
  const a=artifact(),p=provider({artifact:a,retired:true,committed:true}),i=await flow.inspectMintFallback(p,c,{blockTag:10,importArtifact:a}),op=flow.prepareMintFallbackPermissionless(i,pure.mintFallbackCopyAncestorsCall(c,a,1n),actor),tx=receipt(p,op,[]);const out=await flow.inspectMintFallbackOperationReceipt(p,op,{transactionHash:tx.hash,execution:"direct"});assert.equal(out.events.length,0);assert.match(out.stateAttribution,/observation/);
});
