// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

library StreamFinalityViewPreservationInputSchemasV1 {
    bytes32 internal constant SCHEMA_ID = keccak256("STREAM_VIEW_PRESERVATION_FINALITY_INPUT_V1");
    bytes32 internal constant CANON_ID =
        keccak256("STREAM_VIEW_PRESERVATION_FINALITY_INPUT_ABI_V1");
    error UnknownManifestDefinition(bytes32 id);

    function document(bytes32 id) public pure returns (bytes memory) {
        if (id == SCHEMA_ID) {
            return bytes(
                '{"name":"STREAM_VIEW_PRESERVATION_FINALITY_INPUT_V1","version":1,"profile":"VIEW; exact adopted policy view; skip-only-sanction preservation output","fields":["StreamFinalityScope scope","bytes32 coreFactsHash","bytes32 contentRoot","uint64 leafCount","bytes32 contentRootSchemaId","bytes32 snapshotManifestHash","bytes32 referenceRenderManifestHash","StreamFinalityScopeInputs inputs","StreamFinalityComponentExpectation[] nonSanctionComponents","Entropy entropy","bytes32 completeBindingRecordHash","bytes32 adoptionRecordHash","bytes32 adoptionProfile","bytes32 outputProfile","bytes32 membershipHash","bytes32 rootBindingHash","bytes32 viewId","uint8 postFreezePolicy","uint8 sanctionPolicy"],"entropyTuple":["address sourceSet","bytes32 sourceSetCodeHash","bytes32 sourceSetProfile","bytes32 inventoryPlan","bytes32 inventoryHash","bytes32 policyChainHash","uint256 policyCount","bytes32 snapshotProfileHash","bytes32 referenceProfileHash"],"inputs":["rootRecordHash","snapshotRecordHash","referenceRenderRecordHash","intentRecordHash","intentWaiverRecordHash","interviewEvidenceHash","rightsStatementRecordHash","workDescriptionRecordHash","renderCriticalEvidenceHash","bundleCoverageHash"],"scope":["uint8 scopeType=4","uint256 collectionId>0","uint256 tokenId=0","bytes32 scopeId!=0"],"components":"Nine sorted independent complete seven-field expectations; all required families; no sanction","entropy":"Complete ordered full H resolves from exact scoped source set and current snapshot. Explicit terminal1/2 has zero seed and finalizedfalse; actual finalized5 keeps original semantics. Burned identities retained. No sample-as-membership.","binding":"Exact immutable complete class2 selection receipt, original op17 CONTENT_ROOT and separately tagged RENDERER_CONFIG adoption; rootBindingHash=keccak256(abi.encode(exact28wordBinding)).","excluded":"Sanction/signature/finality and this manifest own hash; no mutable fixity head","limits":"8192bytes; original producer bounds; complete currentness remains mandatory","componentTuple":["bytes32 componentType","address component","bytes4 interfaceId","bytes32 codeHash","bytes32 moduleVersion","bytes32 manifestHash","bytes32 dataHash"]}'
            );
        }
        if (id == CANON_ID) {
            return bytes(
                '{"name":"STREAM_VIEW_PRESERVATION_FINALITY_INPUT_ABI_V1","version":1,"encoding":"abi.encode(bytes32 schemaId,bytes32 canonicalizationId,uint256 chainId,address core,address metadataHost,address finalityRegistry,StreamFinalityViewPreservationInputTypesV1.Statement statement)","scopeInputsHash":"Original 6529STREAM_FINALITY_SCOPE_INPUTS_V1(chainId,core,metadataHost,scope,tenInputs)","canonical":"Solidity0.8.19 exact canonical offsets/widths/padding/order; no trailingbytes; exact full bytes in SchemaStore and original Registry staging","maximumBytes":8192,"scopeTuple":["uint8 scopeType","uint256 collectionId","uint256 tokenId","bytes32 scopeId"],"inputTuple":["bytes32 rootRecordHash","bytes32 snapshotRecordHash","bytes32 referenceRenderRecordHash","bytes32 intentRecordHash","bytes32 intentWaiverRecordHash","bytes32 interviewEvidenceHash","bytes32 rightsStatementRecordHash","bytes32 workDescriptionRecordHash","bytes32 renderCriticalEvidenceHash","bytes32 bundleCoverageHash"],"componentTuple":["bytes32 componentType","address component","bytes4 interfaceId","bytes32 codeHash","bytes32 moduleVersion","bytes32 manifestHash","bytes32 dataHash"],"entropyTuple":["address sourceSet","bytes32 sourceSetCodeHash","bytes32 sourceSetProfile","bytes32 inventoryPlan","bytes32 inventoryHash","bytes32 policyChainHash","uint256 policyCount","bytes32 snapshotProfileHash","bytes32 referenceProfileHash"],"expandedEnvelope":"(bytes32,bytes32,uint256,address,address,address,((StreamFinalityScopeType,uint256,uint256,bytes32),bytes32,bytes32,uint64,bytes32,bytes32,bytes32,(bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32),(bytes32,address,bytes4,bytes32,bytes32,bytes32,bytes32)[],(address,bytes32,bytes32,bytes32,bytes32,bytes32,uint256,bytes32,bytes32),bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,uint8,uint8))","componentCount":9,"componentWords":7}'
            );
        }
        revert UnknownManifestDefinition(id);
    }
}
