// Regenerate only the ABI/type projection; never build or modify the compiler export.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";

export const targets = {
  core: "StreamCore", manager: "StreamMintManager",
  nativeSale: "StreamFixedPriceSaleAdapter", erc20Sale: "StreamERC20FixedPriceSaleAdapter",
  auction: "StreamEnglishAuctionHouse", artistRegistry: "StreamCollectionArtistRegistry",
  entropy: "StreamEntropyCoordinator", splitFactory: "StreamSplitFactory",
  splitWallet: "StreamSplitWallet", primaryRevenue: "StreamRevenueResolver",
  assetPolicy: "StreamAssetPolicyRegistry", executor: "StreamGovernanceExecutor",
};
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const exportRoot = resolve(packageRoot, "../../release-artifacts/current");
const sha = (bytes) => "sha256:" + createHash("sha256").update(bytes).digest("hex");
const canonicalType = (p) => p.type.startsWith("tuple")
  ? `(${p.components.map(canonicalType).join(",")})${p.type.slice(5)}` : p.type;
const tsType = (p) => {
  const array = /^(.*)(\[[0-9]*\])$/.exec(p.type);
  if (array) return `ReadonlyArray<${tsType({ ...p, type: array[1] })}>`;
  if (p.type === "tuple") return `{ ${p.components.map((x, i) => `readonly ${JSON.stringify(x.name || "field" + i)}: ${tsType(x)}`).join("; ")} }`;
  if (/^u?int/.test(p.type)) return "bigint";
  if (p.type === "address") return "Address";
  if (p.type.startsWith("bytes")) return "Hex";
  if (p.type === "bool") return "boolean";
  if (p.type === "string") return "string";
  throw Error(`Unsupported ABI type ${p.type}`);
};
const tuple = (params) => `readonly [${params.map(tsType).join(", ")}]`;
const result = (params) => params.length === 0 ? "void" : params.length === 1 ? tsType(params[0])
  : `${tuple(params)} & { ${params.filter(p => p.name).map(p => `readonly ${JSON.stringify(p.name)}: ${tsType(p)}`).join("; ")} }`;

export async function render(root = exportRoot) {
  const manifestBytes = await readFile(resolve(root, "manifest.json"));
  const manifest = JSON.parse(manifestBytes);
  const compilerInput = await readFile(resolve(root, "compiler-input.json"));
  if (sha(compilerInput) !== manifest.compiler_input_sha256) throw Error("Compiler input digest mismatch");
  const abis = {}, hashes = {}, definitions = [];
  for (const [key, target] of Object.entries(targets)) {
    const path = `artifacts/${target}.json`;
    const bytes = await readFile(resolve(root, path));
    if (manifest.files[path] !== sha(bytes)) throw Error(`Export artifact digest mismatch: ${path}`);
    const abi = JSON.parse(bytes).abi;
    abis[key] = abi; hashes[path] = sha(bytes);
    const methods = abi.filter(x => x.type === "function");
    const rows = methods.map(f => {
      const name = methods.filter(x => x.name === f.name).length === 1 ? f.name : `${f.name}(${f.inputs.map(canonicalType).join(",")})`;
      return `    ${JSON.stringify(name)}: { args: ${tuple(f.inputs)}; result: ${result(f.outputs)}; mutability: ${JSON.stringify(f.stateMutability)} };`;
    });
    definitions.push(`  ${key}: {\n${rows.join("\n")}\n  };`);
  }
  // Signing field order and widths come from the exact compiled ABI, not another ABI copy.
  const fields = (key, method) => {
    const f = abis[key].find(x => x.type === "function" && x.name === method);
    if (!f) throw Error(`Missing digest surface ${key}.${method}`);
    const values = f.inputs.length === 1 && f.inputs[0].type === "tuple" ? f.inputs[0].components : f.inputs;
    return values.map(({ name, type }) => ({ name, type }));
  };
  const signingFields = {
    SaleAuthorization: fields("nativeSale", "authorizationDigest"),
    ERC20SaleAuthorization: fields("erc20Sale", "authorizationDigest"),
    StreamPaymentIntent: fields("erc20Sale", "paymentIntentDigest"),
    StreamPaymentIntentRevocation: fields("erc20Sale", "paymentIntentRevocationDigest"),
    CollectionArtistAcceptance: [{ name: "core", type: "address" }, ...fields("artistRegistry", "acceptanceDigest")],
    AuctionAuthorization: fields("auction", "authorizationDigest"),
  };
  const header = "// Generated by scripts/generate.mjs. Do not edit; npm run generate:check verifies the projection.\n";
  return {
    "src/generated/abis.ts": header + `export const abis = ${JSON.stringify(abis, null, 2)} as const;\n`,
    "src/generated/contracts.ts": header + `export type Hex = \`0x\${string}\`;\nexport type Address = Hex;\nexport interface ContractFunctions {\n${definitions.join("\n")}\n}\nexport const signingFields = ${JSON.stringify(signingFields, null, 2)} as const;\n`,
    "src/generated/provenance.ts": header + `export const provenance = ${JSON.stringify({ schemaVersion: 1, source: "release-artifacts/current", manifestSha256: sha(manifestBytes), compilerInputSha256: manifest.compiler_input_sha256, compilerVersion: manifest.compiler_version, artifacts: hashes }, null, 2)} as const;\n`,
  };
}

export async function generate(check = false) {
  const outputs = await render();
  for (const [path, text] of Object.entries(outputs)) {
    const destination = resolve(packageRoot, path);
    if (check) {
      let actual; try { actual = await readFile(destination, "utf8"); } catch { /* reported below */ }
      if (actual !== text) throw Error(`Stale client projection: ${path}; run npm run generate`);
    } else { await mkdir(dirname(destination), { recursive: true }); await writeFile(destination, text, "utf8"); }
  }
  console.log(`${check ? "Verified" : "Generated"} ${Object.keys(targets).length} current contract ABIs and types`);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.slice(2).some(x => x !== "--check")) throw Error("Usage: node scripts/generate.mjs [--check]");
  await generate(process.argv.includes("--check"));
}
