"""Generate/check exact mode interpretation literals from the retained JSON documents."""
import argparse
import json
from pathlib import Path
from tools.museum.canonical import keccak256

ROOT = Path(__file__).resolve().parents[2]
DOCUMENTS = {
    "SCHEMA": "STREAM_REFERENCE_MODE_ABI_V1",
    "PROFILE": "STREAM_REFERENCE_MODE_PROFILE_V1",
    "DECODE": "STREAM_REFERENCE_MODE_ABI_V2",
    "CONDITION": "STREAM_REFERENCE_CURATED_CONDITION_ABI_V1",
    "PROPERTIES": "STREAM_REFERENCE_SIGNIFICANT_PROPERTIES_ABI_V1",
    "CANON": "STREAM_SOLIDITY_ABI_V1",
}


def generated():
    lines = ["// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.19;", "",
             "/// @notice Exact immutable interpretation documents; generated by reference_mode_profile.py.",
             "library StreamReferenceModeDefinitions {"]
    for name, identity in DOCUMENTS.items():
        raw = (ROOT / "schemas/records" / (identity + ".json")).read_bytes()
        parsed = json.loads(raw)
        if raw != (json.dumps(parsed, sort_keys=True, separators=(",", ":")) + "\n").encode():
            raise ValueError("noncanonical definition: " + identity)
        literal = json.dumps(raw.decode(), ensure_ascii=True)
        lines += [f'    bytes32 internal constant {name}_ID = keccak256("{identity}");',
                  f"    string internal constant {name}_DOCUMENT = {literal};",
                  f"    bytes32 internal constant {name}_HASH = {keccak256(raw)};",
                  f"    uint32 internal constant {name}_BYTES = {len(raw)};"]
    return "\n".join(lines + ["}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "smart-contracts/domains/records/StreamReferenceModeDefinitions.sol"
    source = generated()
    if args.check:
        if path.read_text(encoding="utf8") != source:
            raise SystemExit("reference-mode definition literals differ")
    else:
        path.write_text(source, encoding="utf8", newline="\n")


if __name__ == "__main__":
    main()
