// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @notice Exact native snapshot interpretation bytes, independently registered before use.
/// @dev Generated by python -m tools.metadata.snapshot_profile. Do not edit.
library StreamSnapshotDefinitions {
    bytes32 internal constant SCHEMA_ID = keccak256("STREAM_NATIVE_ONCHAIN_SNAPSHOT_V1");
    bytes32 internal constant SCHEMA_HASH =
        0x5b263e5629cf85cdd9d905cff19dca57b23ee052efb94e78699cd1c3492a01c2;
    uint256 internal constant SCHEMA_BYTES = 10058;
    bytes32 internal constant PROFILE_ID =
        keccak256("STREAM_NATIVE_ONCHAIN_SNAPSHOT_JSON_PROFILE_V1");
    bytes32 internal constant PROFILE_HASH =
        0x1de4ffe22d9442b4aa3447fef5057f6677f167ce901c76555d17c25aece44755;
    uint256 internal constant PROFILE_BYTES = 2283;
    bytes32 internal constant CANON_ID = keccak256("RFC8785_JCS");
    bytes32 internal constant CANON_HASH =
        0xbc33af15c6b6374052871a5fdfa255f900f56fa594f650b2d0814c681fdb35a9;
    uint256 internal constant CANON_BYTES = 362;
}
