// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @notice Exact retained definition pins; registration is verified by the consumer.
/// @dev Generated by python -m tools.metadata.rights_definitions. Do not edit.
library StreamRightsRecordDefinitions {
    bytes32 internal constant SCHEMA_ID = keccak256("STREAM_RIGHTS_V1");
    bytes32 internal constant SCHEMA_HASH = 0xccb6e9813b29689628095bd2eaaf2b62bdbdfd7e971d14784a9dc419688a33e8;
    uint256 internal constant SCHEMA_BYTES = 14613;
    bytes32 internal constant PROFILE_ID = keccak256("STREAM_RIGHTS_JSON_PROFILE_V1");
    bytes32 internal constant PROFILE_HASH = 0x15df3f552f58b0a0e8ba75bc4679d6ef3c3c1034fd065646a518bb63edb27174;
    uint256 internal constant PROFILE_BYTES = 1335;
    bytes32 internal constant CANON_ID = keccak256("RFC8785_JCS");
    bytes32 internal constant CANON_HASH = 0xbc33af15c6b6374052871a5fdfa255f900f56fa594f650b2d0814c681fdb35a9;
    uint256 internal constant CANON_BYTES = 362;
}
