// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @dev Generated by python -m tools.metadata.chunked_snapshot_profile.
library StreamChunkedSnapshotDefinitions {
    bytes32 internal constant SCHEMA_ID = keccak256("STREAM_CHUNKED_ONCHAIN_SNAPSHOT_V1");
    bytes32 internal constant SCHEMA_HASH =
        0x715e2549f00ad206cc137e3d82118c72a692bea2ef50780a3bc53cbb5cca8631;
    uint256 internal constant SCHEMA_BYTES = 13571;
    bytes32 internal constant PROFILE_ID =
        keccak256("STREAM_CHUNKED_ONCHAIN_SNAPSHOT_JSON_PROFILE_V1");
    bytes32 internal constant PROFILE_HASH =
        0x13974c0940ff0a65544b3c95ccf4981dedac1e830912924fe51c3fd6c696a49e;
    uint256 internal constant PROFILE_BYTES = 3193;
    bytes32 internal constant CANON_ID = keccak256("RFC8785_JCS");
    bytes32 internal constant CANON_HASH =
        0xbc33af15c6b6374052871a5fdfa255f900f56fa594f650b2d0814c681fdb35a9;
    uint256 internal constant CANON_BYTES = 362;
}
