// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @notice Generated additive metric documents; original reference definitions are unchanged.
library StreamReferenceMetricDefinitions {
    bytes32 internal constant SCHEMA_ID = keccak256("STREAM_REFERENCE_METRIC_SUPPLEMENT_ABI_V1");
    string internal constant SCHEMA_DOCUMENT = "{\"abi\":[{\"components\":[{\"name\":\"implementationIndex\",\"type\":\"bytes\"},{\"name\":\"parameters\",\"type\":\"bytes\"},{\"components\":[{\"name\":\"path\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"bytes\"}],\"name\":\"sources\",\"type\":\"tuple[4]\"},{\"components\":[{\"name\":\"environmentObjectHash\",\"type\":\"bytes32\"},{\"name\":\"environmentManifestHash\",\"type\":\"bytes32\"},{\"name\":\"entrypoint\",\"type\":\"string\"},{\"name\":\"interpreter\",\"type\":\"string\"},{\"name\":\"launcher\",\"type\":\"string\"},{\"name\":\"sourceRoot\",\"type\":\"string\"},{\"name\":\"argv\",\"type\":\"string[]\"},{\"components\":[{\"name\":\"path\",\"type\":\"string\"},{\"name\":\"byteSize\",\"type\":\"uint64\"},{\"name\":\"sha256Digest\",\"type\":\"bytes32\"}],\"name\":\"members\",\"type\":\"tuple[]\"}],\"name\":\"runtime\",\"type\":\"tuple\"},{\"components\":[{\"name\":\"runtimeHash\",\"type\":\"bytes32\"},{\"name\":\"contextHash\",\"type\":\"bytes32\"},{\"name\":\"reportHash\",\"type\":\"bytes32\"},{\"name\":\"inputsHash\",\"type\":\"bytes32\"},{\"name\":\"inputManifest\",\"type\":\"bytes\"},{\"name\":\"transcript\",\"type\":\"bytes\"},{\"name\":\"executedAt\",\"type\":\"uint64\"},{\"name\":\"exitCode\",\"type\":\"uint32\"}],\"name\":\"replay\",\"type\":\"tuple\"}],\"name\":\"supplement\",\"type\":\"tuple\"}],\"canonicalization\":\"STREAM_SOLIDITY_ABI_V1\",\"encoding\":\"abi.encode(Supplement)\",\"id\":\"STREAM_REFERENCE_METRIC_SUPPLEMENT_ABI_V1\",\"limits\":{\"inputManifestBytes\":65536,\"parametersBytes\":65536,\"runtimeMembers\":2048,\"sourceFileBytes\":131072,\"totalBytes\":524288,\"transcriptBytes\":65536},\"provenance\":\"Original curator/global writer records exact source/package identities and an attributed restored replay; EVM does not execute Python.\",\"receiptDomain\":\"6529STREAM_METRIC_SUPPLEMENT_V1\",\"replayDomain\":\"6529STREAM_METRIC_REPLAY_V1\",\"runtimeDomain\":\"6529STREAM_METRIC_RUNTIME_V1\"}\n";
    bytes32 internal constant SCHEMA_HASH = 0xe1d65752e9ccd6217a35d52ac5c3358bd1b22211472b10cd38461bac1795677a;
    uint32 internal constant SCHEMA_BYTES = 1690;
    bytes32 internal constant PROFILE_ID = keccak256("STREAM_REFERENCE_METRIC_SUPPLEMENT_PROFILE_V1");
    string internal constant PROFILE_DOCUMENT = "{\"admission\":{\"authority\":\"Original selected-record scope, current actual CURATOR class3 or global class8 grant, before reference lock\",\"finality\":\"Exact supplement identity enters PERCEPTUAL input and locked component identity; absent or mismatched closure/replay refuses\",\"historical\":\"Original V1 receipt/payload/profile and reads remain available; CURATED and BYTE_EXACT finality identities unchanged\",\"onceOnly\":true},\"id\":\"STREAM_REFERENCE_METRIC_SUPPLEMENT_PROFILE_V1\",\"implementationIndex\":\"Canonical sorted compact JSON original four path to lowercase raw-file SHA256 hex, without 0x or newline\",\"kind\":\"original-record-bound-additive-metric-closure\",\"metricAndReport\":\"Unchanged original seven-field Metric and 6529STREAM_PERCEPTUAL_REPORT_V1 preimage\",\"parameters\":\"Exact bytes whose Keccak is original Metric.parametersHash\",\"referenceSchema\":\"STREAM_REFERENCE_MODE_ABI_V1\",\"replay\":{\"inputs\":\"Exact source-derived canonical JSON contextHash/environmentHash/evaluatedAt/threshold and capture-major firstSha256/secondSha256/viewport dimensions\",\"qualification\":\"Publisher-authenticated attributed restored execution. Offline validator must restore and run archived command, verify loaded dependencies/OS prerequisites and output. Declaration or source hash alone is insufficient.\",\"result\":\"Exit code zero, original reportHash, runtimeHash and inputHash, nonempty retained transcript, time no earlier than original metric evaluation\",\"transcriptEncoding\":\"abi.encode(keccak256(\\\"6529STREAM_METRIC_TRANSCRIPT_V1\\\"),runtimeHash,contextHash,reportHash,inputsHash,uint64(executedAt),uint32(exitCode),bytes(originalCanonicalDiagnosticJSON)); exact canonical tuple and all copied fields checked onchain\"},\"runtime\":{\"argv\":[\"-I\",\"-S\",\"-B\",\"metric/launch.py\"],\"entrypoint\":\"metric/source/tools/preservation/reference_metric.py\",\"environment\":\"Same original Publication.environment objectHash and manifestHash\",\"index\":\"metric/implementation.json\",\"interpreter\":\"metric/python/python.exe\",\"launcher\":\"metric/launch.py\",\"members\":\"Exact entire metric/ prefix of original environment.packageFiles, in the same strictly ordered path sequence\",\"parameters\":\"metric/parameters.json\",\"platform\":\"Original Windows AMD64 profile and exact declared OS prerequisite files; no claim to archive OS licenses or semantics\",\"sourceRoot\":\"metric/source\"},\"sourcePaths\":[\"tools/museum/canonical.py\",\"tools/museum/chain_abi.py\",\"tools/preservation/reference_manifest.py\",\"tools/preservation/reference_metric.py\"]}\n";
    bytes32 internal constant PROFILE_HASH = 0x9044071059abb70a02df3ebd40ce30ad024203d2058235540ff7c449ea8ef036;
    uint32 internal constant PROFILE_BYTES = 2499;
}
