// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @notice Exact WORK interpretation pins; actual registration is checked by the consumer.
/// @dev Generated by python -m tools.metadata.work_definitions. Do not edit.
library StreamWorkRecordDefinitions {
    bytes32 internal constant SCHEMA_ID = keccak256("STREAM_WORK_DESCRIPTION_V1");
    bytes32 internal constant SCHEMA_HASH =
        0xc534a4212c652d620942266ff32d8699bcc40492aa9a323e0f5b711bbc5bba88;
    uint256 internal constant SCHEMA_BYTES = 11481;
    bytes32 internal constant PROFILE_ID = keccak256("STREAM_WORK_DESCRIPTION_JSON_PROFILE_V1");
    bytes32 internal constant PROFILE_HASH =
        0x1c5e8281a5c12e06b334020bc158dc101dd33baaa449feeb8f504e20bd910353;
    uint256 internal constant PROFILE_BYTES = 2350;
    bytes32 internal constant CATALOG_SCHEMA_ID = keccak256("STREAM_WORK_FORMAT_CATALOG_V1");
    bytes32 internal constant CATALOG_SCHEMA_HASH =
        0xa2c03300254919dad0436cffd743bc869665f06434123b92ae48c5ff98a284ed;
    uint256 internal constant CATALOG_SCHEMA_BYTES = 1720;
    bytes32 internal constant CATALOG_PROFILE_ID =
        keccak256("STREAM_WORK_FORMAT_CATALOG_JSON_PROFILE_V1");
    bytes32 internal constant CATALOG_PROFILE_HASH =
        0x03799bc44aab386d3032a5859e6e7b7f6558bdb279f0e9906d3af535274a6514;
    uint256 internal constant CATALOG_PROFILE_BYTES = 957;
    bytes32 internal constant CANON_ID = keccak256("RFC8785_JCS");
    bytes32 internal constant CANON_HASH =
        0xbc33af15c6b6374052871a5fdfa255f900f56fa594f650b2d0814c681fdb35a9;
    uint256 internal constant CANON_BYTES = 362;
}
