// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// Generated by tools.preservation.prospective_reference_profile; do not edit.
library StreamProspectiveReferenceDefinitions {
    bytes32 public constant SCHEMA_ID = keccak256("STREAM_PROSPECTIVE_REFERENCE_ABI_V1");
    bytes32 public constant SCHEMA_HASH = 0x8416f4cb0125f5c2156d0105a7f02bda039c38399cccb2716a38163011a7efe6;
    uint32 public constant SCHEMA_BYTES = 9169;
    bytes32 public constant PROFILE_ID = keccak256("STREAM_PROSPECTIVE_NAMED_SIMULATION_PROFILE_V1");
    bytes32 public constant PROFILE_HASH = 0x62837f1da89beeeda117c5d509eeadda40a7cfb17441870bfe78295ff14f223c;
    uint32 public constant PROFILE_BYTES = 3630;
    bytes32 public constant CANON_ID = keccak256("STREAM_ABI_PROSPECTIVE_REFERENCE_V1");
    bytes32 public constant CANON_HASH = 0xa49312f8b4a2956768955836725736f560e4fc1b0b5a2b5257dc006db19b3668;
    uint32 public constant CANON_BYTES = 708;
}
