// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// Generated by tools.metadata.reference_render_profile; do not edit.
library StreamReferenceRenderDefinitions {
    bytes32 public constant RENDERER_SCHEMA_ID = keccak256("STREAM_RENDERER_CLASS_DECLARATION_V1");
    bytes32 public constant RENDERER_SCHEMA_HASH =
        0xce9047a5c3bc8ab8aa1b9a5f1cd77a1902725799750654135be9b6f942811bc1;
    uint32 public constant RENDERER_SCHEMA_BYTES = 838;
    bytes32 public constant RENDERER_PROFILE_ID =
        keccak256("STREAM_RENDERER_CLASS_DECLARATION_JSON_PROFILE_V1");
    bytes32 public constant RENDERER_PROFILE_HASH =
        0xbec0b224d0e79c1c8d775742321a8f0efb7caaa551ffbd5f758606517a8ad530;
    uint32 public constant RENDERER_PROFILE_BYTES = 1074;
    bytes32 public constant SCHEMA_ID = keccak256("STREAM_NATIVE_REFERENCE_RENDER_V1");
    bytes32 public constant SCHEMA_HASH =
        0xe644ff3dae5c1b778253b7c68239a2d56845fc14d711b6dcb7e7ebac7b6ab2e5;
    uint32 public constant SCHEMA_BYTES = 10288;
    bytes32 public constant PROFILE_ID =
        keccak256("STREAM_NATIVE_REFERENCE_RENDER_JSON_PROFILE_V1");
    bytes32 public constant PROFILE_HASH =
        0x4088e9ed35d57dd3d534d756282c50e92bc70dd7b5f30414b3327ab4247b1cab;
    uint32 public constant PROFILE_BYTES = 2801;
    bytes32 public constant ENVIRONMENT_SCHEMA_ID =
        keccak256("STREAM_REFERENCE_NATIVE_ENVIRONMENT_V1");
    bytes32 public constant ENVIRONMENT_SCHEMA_HASH =
        0xe09ea65b22dccf9a9528b0ec4c940a831be48a060f0a095157a65aff5b290b90;
    uint32 public constant ENVIRONMENT_SCHEMA_BYTES = 2236;
    bytes32 public constant PNG_SCHEMA_ID = keccak256("STREAM_REFERENCE_PNG_OBJECT_V1");
    bytes32 public constant PNG_SCHEMA_HASH =
        0x06dacccbad9218d04f77cbfdd597dfa61e2cab5b58c0fb8f5a1344ce301cb489;
    uint32 public constant PNG_SCHEMA_BYTES = 286;
    bytes32 public constant ZIP_SCHEMA_ID = keccak256("STREAM_REFERENCE_RUNTIME_ZIP_OBJECT_V1");
    bytes32 public constant ZIP_SCHEMA_HASH =
        0xb3cedd289be34a31fcd20d1941c86e28f31723e4c61f11ddf87894cda4903cac;
    uint32 public constant ZIP_SCHEMA_BYTES = 351;
    bytes32 public constant FORMAT_CATALOG_ID = keccak256("STREAM_REFERENCE_NATIVE_FORMATS_V1");
    bytes32 public constant FORMAT_CATALOG_HASH =
        0x91a426d25d6e00c056cea336611731171bfe84e1b90bf10f7e2e0d0edc6d8c03;
    uint32 public constant FORMAT_CATALOG_BYTES = 422;
    bytes32 public constant CANON_ID = keccak256("RFC8785_JCS");
    bytes32 public constant CANON_HASH =
        0xbc33af15c6b6374052871a5fdfa255f900f56fa594f650b2d0814c681fdb35a9;
    uint32 public constant CANON_BYTES = 362;
}
