// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;
import "../../regression/legacy/helpers/CharacterizationTestBase.sol";
import {
    StreamViewPreservationRenderCriticalStateV1 as State
} from "../../../smart-contracts/domains/preservation/StreamViewPreservationRenderCriticalStateV1.sol";
import {
    StreamViewPreservationRenderCriticalDefinitionsV1 as Definitions
} from "../../../smart-contracts/domains/preservation/StreamViewPreservationRenderCriticalDefinitionsV1.sol";
import {
    StreamViewPreservationRenderCriticalTypesV1 as View
} from "../../../smart-contracts/interfaces/stream/preservation/StreamViewPreservationRenderCriticalTypesV1.sol";
import {
    StreamRenderCriticalSourceTypes as S
} from "../../../smart-contracts/interfaces/stream/preservation/StreamRenderCriticalSourceTypes.sol";
import {
    StreamPreservationInventoryTypes as T
} from "../../../smart-contracts/interfaces/stream/preservation/StreamPreservationInventoryTypes.sol";
import {
    StreamFinalityScope,
    StreamFinalityScopeType
} from "../../../smart-contracts/interfaces/stream/finality/StreamArtworkFinalityTypes.sol";

/// @dev Test-owned storage namespace. Seeding a plan exercises refusal order only; no source proof
/// or final accepted inventory is generated by this probe.
contract ViewInventoryStateProbe {
    State.State private state;
    bytes32 public immutable dependency;
    uint256 public immutable deploymentChain = block.chainid;

    constructor(bytes32 d) {
        dependency = d;
        state.dependencyHash = d;
    }

    function id(View.Context memory c) external view returns (bytes32) {
        return State.idFor(dependency, c);
    }

    function common(View.Context memory c) external pure returns (S.Context memory) {
        return State.originalRecordContext(c);
    }

    function append(bytes32 id_, T.Item[] memory rows, bytes32 witness) external {
        State.append(state, id_, rows, witness);
    }

    function segment(bytes32 id_, uint64 n) external view returns (T.Segment memory) {
        return state.segments[id_][n];
    }

    function plan(bytes32 id_) external view returns (T.Plan memory) {
        return state.plans[id_].progress;
    }

    function seedRefusal(bytes32 id_, uint256 cid, uint16 stage, bytes32 complete) external {
        state.plans[id_].progress.collectionId = cid;
        state.plans[id_].progress.completedStages = stage;
        state.plans[id_].progress.renderCriticalEvidenceHash = complete;
    }

    function stage(bytes32 id_, uint16 expected) external view {
        State.stage(state, id_, expected);
    }

    function definition(uint64 index) external pure returns (bytes32, bytes32) {
        return Definitions.definition(index);
    }
}

contract StreamViewPreservationInventoryStateV1Test is CharacterizationTestBase {
    function _context() private pure returns (View.Context memory c) {
        c.scope = StreamFinalityScope(
            StreamFinalityScopeType.VIEW, 11, 0, keccak256("complete selected membership")
        );
        c.subject = keccak256("original VIEW subject");
        c.artistId = keccak256("selected artist");
        c.snapshot.recordHash = keccak256("genuine VIEW snapshot");
        c.referenceRender.observation.recordHash = keccak256("genuine VIEW reference");
        c.adoptionRecord = keccak256("original op17 renderer adoption");
        c.rootRecordHash = keccak256("separate original CONTENT_ROOT");
        c.viewId = keccak256("declaration distinct from scope");
        c.tokenCount = 3;
    }

    function testLiteralPlanBindsFullScopeBothReceiptsHostChainAndDependency() public {
        bytes32 d = keccak256("exact dependency roster");
        ViewInventoryStateProbe a = new ViewInventoryStateProbe(d);
        View.Context memory c = _context();
        bytes32 expected = keccak256(
            abi.encode(
                keccak256("6529STREAM_VIEW_PRESERVATION_RENDER_CRITICAL_PLAN_V1"),
                block.chainid,
                address(a),
                d,
                c
            )
        );
        require(a.id(c) == expected, "literal full context plan");
        ViewInventoryStateProbe b = new ViewInventoryStateProbe(d);
        require(b.id(c) != expected, "actual host namespace");
        for (uint256 i; i < 6; ++i) {
            View.Context memory changed = abi.decode(abi.encode(c), (View.Context));
            if (i == 0) changed.scope.scopeId = keccak256("same view other membership");
            if (i == 1) changed.scope.scopeType = StreamFinalityScopeType.RELEASE;
            if (i == 2) changed.snapshot.recordHash = keccak256("other snapshot");
            if (i == 3) {
                changed.referenceRender.observation.recordHash = keccak256("other reference");
            }
            if (i == 4) changed.viewId = keccak256("other declaration");
            if (i == 5) changed.rootRecordHash = keccak256("other signed root");
            require(a.id(changed) != expected, "all original identities committed");
        }
        uint256 originalChain = a.deploymentChain();
        vm.chainId(originalChain + 1);
        require(a.id(c) != expected, "original deployment chain");
        vm.chainId(originalChain);
        require(a.id(c) == expected, "restore exact plan");
    }

    function testCommonRecordProjectionNeverCastsViewReceipts() public {
        ViewInventoryStateProbe p = new ViewInventoryStateProbe(keccak256("deps"));
        View.Context memory c = _context();
        S.Context memory old = p.common(c);
        S.Context memory literal_;
        literal_.collectionId = 11;
        literal_.subject = c.subject;
        require(
            keccak256(abi.encode(old)) == keccak256(abi.encode(literal_)),
            "only original record coordinates"
        );
        require(
            old.snapshot.recordHash == 0 && old.referenceRender.recordHash == 0
                && old.artistId == 0,
            "no VIEW as legacy promotion"
        );
    }

    function _rows() private pure returns (T.Item[] memory rows) {
        rows = new T.Item[](2);
        for (uint256 i; i < 2; ++i) {
            rows[i].kind = T.Kind.NATIVE_BYTES;
            rows[i].role = keccak256(abi.encode("original role", i));
            rows[i].source = address(0x123);
            rows[i].sourceRecord = keccak256("actual record");
            rows[i].algorithm = 1;
            rows[i].canonicalizationId = keccak256("RAW_BYTES");
            rows[i].digest = abi.encodePacked(keccak256("same bytes distinct roles"));
            rows[i].byteSize = 24;
        }
    }

    function _literalLink(bytes32 key, uint64 index, T.Item memory row, bytes32 next)
        private
        pure
        returns (bytes32)
    {
        return keccak256(
            abi.encode(
                keccak256("6529STREAM_PRESERVATION_ITEM_LINK_V1"),
                key,
                uint64(2),
                index,
                keccak256(abi.encode(keccak256("6529STREAM_PRESERVATION_ITEM_V1"), row)),
                next
            )
        );
    }

    function testOrderedSegmentsRetainRepeatedBytesAndLiteralOriginalLinks() public {
        ViewInventoryStateProbe p = new ViewInventoryStateProbe(keccak256("deps"));
        bytes32 id = keccak256("plan");
        bytes32 witness = keccak256("complete original source");
        T.Item[] memory rows = _rows();
        p.append(id, rows, witness);
        p.append(id, rows, witness);
        bytes32 chain;
        for (uint64 i; i < 2; ++i) {
            T.Segment memory s = p.segment(id, i);
            bytes32 key = keccak256(
                abi.encode(
                    keccak256("6529STREAM_VIEW_PRESERVATION_RENDER_CRITICAL_SEGMENT_V1"), id, i
                )
            );
            require(
                s.key == key && s.itemCount == 2 && s.sourceWitnessHash == witness,
                "literal segment coordinates"
            );
            require(
                s.firstLink == _literalLink(key, 0, rows[0], _literalLink(key, 1, rows[1], 0)),
                "literal complete ordered roles"
            );
            chain =
                keccak256(abi.encode(keccak256("6529STREAM_PRESERVATION_SEGMENT_V1"), chain, i, s));
        }
        T.Plan memory plan = p.plan(id);
        require(
            plan.segmentCount == 2 && plan.itemCount == 4 && plan.segmentChainHash == chain,
            "every occurrence retained"
        );
        require(plan.renderCriticalEvidenceHash == 0, "segments alone do not seal source");
    }

    function testFailedAppendRollsBackAndIdenticalRowsCanRetry() public {
        ViewInventoryStateProbe p = new ViewInventoryStateProbe(keccak256("deps"));
        bytes32 id = keccak256("plan");
        T.Item[] memory rows = _rows();
        vm.expectRevert(abi.encodeWithSelector(T.InvalidInventorySegment.selector));
        p.append(id, rows, 0);
        require(
            p.plan(id).segmentCount == 0 && p.plan(id).itemCount == 0 && p.segment(id, 0).key == 0,
            "atomic failure"
        );
        p.append(id, rows, keccak256("source"));
        require(
            p.plan(id).segmentCount == 1 && p.plan(id).itemCount == 2, "same complete rows retry"
        );
    }

    function testUnpreparedWrongStageAndCompletedRefuseBeforeCurrentDependencyRead() public {
        ViewInventoryStateProbe p = new ViewInventoryStateProbe(keccak256("deps"));
        bytes32 id = keccak256("plan");
        vm.expectRevert(abi.encodeWithSelector(T.InventoryIncomplete.selector));
        p.stage(id, 8);
        p.seedRefusal(id, 11, 7, 0);
        vm.expectRevert(abi.encodeWithSelector(T.InventoryIncomplete.selector));
        p.stage(id, 8);
        p.seedRefusal(id, 11, 8, keccak256("complete"));
        vm.expectRevert(abi.encodeWithSelector(T.InventoryIncomplete.selector));
        p.stage(id, 8);
    }

    function testCompleteDefinitionRosterUsesViewProfilesAndNoLegacyReceiptSchema() public {
        ViewInventoryStateProbe p = new ViewInventoryStateProbe(keccak256("deps"));
        bytes32[36] memory ids;
        for (uint64 i; i < 36; ++i) {
            bytes32 hash;
            (ids[i], hash) = p.definition(i);
            require(ids[i] != 0 && hash != 0, "complete exact definition");
            for (uint64 j; j < i; ++j) {
                require(ids[i] != ids[j], "no duplicated fixed declaration");
            }
            require(
                ids[i] != keccak256("STREAM_NATIVE_ONCHAIN_SNAPSHOT_V1")
                    && ids[i] != keccak256("STREAM_NATIVE_REFERENCE_RENDER_V1")
                    && ids[i] != keccak256("STREAM_POLICY_COLLECTION_SNAPSHOT_ABI_V2"),
                "no profile substitution"
            );
        }
        vm.expectRevert(abi.encodeWithSelector(T.InvalidInventoryItem.selector));
        p.definition(36);
    }
}
