"""Versioned complete chunked snapshot schema, validator and exact-byte offline export.

Validation proves document self-consistency. Carrier/chain authority requires independently
verified recorded provenance; this tool never labels a synthetic document as a capture.
"""
import argparse
import base64
import json
import re
from pathlib import Path
from jsonschema import Draft202012Validator
from . import snapshot_profile as inline
from .work_profile import digest

ROOT = inline.ROOT
SCHEMA = "STREAM_CHUNKED_ONCHAIN_SNAPSHOT_V1"
PROFILE = "STREAM_CHUNKED_ONCHAIN_SNAPSHOT_JSON_PROFILE_V1"
MAXIMUM = 3000000
ZERO = "0x" + "00" * 32
RENDERER = digest(b"6529STREAM_ROUTER_CHUNKED_PRESENTATION_V1")
CHECKPOINT = digest(b"6529STREAM_CONTENT_CHUNKED_ONCHAIN_V1")

def schema():
    value = inline.schema()
    value["$id"] = SCHEMA
    p = value["properties"]
    h = p["profileHash"]
    u = p["chainId"]
    a = p["renderer"]["properties"]["address"]
    text = {"type": "string"}
    obj = inline.obj
    chunk = obj({"byteLength": u, "contentBase64": {"type": "string", "maxLength": 32768}, "contentHash": h, "index": u})
    chunks = {"type": "array", "minItems": 1, "maxItems": 32, "items": chunk}
    common = {"bundleId": h, "byteLength": u, "chunkCount": u, "chunks": chunks, "contentHash": h, "sourceType": u}
    manifest = obj({"chunkCount": u, "executable": {"const": True}, "libraryURI": text, "mimeType": {"const": "application/javascript"},
        "rendererCompatibility": {"const": RENDERER}, "scriptHash": h, "scriptURI": text, "sourcePointer": h, "sourceType": u})
    registry = obj({"address": a, "contentHash": h, "dependencyId": h, "runtimeHash": h, "version": u})
    p["script"] = obj({**common, "libraryBundle": h, "manifest": manifest, "manifestHash": h})
    p["library"] = {"oneOf": [{"type": "null"}, obj({**common, "registry": {"oneOf": [{"type": "null"}, registry]}})]}
    p["checkpointProfile"] = {"const": CHECKPOINT}
    p["version"] = {"const": 2}
    value["required"] = list(p)
    return value

def profile():
    result = inline.profile()
    result.update(name=PROFILE, schema=SCHEMA, version=2, manifestBytesMaximum=MAXIMUM,
        scriptBytesMaximum=786432, libraryBytesMaximum=786432, logicalChunkBytesMaximum=24576, logicalChunkCountMaximum=32,
        payloadEncoding="Ordered canonical Base64 logical chunks with exact byte lengths and Keccak-256 hashes; whole UTF8 payload reconstructed without normalization.",
        currentScope="COLLECTION chunked ONCHAIN script with optional immutable local or pinned-version registry library; complete declared payloads, not complete arbitrary web/runtime closure.")
    result["sourceRules"][3] = "Exact UTF8 name256, description2048, each URI2048; script and optional library each32x24576 bytes. UTF8 code points may cross logical chunk boundaries."
    result["sourceRules"] += ["Actual immutable bundle/ScriptManifest and selected chunk renderer; explicit chunked checkpoint, original content-root publication, complete leaf manifest and frozen entropy inventory.",
        "Registry contentHash is the original typed rolling chunk commitment; it is distinct from the whole payload hash.",
        "Compact token JSON links are not embedded payloads. Offline export writes only reconstructed verified bytes and retains the exact input manifest.",
        "Three-million-byte envelope admission is a source bound, not measured transaction or RPC gas capacity."]
    return result

def generated():
    docs = {f"schemas/records/{SCHEMA}.json": schema(), f"schemas/records/{PROFILE}.json": profile()}
    out = {p: (json.dumps(v, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode() for p,v in docs.items()}
    rows = [("SCHEMA",SCHEMA,out[f"schemas/records/{SCHEMA}.json"]),("PROFILE",PROFILE,out[f"schemas/records/{PROFILE}.json"]),
        ("CANON","RFC8785_JCS",(ROOT/"schemas/museum/account-profile/RFC8785_JCS.json").read_bytes())]
    lines = ["// SPDX-License-Identifier: MIT","pragma solidity ^0.8.19;","", "/// @dev Generated by python -m tools.metadata.chunked_snapshot_profile.","library StreamChunkedSnapshotDefinitions {"]
    for label,name,raw in rows:
        declaration = f'    bytes32 internal constant {label}_ID = keccak256("{name}");'
        lines += ([declaration] if len(declaration)<=100 else [f"    bytes32 internal constant {label}_ID =",f'        keccak256("{name}");'])
        lines += [f"    bytes32 internal constant {label}_HASH =",f"        {digest(raw)};",f"    uint256 internal constant {label}_BYTES = {len(raw)};"]
    out["smart-contracts/domains/records/StreamChunkedSnapshotDefinitions.sol"] = ("\n".join(lines+["}",""])).encode()
    return out

def _uint(text, maximum=(1<<256)-1):
    # Schema already requires a decimal string, but these width checks must not round.
    if not isinstance(text,str) or re.fullmatch(r"0|[1-9][0-9]*",text) is None: raise ValueError("exact decimal quantity")
    n=int(text)
    if n>maximum: raise ValueError("quantity width")
    return n

def _payload(row):
    if int(row["bundleId"],16)==0 or int(row["contentHash"],16)==0: raise ValueError("nonzero bundle commitment")
    if _uint(row["chunkCount"],32)!=len(row["chunks"]): raise ValueError("chunk count")
    parts=[]
    for i,c in enumerate(row["chunks"]):
        if _uint(c["index"])!=i: raise ValueError("ordered chunk index")
        raw=base64.b64decode(c["contentBase64"],validate=True)
        if base64.b64encode(raw).decode()!=c["contentBase64"]: raise ValueError("canonical Base64")
        if not 0<len(raw)<=24576 or _uint(c["byteLength"],24576)!=len(raw) or digest(raw)!=c["contentHash"]: raise ValueError("chunk bytes")
        parts.append(raw)
    raw=b"".join(parts)
    if not 0<len(raw)<=786432 or _uint(row["byteLength"],786432)!=len(raw) or digest(raw)!=row["contentHash"]: raise ValueError("payload bytes")
    if _uint(row["sourceType"])!=2 and any(len(part)>8192 for part in parts): raise ValueError("source-specific chunk bound")
    raw.decode("utf8",errors="strict")
    return raw

def _word(value):
    if isinstance(value,str): value=int(value,16) if value.startswith("0x") else int(value)
    return int(value).to_bytes(32,"big")

def _tuple(items):
    """ABI tuple of explicit static word spans or dynamic byte encodings (no guessed field widths)."""
    size=sum(32 if dynamic else len(raw) for dynamic,raw in items)
    head=[];tail=b""
    for dynamic,raw in items:
        if dynamic: head.append(_word(size+len(tail)));tail+=raw
        else: head.append(raw)
    return b"".join(head)+tail

def _text(text):
    raw=text.encode("utf8")
    return _word(len(raw))+raw+b"\0"*((-len(raw))%32)

def registry_hash(row):
    r=row["registry"];sequence=ZERO
    for i,c in enumerate(row["chunks"]):
        typed=digest(_word(digest(b"6529StreamDependencyScriptChunk(uint256 index,bytes32 chunkHash,uint256 byteLength)"))+_word(i)+_word(c["contentHash"])+_word(c["byteLength"]))
        sequence=digest(_word(sequence)+_word(typed))
    return digest(_word(digest(b"6529StreamDependencyScript(bytes32 dependencyNameAndVersion,uint256 chunkCount,bytes32 chunksHash)"))+_word(r["dependencyId"])+_word(row["chunkCount"])+_word(sequence))

def bundle_hash(value,row,is_library):
    source=ZERO
    if is_library and row["registry"] is not None:
        r=row["registry"]
        source=digest(b"".join(_word(r[k]) for k in ("address","runtimeHash","dependencyId","version","contentHash")))
    hashes=_word(len(row["chunks"]))+b"".join(_word(c["contentHash"]) for c in row["chunks"])
    lengths=_word(len(row["chunks"]))+b"".join(_word(c["byteLength"]) for c in row["chunks"])
    plan=_tuple([(False,_word(row["contentHash"])),(False,_word(row["sourceType"])),(True,hashes),(True,lengths),
        (False,_word(ZERO if is_library else row["libraryBundle"])),(False,_word(is_library))])
    return digest(_tuple([(False,_word(digest(b"6529STREAM_IMMUTABLE_SCRIPT_BUNDLE_V1"))),(False,_word(value["chainId"])),
        (False,_word(value["sources"][1]["address"])),(True,plan),(False,_word(source))]))

def manifest_hash(value):
    s=value["script"];m=s["manifest"]
    encoded=_tuple([(False,_word(m["scriptHash"])),(False,_word(m["rendererCompatibility"])),(False,_word(m["sourceType"])),
        (True,_text(m["libraryURI"])),(True,_text(m["scriptURI"])),(True,_text(m["sourcePointer"])),(True,_text(m["mimeType"])),
        (False,_word(m["chunkCount"])),(False,_word(m["executable"]))])
    facts=b"".join(_word(x) for x in (s["contentHash"],s["libraryBundle"],s["byteLength"],s["chunkCount"],s["sourceType"],False,True))
    return digest(_tuple([(False,_word(digest(b"6529STREAM_CHUNKED_SCRIPT_MANIFEST_V1"))),(False,_word(value["chainId"])),
        (False,_word(value["sources"][0]["address"])),(False,_word(value["sources"][1]["address"])),
        (False,_word(value["sources"][4]["address"])),(False,_word(value["sources"][4]["runtimeHash"])),
        (False,_word(value["collectionId"])),(False,_word(s["bundleId"])),(False,facts),(True,encoded)]))

def validate(raw):
    def pairs(rows):
        obj={}
        for k,v in rows:
            if k in obj: raise ValueError("duplicate JSON key")
            obj[k]=v
        return obj
    if not isinstance(raw,bytes) or not 0<len(raw)<=MAXIMUM: raise ValueError("manifest byte bound")
    v=json.loads(raw.decode("utf8"),object_pairs_hook=pairs,parse_constant=lambda _: (_ for _ in ()).throw(ValueError("nonfinite")))
    Draft202012Validator(schema()).validate(v)
    if type(v["version"]) is not int or v["version"]!=2: raise ValueError("literal version")
    if json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()!=raw: raise ValueError("canonical exact bytes")
    for key,want in (("schemaId",digest(SCHEMA.encode())),("schemaHash",digest(generated()[f"schemas/records/{SCHEMA}.json"])),("profileHash",digest(generated()[f"schemas/records/{PROFILE}.json"]))):
        if v[key]!=want: raise ValueError("registered interpretation pin")
    inline.validate_common(v)
    s=v["script"]; m=s["manifest"]; _payload(s)
    if _uint(s["sourceType"]) not in (1,2): raise ValueError("script source type")
    if (m["scriptHash"],m["sourceType"],m["chunkCount"],m["sourcePointer"])!=(s["contentHash"],s["sourceType"],s["chunkCount"],s["bundleId"]): raise ValueError("manifest/bundle facts")
    if int(s["manifestHash"],16)==0: raise ValueError("manifest hash")
    for field in ("scriptURI","libraryURI"):
        if len(m[field].encode())>2048: raise ValueError("manifest URI bound")
    if v["renderer"]["presentationProfile"]!=RENDERER or v["renderer"]["context"]!=digest(b"6529STREAM_CHUNKED_RENDER_CONTEXT_V1") or v["dependencyReadProfile"]!=digest(b"6529STREAM_PINNED_BUNDLE_DEPENDENCIES_V1"): raise ValueError("renderer profile")
    lib=v["library"]
    if s["libraryBundle"]==ZERO:
        if lib is not None or m["libraryURI"]: raise ValueError("absent library")
    else:
        if lib is None or lib["bundleId"]!=s["libraryBundle"]: raise ValueError("exact library bundle")
        _payload(lib)
        kind=_uint(lib["sourceType"])
        if kind not in (1,2,4): raise ValueError("library source type")
        reg=lib["registry"]
        if kind==4:
            if reg is None or any(int(reg[k],16)==0 for k in ("address","runtimeHash","dependencyId","contentHash")) or _uint(reg["version"])==0: raise ValueError("registry provenance")
            if registry_hash(lib)!=reg["contentHash"]: raise ValueError("registry typed rolling hash")
        elif reg is not None: raise ValueError("unexpected registry provenance")
        if bundle_hash(v,lib,True)!=lib["bundleId"]: raise ValueError("canonical library bundle")
    if bundle_hash(v,s,False)!=s["bundleId"]: raise ValueError("canonical script bundle")
    if manifest_hash(v)!=s["manifestHash"]: raise ValueError("canonical script manifest")
    return v

def export(raw, output):
    value=validate(raw)
    output=Path(output)
    # Validate before creating anything; never overwrite an existing capture/export.
    output.mkdir(parents=True,exist_ok=False)
    (output/"snapshot.json").write_bytes(raw)
    (output/"script.js").write_bytes(_payload(value["script"]))
    files=["snapshot.json","script.js"]
    if value["library"] is not None:
        (output/"library.js").write_bytes(_payload(value["library"]));files.append("library.js")
    report={"profile":PROFILE,"manifestHash":digest(raw),"files":{f:digest((output/f).read_bytes()) for f in files},
        "qualification":"Exact declared payload reconstruction and document self-consistency only. Chain/caller authority, captured provenance and external/browser execution closure are not established by this offline export."}
    (output/"export.json").write_text(json.dumps(report,sort_keys=True,indent=2)+"\n",encoding="utf8")
    return report

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true");parser.add_argument("--manifest",type=Path);parser.add_argument("--output",type=Path)
    args=parser.parse_args()
    if args.manifest:
        raw=args.manifest.read_bytes()
        if args.output: export(raw,args.output)
        else: validate(raw)
        return
    if args.output: parser.error("--output requires --manifest")
    for p,raw in generated().items():
        path=ROOT/p
        if args.check:
            if not path.exists() or path.read_bytes()!=raw: raise SystemExit(f"Chunked snapshot definition differs: {p}")
        else: path.write_bytes(raw)
    print("Chunked snapshot definition pins match.")

if __name__=="__main__": main()
