"""Generate exact immutable rights interpretation pins from the retained documents."""
from pathlib import Path
import argparse

from tools.protocol.check_drop_authorization_fixtures import keccak256

ROOT = Path(__file__).resolve().parents[2]
DOCUMENTS = (
    ("SCHEMA", "STREAM_RIGHTS_V1", "schemas/records/STREAM_RIGHTS_V1.json"),
    ("PROFILE", "STREAM_RIGHTS_JSON_PROFILE_V1", "schemas/records/STREAM_RIGHTS_JSON_PROFILE_V1.json"),
    ("CANON", "RFC8785_JCS", "schemas/museum/account-profile/RFC8785_JCS.json"),
)
TARGET = ROOT / "smart-contracts/domains/records/StreamRightsRecordDefinitions.sol"


def generated():
    lines = ["// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.19;", "",
             "/// @notice Exact retained definition pins; registration is verified by the consumer.",
             "/// @dev Generated by python -m tools.metadata.rights_definitions. Do not edit.",
             "library StreamRightsRecordDefinitions {"]
    for label, name, relative in DOCUMENTS:
        raw = (ROOT / relative).read_bytes()
        lines += [f'    bytes32 internal constant {label}_ID = keccak256("{name}");',
                  f"    bytes32 internal constant {label}_HASH = 0x{keccak256(raw).hex()};",
                  f"    uint256 internal constant {label}_BYTES = {len(raw)};"]
    lines += ["}", ""]
    return "\n".join(lines).encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_bytes() != expected:
            raise SystemExit("Rights definition pins differ; regenerate from the retained documents.")
    else:
        TARGET.write_bytes(expected)
    print("Rights definition pins match the three exact retained documents.")


if __name__ == "__main__":
    main()
