"""Generate exact immutable WORK interpretation pins from retained original documents."""

import argparse
from pathlib import Path

from .work_profile import digest

ROOT = Path(__file__).resolve().parents[2]
DOCUMENTS = (
    ("SCHEMA", "STREAM_WORK_DESCRIPTION_V1", "schemas/records/STREAM_WORK_DESCRIPTION_V1.json"),
    ("PROFILE", "STREAM_WORK_DESCRIPTION_JSON_PROFILE_V1", "schemas/records/STREAM_WORK_DESCRIPTION_JSON_PROFILE_V1.json"),
    ("CATALOG_SCHEMA", "STREAM_WORK_FORMAT_CATALOG_V1", "schemas/records/STREAM_WORK_FORMAT_CATALOG_V1.json"),
    ("CATALOG_PROFILE", "STREAM_WORK_FORMAT_CATALOG_JSON_PROFILE_V1", "schemas/records/STREAM_WORK_FORMAT_CATALOG_JSON_PROFILE_V1.json"),
    ("CANON", "RFC8785_JCS", "schemas/museum/account-profile/RFC8785_JCS.json"),
)
TARGET = ROOT / "smart-contracts/domains/records/StreamWorkRecordDefinitions.sol"


def generated():
    lines = ["// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.19;", "",
             "/// @notice Exact WORK interpretation pins; actual registration is checked by the consumer.",
             "/// @dev Generated by python -m tools.metadata.work_definitions. Do not edit.",
             "library StreamWorkRecordDefinitions {"]
    for label, name, relative in DOCUMENTS:
        raw = (ROOT / relative).read_bytes()
        identity = f'    bytes32 internal constant {label}_ID = keccak256("{name}");'
        if len(identity) > 100:
            lines += [f"    bytes32 internal constant {label}_ID =",
                      f'        keccak256("{name}");']
        else:
            lines.append(identity)
        lines += [f"    bytes32 internal constant {label}_HASH =",
                  f"        {digest(raw)};",
                  f"    uint256 internal constant {label}_BYTES = {len(raw)};"]
    return ("\n".join(lines + ["}", ""])).encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_bytes() != raw:
            raise SystemExit("WORK definition pins differ from exact retained documents")
    else:
        TARGET.write_bytes(raw)
    print("WORK definition pins match all five exact retained documents.")


if __name__ == "__main__":
    main()
