import { Interface, ZeroAddress, getAddress, id, isHexString, keccak256, toQuantity } from "ethers";
import type { Provider } from "ethers";
import type { Address, Hex } from "./generated/contracts.js";
import type { UnsignedCall } from "./client.js";
import { normalizeReferenceEnvironmentSnapshot, REFERENCE_ENVIRONMENT_ABI_TUPLE, REFERENCE_ENVIRONMENT_MAX_BYTES } from "./current-reference-environment.js";
import type { ReferenceEnvironmentSnapshot } from "./current-reference-environment.js";
import { prepareReferenceInventoryPlan } from "./current-reference-inventory-workflow.js";
import type { ReferenceInventoryDeployment, ReferenceInventoryChunk, ReferenceInventoryChunkAvailability, ReferenceInventoryStepStatus, ReferenceInventoryGasProvider, ReferenceInventoryEventReference } from "./current-reference-inventory-workflow.js";

export interface ReferenceEnvironmentStep { readonly index:number; readonly kind:"upload"|"environment"; readonly caller:Address; readonly call:UnsignedCall; readonly identity:Hex; readonly chunkIndex:number|null }
export interface PreparedReferenceEnvironmentPlan { readonly deployment:ReferenceInventoryDeployment; readonly preparer:Address; readonly uploader:Address; readonly snapshot:ReferenceEnvironmentSnapshot; readonly chunks:readonly ReferenceInventoryChunk[]; readonly steps:readonly ReferenceEnvironmentStep[] }
export interface ReferenceEnvironmentInspection { readonly plan:PreparedReferenceEnvironmentPlan; readonly blockNumber:number; readonly blockHash:Hex; readonly completed:boolean; readonly prerequisites:{readonly package:boolean;readonly platform:boolean}|null; readonly chunkAvailability:readonly ReferenceInventoryChunkAvailability[]; readonly steps:readonly ReferenceInventoryStepStatus[] }
export interface ReferenceEnvironmentGasQuote { readonly inspection:ReferenceEnvironmentInspection; readonly step:ReferenceEnvironmentStep; readonly scope:"inner-call"; readonly estimatedGas:bigint; readonly maximumGas:bigint|null; readonly withinMaximum:boolean }
export interface ReferenceEnvironmentStepReceipt { readonly plan:PreparedReferenceEnvironmentPlan; readonly step:ReferenceEnvironmentStep; readonly transactionHash:Hex; readonly blockNumber:number; readonly blockHash:Hex; readonly identity:Hex; readonly events:readonly ReferenceInventoryEventReference[]; readonly retention:"created"|"reused"; readonly priorBlock:{readonly number:number;readonly hash:Hex;readonly retained:boolean} }
type Reader=Pick<Provider,"getNetwork"|"getBlock"|"getCode"|"call">;
type ReceiptReader=Reader&Pick<Provider,"getTransaction"|"getTransactionReceipt">;
const environmentTuple=REFERENCE_ENVIRONMENT_ABI_TUPLE;
const hostAbi=new Interface([`function prepareEnvironment(${environmentTuple}) returns(bytes32 environmentId)`,"function preparedFileInventory(bytes32) view returns(bytes)","function deploymentChainId() view returns(uint256)","function dependencies() view returns(tuple(address[7] targets,bytes32[7] codeHashes,uint256 chainId,bytes32 rendererCatalogId,bytes32 rendererCatalogHash,uint32 rendererCatalogBytes,uint256 readGas,uint256 sourceGas,uint256 snapshotGas,uint256 archiveGas))","function supportsInterface(bytes4) pure returns(bool)","event ReferenceEnvironmentPrepared(uint16 schemaVersion,bytes32 indexed environmentId,bytes32 contentHash,uint32 byteLength)"]);
const storeAbi=new Interface(["function MAX_CHUNK_BYTES() view returns(uint256)","function chunk(bytes32) view returns(address pointer,uint32 length)","function publishChunk(bytes) returns(bytes32 hash,address pointer)","event ChunkPublished(bytes32 indexed hash,address indexed pointer,uint32 length)"]);
const safeAbi=new Interface(["function execTransaction(address to,uint256 value,bytes data,uint8 operation,uint256 safeTxGas,uint256 baseGas,uint256 gasPrice,address gasToken,address refundReceiver,bytes signatures) returns(bool)"]),safeLegacy=new Interface(["event ExecutionSuccess(bytes32 txHash,uint256 payment)","event ExecutionFailure(bytes32 txHash,uint256 payment)"]),safeIndexed=new Interface(["event ExecutionSuccess(bytes32 indexed txHash,uint256 payment)","event ExecutionFailure(bytes32 indexed txHash,uint256 payment)"]);
const invalidManifest=id("InvalidSnapshotManifest()").slice(0,10),MAX_BYTES=REFERENCE_ENVIRONMENT_MAX_BYTES;
function address(v:unknown,zero=false):Address {if(typeof v!=="string")throw Error("Expected address");const a=getAddress(v) as Address;if(!zero&&a===ZeroAddress)throw Error("Zero address");return a;}
function hash(v:unknown,zero=false):Hex {if(typeof v!=="string"||!isHexString(v,32)||(!zero&&/^0x0{64}$/i.test(v)))throw Error("Expected bytes32");return v.toLowerCase() as Hex;}
function bytes(v:unknown,max=MAX_BYTES+96):Hex {if(typeof v!=="string"||!isHexString(v,true)||(v.length-2)/2>max)throw Error("Malformed/oversized bytes");return v.toLowerCase() as Hex;}
function uint(v:unknown,positive=false):bigint {if(typeof v!=="bigint"||v<(positive?1n:0n)||v>=1n<<256n)throw Error("Expected uint256 bigint");return v;}
function integer(v:number):number {if(!Number.isSafeInteger(v)||v<0)throw Error("Expected concrete block/index");return v;}
function same(a:unknown,b:unknown):boolean {return typeof a==="string"&&typeof b==="string"&&a.toLowerCase()===b.toLowerCase();}
function stable(v:unknown):string{return JSON.stringify(v,(_,x:unknown)=>typeof x==="bigint"?`${x}n`:x&&typeof x==="object"&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);}
function equal(a:unknown,b:unknown,message="Prepared environment plan differs from canonical reconstruction"):void{if(stable(a)!==stable(b))throw Error(message);}
function keys(v:unknown,names:readonly string[]):void{if(!v||typeof v!=="object"||Array.isArray(v)||Object.keys(v).sort().join()!==[...names].sort().join())throw Error("Missing/unknown properties");}
function freeze<T>(v:T):T{if(v&&typeof v==="object"){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
function call(to:Address,abi:Interface,name:string,args:readonly unknown[]):UnsignedCall{return freeze({to,value:0n,data:abi.encodeFunctionData(name,args) as Hex});}
/** Inventory prerequisites remain original independent plans; only environment chunks and full-input preparation are included. */
export function prepareReferenceEnvironmentPlan(input:ReferenceInventoryDeployment,preparer:Address,snapshot:ReferenceEnvironmentSnapshot,options:{readonly uploader?:Address}={}):PreparedReferenceEnvironmentPlan{
  keys(options,options.uploader===undefined?[]:["uploader"]);const s=normalizeReferenceEnvironmentSnapshot(snapshot),actor=address(preparer),uploader=address(options.uploader??actor),existing=prepareReferenceInventoryPlan(input,actor,s.packageInventory,{mode:"monolithic",uploader}),d=existing.deployment;
  if(s.chainId!==d.chainId||!same(s.publicationHost,d.publicationHost.address))throw Error("Environment coordinates differ from deployment");
  const chunks:ReferenceInventoryChunk[]=[],steps:ReferenceEnvironmentStep[]=[],seen=new Set<string>();for(let offset=2;offset<s.canonical.length;offset+=16384){const raw=`0x${s.canonical.slice(offset,offset+16384)}` as Hex,h=keccak256(raw) as Hex;if(!seen.has(h)){seen.add(h);chunks.push({index:chunks.length,hash:h,bytes:raw});}}
  for(const chunk of chunks)steps.push({index:steps.length,kind:"upload",caller:uploader,call:call(d.store.address,storeAbi,"publishChunk",[chunk.bytes]),identity:chunk.hash,chunkIndex:chunk.index});
  steps.push({index:steps.length,kind:"environment",caller:actor,call:call(d.publicationHost.address,hostAbi,"prepareEnvironment",[s.environment]),identity:s.environmentId,chunkIndex:null});return freeze({deployment:d,preparer:actor,uploader,snapshot:s,chunks,steps});
}
function plan(v:PreparedReferenceEnvironmentPlan):PreparedReferenceEnvironmentPlan{const p=prepareReferenceEnvironmentPlan(v.deployment,v.preparer,v.snapshot,{uploader:v.uploader});equal(v,p);return p;}
function step(p:PreparedReferenceEnvironmentPlan,index:number):ReferenceEnvironmentStep{integer(index);const s=p.steps[index];if(!s)throw Error("Step outside plan");return s;}
async function rpc(p:Pick<Provider,"call">,target:Address,abi:Interface,name:string,args:readonly unknown[],tag:number,from?:Address):Promise<readonly unknown[]>{const raw=bytes(await p.call({...call(target,abi,name,args),blockTag:tag,...(from?{from}:{})})),r=abi.decodeFunctionResult(name,raw);if(!same(abi.encodeFunctionResult(name,r),raw))throw Error(`Noncanonical ${name} return`);return r;}
async function header(p:Pick<Provider,"getBlock">,tag:number):Promise<{number:number;hash:Hex}>{const b=await p.getBlock(tag);if(!b||b.number!==tag)throw Error("Missing/mismatched block");return {number:tag,hash:hash(b.hash)};}
async function unchanged(p:Pick<Provider,"getBlock">,h:{number:number;hash:Hex}):Promise<void>{equal(await header(p,h.number),h,"Pinned block changed");}
async function context(p:Reader,plan:PreparedReferenceEnvironmentPlan,tag:number):Promise<{number:number;hash:Hex}>{const d=plan.deployment;if((await p.getNetwork()).chainId!==d.chainId)throw Error("RPC chain mismatch");const h=await header(p,tag);await Promise.all([d.publicationHost,d.store].map(async pin=>{const code=bytes(await p.getCode(pin.address,tag),65536);if(code==="0x"||(code.length===48&&code.startsWith("0xef0100"))||!same(keccak256(code),pin.codeHash))throw Error("Pinned host/Store runtime differs");}));const [[chain],[dep],[max],[supported]]=await Promise.all([rpc(p,d.publicationHost.address,hostAbi,"deploymentChainId",[],tag),rpc(p,d.publicationHost.address,hostAbi,"dependencies",[],tag),rpc(p,d.store.address,storeAbi,"MAX_CHUNK_BYTES",[],tag),rpc(p,d.publicationHost.address,hostAbi,"supportsInterface",[hostAbi.getFunction("prepareEnvironment")!.selector],tag)]),dependencies=dep as {chainId:bigint;targets:readonly string[];codeHashes:readonly string[]};if(chain!==d.chainId||dependencies.chainId!==d.chainId||!same(dependencies.targets[3],d.store.address)||!same(dependencies.codeHashes[3],d.store.codeHash)||max!==8192n||supported!==true)throw Error("Host/Store chain, dependency or environment capability differs");return h;}
async function retained(p:Reader,plan:PreparedReferenceEnvironmentPlan,identity:Hex,expected:Hex,tag:number):Promise<boolean>{let r;try{r=await rpc(p,plan.deployment.publicationHost.address,hostAbi,"preparedFileInventory",[identity],tag);}catch(error){const e=error as {code?:unknown;data?:unknown};if(e.code==="CALL_EXCEPTION"&&same(e.data,invalidManifest))return false;throw error;}if(!same(bytes(r[0],MAX_BYTES),expected))throw Error("Retained bytes differ from exact canonical document");return true;}
async function availability(p:Reader,plan:PreparedReferenceEnvironmentPlan,c:ReferenceInventoryChunk,tag:number):Promise<ReferenceInventoryChunkAvailability>{const [target,len]=await rpc(p,plan.deployment.store.address,storeAbi,"chunk",[c.hash],tag),pointer=address(target,true),byteLength=uint(len);if(pointer===ZeroAddress){if(byteLength!==0n)throw Error("Missing chunk has nonzero length");return {index:c.index,hash:c.hash,available:false,pointer,byteLength};}if(byteLength!==BigInt((c.bytes.length-2)/2)||!same(bytes(await p.getCode(pointer,tag),8193),`0x00${c.bytes.slice(2)}`))throw Error("Store chunk is not exact STOP plus canonical bytes");return {index:c.index,hash:c.hash,available:true,pointer,byteLength};}
/** Existing retained environment bytes are checked before prerequisites; retries do not invent inventory history. */
export async function inspectReferenceEnvironmentPreparation(p:Reader,input:PreparedReferenceEnvironmentPlan,options:{readonly blockTag:number}):Promise<ReferenceEnvironmentInspection>{const plan_=plan(input),tag=integer(options.blockTag),h=await context(p,plan_,tag),s=plan_.snapshot;if(await retained(p,plan_,s.environmentId,s.canonical,tag)){await unchanged(p,h);return freeze({plan:plan_,blockNumber:tag,blockHash:h.hash,completed:true,prerequisites:null,chunkAvailability:[],steps:plan_.steps.map(x=>({index:x.index,status:x.kind==="environment"?"complete" as const:"unnecessary" as const,reason:x.kind==="environment"?"Exact original environment retained":"Environment complete; upload history not inferred"}))});}
  const prerequisites={package:await retained(p,plan_,s.packageInventory.inventoryId,s.packageInventory.canonical,tag),platform:await retained(p,plan_,s.platformInventory.inventoryId,s.platformInventory.canonical,tag)},chunks:ReferenceInventoryChunkAvailability[]=[];for(const c of plan_.chunks)chunks.push(await availability(p,plan_,c,tag));const ready=prerequisites.package&&prerequisites.platform&&chunks.every(c=>c.available),steps=plan_.steps.map(x=>({index:x.index,status:x.kind==="upload"?(chunks[x.chunkIndex!]!.available?"complete" as const:"ready" as const):ready?"ready" as const:"blocked" as const,reason:x.kind==="upload"?"Exact chunk availability inspected":ready?"Both full inventories and canonical environment chunks available":"Full inventories or environment chunks unavailable"}));await unchanged(p,h);return freeze({plan:plan_,blockNumber:tag,blockHash:h.hash,completed:false,prerequisites,chunkAvailability:chunks,steps});}
async function executable(p:Reader,plan:PreparedReferenceEnvironmentPlan,index:number,tag:number):Promise<ReferenceEnvironmentInspection>{const s=step(plan,index),i=await inspectReferenceEnvironmentPreparation(p,plan,{blockTag:tag});if(i.steps[index]!.status==="blocked"||(i.completed&&s.kind==="upload"))throw Error("Step is blocked or unnecessary at pinned block");return i;}
async function simulation(p:Reader,inspection:ReferenceEnvironmentInspection,s:ReferenceEnvironmentStep,tag:number):Promise<{identity:Hex;pointer:Address|null}>{const abi=s.kind==="upload"?storeAbi:hostAbi,name=s.kind==="upload"?"publishChunk":"prepareEnvironment",args=abi.decodeFunctionData(name,s.call.data),r=await rpc(p,s.call.to,abi,name,Array.from(args),tag,s.caller);if(!same(r[0],s.identity))throw Error("Simulated identity differs");const pointer=s.kind==="upload"?address(r[1]):null,observed=s.kind==="upload"?inspection.chunkAvailability[s.chunkIndex!]:undefined;if(observed?.available&&!same(observed.pointer,pointer))throw Error("Simulated retained chunk pointer differs");return freeze({identity:s.identity,pointer});}
export async function simulateReferenceEnvironmentStep(p:Reader,input:PreparedReferenceEnvironmentPlan,stepIndex:number,options:{readonly blockTag:number}):Promise<{readonly identity:Hex;readonly pointer:Address|null}>{const plan_=plan(input),s=step(plan_,stepIndex),tag=integer(options.blockTag),i=await executable(p,plan_,stepIndex,tag),out=await simulation(p,i,s,tag);await unchanged(p,{number:tag,hash:i.blockHash});return out;}
/** Quotes the actual-caller inner CALL only; Safe envelope/signature gas is excluded. */
export async function quoteReferenceEnvironmentStepGas(p:ReferenceInventoryGasProvider,input:PreparedReferenceEnvironmentPlan,stepIndex:number,options:{readonly blockTag:number;readonly maximumGas?:bigint}):Promise<ReferenceEnvironmentGasQuote>{const plan_=plan(input),s=step(plan_,stepIndex),tag=integer(options.blockTag),maximumGas=options.maximumGas===undefined?null:uint(options.maximumGas,true),i=await executable(p,plan_,stepIndex,tag);await simulation(p,i,s,tag);const raw=await p.send("eth_estimateGas",[{from:s.caller,to:s.call.to,data:s.call.data,value:"0x0"},toQuantity(tag)]);if(typeof raw!=="string"||!/^0x[1-9a-f][0-9a-f]*$/.test(raw)||raw.length>66)throw Error("Noncanonical gas estimate quantity");const estimatedGas=uint(BigInt(raw),true);await unchanged(p,{number:tag,hash:i.blockHash});return freeze({inspection:i,step:s,scope:"inner-call",estimatedGas,maximumGas,withinMaximum:maximumGas===null||estimatedGas<=maximumGas});}

/** First retention requires its exact event; an eventless retry needs intact prior-block evidence. */
export async function inspectReferenceEnvironmentStepReceipt(p:ReceiptReader,input:PreparedReferenceEnvironmentPlan,stepIndex:number,evidence:{readonly transactionHash:Hex;readonly execution:"direct"|"safe"}):Promise<ReferenceEnvironmentStepReceipt>{
  const plan_=plan(input),s=step(plan_,stepIndex);keys(evidence,["transactionHash","execution"]);const transactionHash=hash(evidence.transactionHash),execution=evidence.execution;if(execution!=="direct"&&execution!=="safe")throw Error("Unknown receipt mode");const [tx,receipt]=await Promise.all([p.getTransaction(transactionHash),p.getTransactionReceipt(transactionHash)]);
  if(!tx||!receipt||!same(tx.hash,transactionHash)||!same(receipt.hash,transactionHash)||receipt.status!==1||tx.chainId!==plan_.deployment.chainId||tx.blockNumber===null||!tx.blockHash||receipt.blockNumber!==tx.blockNumber||!same(receipt.blockHash,tx.blockHash)||!same(receipt.to,tx.to)||!same(receipt.from,tx.from)||tx.value!==0n||!tx.to||receipt.blockNumber<1)throw Error("Successful mined transaction/receipt identity differs");
  const tag=integer(receipt.blockNumber),blockHash=hash(receipt.blockHash),data=bytes(tx.data,2000000);if(execution==="direct"){if(!same(tx.from,s.caller)||!same(tx.to,s.call.to)||!same(data,s.call.data))throw Error("Direct step CALL differs");}else{if(!same(tx.to,s.caller))throw Error("Safe caller differs");const q=safeAbi.decodeFunctionData("execTransaction",data);if(!same(safeAbi.encodeFunctionData("execTransaction",q),data)||!same(q.to,s.call.to)||q.value!==0n||q.operation!==0n||!same(q.data,s.call.data))throw Error("Safe envelope differs from exact ordinary zero-value CALL");}
  if(!Array.isArray(receipt.logs)||receipt.logs.length>256)throw Error("Receipt log bound exceeded");let last=-1;const logs=receipt.logs.map(l=>{if(l.removed||l.blockNumber!==tag||!same(l.blockHash,blockHash)||!same(l.transactionHash,transactionHash)||integer(l.index)<=last||!Array.isArray(l.topics)||l.topics.length<1||l.topics.length>4)throw Error("Receipt log identity/order differs");last=l.index;return {address:address(l.address),data:bytes(l.data,16384),topics:l.topics.map((v:string)=>hash(v,true)),index:l.index};});
  const refs:ReferenceInventoryEventReference[]=[];const parse=(target:Address,abi:Interface,name:string)=>{const fragment=abi.getEvent(name)!;return logs.filter(l=>same(l.address,target)&&same(l.topics[0],fragment.topicHash)).map(l=>{const decoded=abi.decodeEventLog(fragment,l.data,l.topics),canonical=abi.encodeEventLog(fragment,decoded);if(!same(canonical.data,l.data))throw Error(`Noncanonical ${name} event`);equal(canonical.topics.map(t=>t.toLowerCase()),l.topics,"Noncanonical event topics");return {decoded,ref:{address:target,event:name,logIndex:l.index,transactionHash,blockHash}};});};
  if(execution==="safe"){const success=logs.filter(l=>same(l.address,s.caller)&&same(l.topics[0],safeLegacy.getEvent("ExecutionSuccess")!.topicHash));if(success.length!==1||logs.some(l=>same(l.address,s.caller)&&same(l.topics[0],safeLegacy.getEvent("ExecutionFailure")!.topicHash)))throw Error("Expected one Safe success and no failure");const parsed=parse(s.caller,success[0]!.topics.length===2?safeIndexed:safeLegacy,"ExecutionSuccess")[0]!;hash(parsed.decoded.txHash);refs.push(parsed.ref);}
  const h=await context(p,plan_,tag),prior=await context(p,plan_,tag-1);if(!same(h.hash,blockHash))throw Error("Receipt block is not canonical");let previouslyRetained:boolean,emitted:ReturnType<typeof parse>;
  if(s.kind==="upload"){if(parse(plan_.deployment.publicationHost.address,hostAbi,"ReferenceEnvironmentPrepared").length)throw Error("Unexpected environment event during upload");const chunk=plan_.chunks[s.chunkIndex!]!,available=await availability(p,plan_,chunk,tag);if(!available.available)throw Error("Mined chunk unavailable");const previous=await availability(p,plan_,chunk,tag-1);previouslyRetained=previous.available;if(previous.available&&!same(previous.pointer,available.pointer))throw Error("Immutable retained chunk pointer changed");emitted=parse(plan_.deployment.store.address,storeAbi,"ChunkPublished");for(const e of emitted){if(!same(e.decoded.hash,s.identity)||!same(e.decoded.pointer,available.pointer)||e.decoded[2]!==available.byteLength)throw Error("Chunk publication event differs");}}
  else{if(parse(plan_.deployment.store.address,storeAbi,"ChunkPublished").length)throw Error("Unexpected upload event during environment preparation");if(!await retained(p,plan_,s.identity,plan_.snapshot.canonical,tag))throw Error("Mined environment unavailable");previouslyRetained=await retained(p,plan_,s.identity,plan_.snapshot.canonical,tag-1);emitted=parse(plan_.deployment.publicationHost.address,hostAbi,"ReferenceEnvironmentPrepared");for(const e of emitted){const v=e.decoded;if(v.schemaVersion!==1n||!same(v.environmentId,s.identity)||!same(v.contentHash,plan_.snapshot.contentHash)||v.byteLength!==plan_.snapshot.byteLength)throw Error("Environment event differs from original canonical bytes");}}
  if(emitted.length>1)throw Error("Duplicate retention events");if(!emitted.length&&!previouslyRetained)throw Error("Eventless retry requires prior-block retained evidence; same-block history is unproven");if(emitted.length&&previouslyRetained)throw Error("First-retention event contradicts immutable prior-block evidence");for(const e of emitted)refs.push(e.ref);const success=refs.find(e=>e.event==="ExecutionSuccess");if(success&&refs.some(e=>e.event!=="ExecutionSuccess"&&e.logIndex>=success.logIndex))throw Error("Safe success must follow retention events");
  await unchanged(p,prior);await unchanged(p,h);return freeze({plan:plan_,step:s,transactionHash,blockNumber:tag,blockHash,identity:s.identity,events:refs.sort((a,b)=>a.logIndex-b.logIndex),retention:emitted.length?"created":"reused",priorBlock:{...prior,retained:previouslyRetained}});
}
