import { AbiCoder, Interface, ParamType, ZeroAddress, ZeroHash, getAddress, id, isHexString, keccak256, toUtf8Bytes } from "ethers";
import type { Address, Hex } from "./generated/contracts.js";
import type { UnsignedCall } from "./binding.js";
import * as policy from "./current-entropy-collection-policy.js";
import * as instant from "./current-entropy-instant.js";
import * as fallback from "./current-mint-fallback.js";
import { CURRENT_ARTIST_RECOVERY_GOVERNANCE_ABI, ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE } from "./current-artist-recovery-adjudication.js";

/** Separate original succession profile; no historical entropy profile is changed. */
export const ENTROPY_POLICY_SUCCESSION_SOURCE = "7901f3b108a7acc44780e6b686157d1016059e52";
export const ENTROPY_POLICY_SUCCESSION_PLAN_SOURCE = "3fab88e16549e9c06a339b7ef9a98562c6a9bfea";
export const ENTROPY_POLICY_SUCCESSION_KIND = id("ENTROPY_COORDINATOR") as Hex;
/** Client allocation bound, not an on-chain inventory capacity. */
export const ENTROPY_POLICY_SUCCESSION_MAX_INVENTORY = 4096;
export interface EntropyPolicySuccessionConfiguration { readonly chainId: bigint; readonly core: Address; readonly moduleRegistry: Address; readonly executor: Address; readonly roleRegistry: Address; readonly predecessor: Address; readonly predecessorCodeHash: Hex; readonly candidate: Address; readonly candidateCodeHash: Hex; readonly manifest: Address }
export interface EntropyPolicySuccessionRuntime { readonly target: Address; readonly codeHash: Hex }
/** Source-derived inventory header, whose ABI getter returns three separate words. */
export interface EntropyPolicySuccessionInventoryHeader { readonly count: bigint; readonly serial: bigint; readonly idDigest: Hex }
export type EntropyPolicySuccessionPolicyInput = policy.EntropyCollectionPolicyInput;
export type EntropyPolicySuccessionPolicyRecord = policy.EntropyCollectionPolicyRecord;
export type EntropyPolicySuccessionCollectionRecovery = policy.EntropyCollectionPolicyRecovery;
export interface EntropyPolicySuccessionPolicyExport { readonly collectionId: bigint; readonly profile: 0n | 1n; readonly policyOrigin: Address; readonly policyOriginCodeHash: Hex; readonly record: EntropyPolicySuccessionPolicyRecord; readonly policy: EntropyPolicySuccessionPolicyInput; readonly providerCodeHash: Hex; readonly providerConfigHash: Hex; readonly recovery: EntropyPolicySuccessionCollectionRecovery }
export interface EntropyPolicySuccessionRecoveryStep { readonly provider: Address; readonly providerEpoch: bigint; readonly providerConfigHash: Hex; readonly notBeforeBlocks: bigint; readonly acceptLateOriginalFulfillment: boolean }
export interface EntropyPolicySuccessionRecoveryPolicy { readonly exists: boolean; readonly frozen: boolean; readonly maxFreshRecoveryAttempts: bigint; readonly incidentDeclarerRole: Hex; readonly reasonSchemaHash: Hex; readonly policyManifestHash: Hex; readonly steps: readonly EntropyPolicySuccessionRecoveryStep[] }
export interface EntropyPolicySuccessionRecoveryExport { readonly policyId: Hex; readonly policy: EntropyPolicySuccessionRecoveryPolicy; readonly policyHash: Hex; readonly revision: bigint; readonly lastActionId: Hex; readonly policyOrigin: Address; readonly policyOriginCodeHash: Hex; readonly successor: Address; readonly successorCodeHash: Hex }
export interface EntropyPolicySuccessionImportReceipt { readonly state: 0n | 1n | 2n | 3n; readonly nonce: bigint; readonly predecessor: Address; readonly predecessorCodeHash: Hex; readonly pointerRevision: bigint; readonly count: bigint; readonly serial: bigint; readonly idDigest: Hex; readonly manifestHash: Hex; readonly nextIndex: bigint; readonly exportDigest: Hex; readonly requiredRelayCount: bigint; readonly confirmedRelayCount: bigint; readonly importHash: Hex; readonly beginActionId: Hex; readonly sealActionId: Hex; readonly activationActionId: Hex }
export interface EntropyPolicySuccessionImportedPolicy { readonly importHash: Hex; readonly exportHash: Hex; readonly policyOrigin: Address; readonly policyOriginCodeHash: Hex; readonly policyHash: Hex }
export interface EntropyPolicySuccessionAdmission { readonly successorCodeHash: Hex; readonly importHash: Hex; readonly policyHash: Hex }
export type EntropyPolicySuccessionRequestPolicySnapshot = instant.EntropyInstantRequestPolicySnapshot;
export interface EntropyPolicySuccessionRelayInput { readonly importHash: Hex; readonly collectionId: bigint; readonly tokenId: bigint; readonly scopeId: Hex; readonly successorRequestKey: Hex; readonly policy: EntropyPolicySuccessionRequestPolicySnapshot }
export interface EntropyPolicySuccessionRelayResult { readonly successor: Address; readonly successorCodeHash: Hex; readonly importHash: Hex; readonly collectionId: bigint; readonly successorRequestKey: Hex; readonly provider: Address; readonly providerCodeHash: Hex; readonly providerConfigHash: Hex; readonly providerRequestId: bigint; readonly relayId: Hex; readonly contextHash: Hex; readonly submitted: boolean; readonly rawReceived: boolean; readonly delivered: boolean; readonly terminalStale: boolean; readonly raw: Hex; readonly lastOutcome: bigint }
export type EntropyPolicySuccessionPointer = fallback.MintFallbackPointerState;
export type EntropyPolicySuccessionRegistration = fallback.MintFallbackRegistration;
export type EntropyPolicySuccessionManifestState = fallback.MintFallbackManifestState;
export type EntropyPolicySuccessionManifestUpdate = fallback.MintFallbackManifestUpdate;
export type EntropyPolicySuccessionGovernanceCall = fallback.MintFallbackGovernanceCall;
export type EntropyPolicySuccessionGovernanceWindow = fallback.MintFallbackGovernanceWindow;
export type EntropyPolicySuccessionTransition = fallback.MintFallbackTransition;
export interface EntropyPolicySuccessionCatalogRow { readonly actionClass: bigint; readonly target: Address; readonly selector: Hex; readonly targetCodeHash: Hex; readonly targetProfileHash: Hex; readonly callType: bigint; readonly valuePolicy: bigint; readonly valueLimit: bigint; readonly valueSemanticsHash: Hex }
export interface EntropyPolicySuccessionCatalogState { readonly candidateProfileHash: Hex; readonly catalogHash: Hex; readonly entryCount: bigint; readonly revision: bigint }
/** Complete original bind followed by the actual ordered extension groups, not a flattened replacement. */
export interface EntropyPolicySuccessionCatalogHistory { readonly initialRows: readonly EntropyPolicySuccessionCatalogRow[]; readonly extensions: readonly (readonly EntropyPolicySuccessionCatalogRow[])[] }
/** Original script inventory, source-derived rather than a new on-chain tuple. */
export interface EntropyPolicySuccessionCatalogInventory { readonly chainId: bigint; readonly executor: Address; readonly executorCodeHash: Hex; readonly candidateProfileHash: Hex; readonly baseCatalogHash: Hex; readonly baseEntryCount: bigint; readonly baseRevision: bigint; readonly additions: readonly EntropyPolicySuccessionCatalogRow[] }

export const ENTROPY_POLICY_SUCCESSION_POLICY_INPUT_TUPLE = policy.ENTROPY_COLLECTION_POLICY_INPUT_TUPLE;
export const ENTROPY_POLICY_SUCCESSION_POLICY_RECORD_TUPLE = policy.ENTROPY_COLLECTION_POLICY_RECORD_TUPLE;
export const ENTROPY_POLICY_SUCCESSION_COLLECTION_RECOVERY_TUPLE = policy.ENTROPY_COLLECTION_POLICY_RECOVERY_TUPLE;
export const ENTROPY_POLICY_SUCCESSION_POLICY_EXPORT_TUPLE = `tuple(uint256 collectionId,uint8 profile,address policyOrigin,bytes32 policyOriginCodeHash,${ENTROPY_POLICY_SUCCESSION_POLICY_RECORD_TUPLE} record,${ENTROPY_POLICY_SUCCESSION_POLICY_INPUT_TUPLE} policy,bytes32 providerCodeHash,bytes32 providerConfigHash,${ENTROPY_POLICY_SUCCESSION_COLLECTION_RECOVERY_TUPLE} recovery)`;
export const ENTROPY_POLICY_SUCCESSION_RECOVERY_STEP_TUPLE = "tuple(address provider,uint32 providerEpoch,bytes32 providerConfigHash,uint64 notBeforeBlocks,bool acceptLateOriginalFulfillment)";
export const ENTROPY_POLICY_SUCCESSION_RECOVERY_POLICY_TUPLE = `tuple(bool exists,bool frozen,uint16 maxFreshRecoveryAttempts,bytes32 incidentDeclarerRole,bytes32 reasonSchemaHash,bytes32 policyManifestHash,${ENTROPY_POLICY_SUCCESSION_RECOVERY_STEP_TUPLE}[] steps)`;
export const ENTROPY_POLICY_SUCCESSION_RECOVERY_EXPORT_TUPLE = `tuple(bytes32 policyId,${ENTROPY_POLICY_SUCCESSION_RECOVERY_POLICY_TUPLE} policy,bytes32 policyHash,uint64 revision,bytes32 lastActionId,address policyOrigin,bytes32 policyOriginCodeHash,address successor,bytes32 successorCodeHash)`;
export const ENTROPY_POLICY_SUCCESSION_IMPORT_RECEIPT_TUPLE = "tuple(uint8 state,uint64 nonce,address predecessor,bytes32 predecessorCodeHash,uint64 pointerRevision,uint256 count,uint64 serial,bytes32 idDigest,bytes32 manifestHash,uint256 nextIndex,bytes32 exportDigest,uint256 requiredRelayCount,uint256 confirmedRelayCount,bytes32 importHash,bytes32 beginActionId,bytes32 sealActionId,bytes32 activationActionId)";
export const ENTROPY_POLICY_SUCCESSION_IMPORTED_POLICY_TUPLE = "tuple(bytes32 importHash,bytes32 exportHash,address policyOrigin,bytes32 policyOriginCodeHash,bytes32 policyHash)";
export const ENTROPY_POLICY_SUCCESSION_ADMISSION_TUPLE = "tuple(bytes32 successorCodeHash,bytes32 importHash,bytes32 policyHash)";
export const ENTROPY_POLICY_SUCCESSION_INVENTORY_HEADER_TUPLE = "tuple(uint256 count,uint64 serial,bytes32 idDigest)";
export const ENTROPY_POLICY_SUCCESSION_REQUEST_POLICY_SNAPSHOT_TUPLE = instant.ENTROPY_INSTANT_REQUEST_POLICY_TUPLE;
export const ENTROPY_POLICY_SUCCESSION_RELAY_INPUT_TUPLE = `tuple(bytes32 importHash,uint256 collectionId,uint256 tokenId,bytes32 scopeId,bytes32 successorRequestKey,${ENTROPY_POLICY_SUCCESSION_REQUEST_POLICY_SNAPSHOT_TUPLE} policy)`;
export const ENTROPY_POLICY_SUCCESSION_RELAY_RESULT_TUPLE = "tuple(address successor,bytes32 successorCodeHash,bytes32 importHash,uint256 collectionId,bytes32 successorRequestKey,address provider,bytes32 providerCodeHash,bytes32 providerConfigHash,uint256 providerRequestId,bytes32 relayId,bytes32 contextHash,bool submitted,bool rawReceived,bool delivered,bool terminalStale,bytes32 raw,uint8 lastOutcome)";
export const ENTROPY_POLICY_SUCCESSION_POINTER_TUPLE = "tuple(address target,bytes32 codeHash,bool frozen,bytes32 moduleType,bytes4 interfaceId,address registry,uint8 registryStatus,bytes32 moduleManifestHash,bytes32 deploymentManifestHash,uint64 revision)";
export const ENTROPY_POLICY_SUCCESSION_REGISTRATION_TUPLE = "tuple(address module,bytes32 moduleType,bytes32 moduleVersion,bytes4 interfaceId,uint32 moduleGasLimit,bytes32 expectedRuntimeCodeHash,bytes32 deploymentManifestHash,bytes32 moduleManifestHash,string moduleManifestURI)";
export const ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE = "tuple(uint8 actionClass,address target,bytes4 selector,bytes32 targetCodeHash,bytes32 targetProfileHash,uint8 callType,uint8 valuePolicy,uint256 valueLimit,bytes32 valueSemanticsHash)";
export const ENTROPY_POLICY_SUCCESSION_CATALOG_STATE_TUPLE = "tuple(bytes32 candidateProfileHash,bytes32 catalogHash,uint256 entryCount,uint64 revision)";
export const ENTROPY_POLICY_SUCCESSION_CATALOG_INVENTORY_TUPLE = `tuple(uint256 chainId,address executor,bytes32 executorCodeHash,bytes32 candidateProfileHash,bytes32 baseCatalogHash,uint256 baseEntryCount,uint64 baseRevision,${ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE}[] additions)`;
export const ENTROPY_POLICY_SUCCESSION_MANIFEST_UPDATE_TUPLE = "tuple(bytes32 manifestHash,string manifestURI,bytes32 eventCatalogHash,bytes32 compatibilityMatrixHash,bytes32 numericIdCatalogHash,bytes32 schemaCatalogHash,bytes32 canonicalizationCatalogHash,bytes32 specBundleHash,bytes32 reconstructionClientHash)";
export const ENTROPY_POLICY_SUCCESSION_GOVERNANCE_CALL_TUPLE = ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE;
const coder = AbiCoder.defaultAbiCoder(), zeroHash = ZeroHash as Hex;
function exact(value: unknown, keys: readonly string[]): void { if (!value || typeof value !== "object" || Array.isArray(value)) throw Error("Expected object"); const actual = Reflect.ownKeys(value); if (actual.length !== keys.length || actual.some(k => typeof k !== "string" || !keys.includes(k))) throw Error("Missing or unknown fields"); }
function uint(v: unknown, bits: number): bigint { if (typeof v !== "bigint" || v < 0n || v >= 1n << BigInt(bits)) throw Error(`Expected uint${bits} bigint`); return v; }
function hex(v: unknown, size?: number): Hex { if (typeof v !== "string" || !isHexString(v, size) || v.length % 2 !== 0) throw Error("Expected hex bytes"); return v.toLowerCase() as Hex; }
function nz(v: Hex): Hex { if (v === ZeroHash) throw Error("Expected nonzero hash"); return v; }
function address(v: unknown, nonzero = false): Address { if (typeof v !== "string") throw Error("Expected address"); const a = getAddress(v) as Address; if (nonzero && a === ZeroAddress) throw Error("Expected nonzero address"); return a; }
function dense(v: unknown, max: number): readonly unknown[] { if (!Array.isArray(v) || v.length > max || Reflect.ownKeys(v).length !== v.length + 1 || Array.from({ length: v.length }, (_, i) => i).some(i => !Object.hasOwn(v, i))) throw Error("Expected bounded dense array"); return v; }
function normal(p: ParamType, v: unknown, decoded = false): unknown {
  if (p.baseType === "array") return Object.freeze(dense(v, p.name === "steps" ? 32 : ENTROPY_POLICY_SUCCESSION_MAX_INVENTORY).map(x => normal(p.arrayChildren!, x, decoded)));
  if (p.baseType === "tuple") { if (!decoded) exact(v, p.components!.map(f => f.name)); return Object.freeze(Object.fromEntries(p.components!.map((f, i) => [f.name, normal(f, decoded ? (v as readonly unknown[])[i] : Reflect.get(v as object, f.name), decoded)]))); }
  if (p.type === "address") return address(v);
  if (p.type === "bool") { if (typeof v !== "boolean") throw Error("Expected boolean"); return v; }
  if (p.type.startsWith("uint")) { const x = uint(v, Number(p.type.slice(4))); if ((p.name === "profile" || p.name === "securityClass" || p.name === "renderRequirement") && x > 1n || p.name === "mode" && x > 2n || p.name === "state" && x > 3n) throw Error("Unknown original enum"); return x; }
  if (p.type === "string") { if (typeof v !== "string" || /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(v) || toUtf8Bytes(v).length > 2048) throw Error("Expected bounded Unicode text"); return v; }
  if (p.type.startsWith("bytes")) return hex(v, Number(p.type.slice(5)) || undefined);
  throw Error("Unsupported source ABI type");
}
function normalize<T>(type: string, v: T): T { return normal(ParamType.from(type), v) as T; }
function encoded(type: string, v: unknown): Hex { return coder.encode([type], [normalize(type, v)]) as Hex; }
function decoded<T>(type: string, v: Hex, max = 65536): T { const raw = hex(v); if (raw.length > 2 + 2 * max) throw Error("Encoded data exceeds bound"); const value = normal(ParamType.from(type), coder.decode([type], raw)[0], true) as T; if (encoded(type, value) !== raw) throw Error("Noncanonical ABI encoding"); return value; }
function hash(types: readonly (string | ParamType)[], values: readonly unknown[]): Hex { return keccak256(coder.encode(types, values)) as Hex; }
function same(a: unknown, b: unknown): boolean { if (a === b) return true; if (!a || !b || typeof a !== "object" || typeof b !== "object") return false; const keys = Reflect.ownKeys(a), other = Reflect.ownKeys(b); return keys.length === other.length && keys.every(k => other.includes(k) && same(Reflect.get(a, k), Reflect.get(b, k))); }
function next64(v: bigint): bigint { return uint(v + 1n, 64); }
export function normalizeEntropyPolicySuccessionConfiguration(v: EntropyPolicySuccessionConfiguration): EntropyPolicySuccessionConfiguration { exact(v, ["chainId", "core", "moduleRegistry", "executor", "roleRegistry", "predecessor", "predecessorCodeHash", "candidate", "candidateCodeHash", "manifest"]); const c = Object.freeze({ chainId: uint(v.chainId, 256), core: address(v.core, true), moduleRegistry: address(v.moduleRegistry, true), executor: address(v.executor, true), roleRegistry: address(v.roleRegistry, true), predecessor: address(v.predecessor, true), predecessorCodeHash: nz(hex(v.predecessorCodeHash, 32)), candidate: address(v.candidate, true), candidateCodeHash: nz(hex(v.candidateCodeHash, 32)), manifest: address(v.manifest, true) }); if (c.predecessor === c.candidate) throw Error("Distinct predecessor and candidate required"); return c; }
export function normalizeEntropyPolicySuccessionRuntime(v: EntropyPolicySuccessionRuntime): EntropyPolicySuccessionRuntime { exact(v, ["target", "codeHash"]); return Object.freeze({ target: address(v.target, true), codeHash: nz(hex(v.codeHash, 32)) }); }
export const normalizeEntropyPolicySuccessionPointer = fallback.normalizeMintFallbackPointerState;
export const normalizeEntropyPolicySuccessionManifestState = fallback.normalizeMintFallbackManifestState;
export const normalizeEntropyPolicySuccessionManifestUpdate = fallback.normalizeMintFallbackManifestUpdate;
export const normalizeEntropyPolicySuccessionGovernanceWindow = fallback.normalizeMintFallbackGovernanceWindow;

export function normalizeEntropyPolicySuccessionInventoryHeader(v: EntropyPolicySuccessionInventoryHeader): EntropyPolicySuccessionInventoryHeader { return normalize(ENTROPY_POLICY_SUCCESSION_INVENTORY_HEADER_TUPLE, v); }
export function encodeEntropyPolicySuccessionInventoryHeader(v: EntropyPolicySuccessionInventoryHeader): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_INVENTORY_HEADER_TUPLE, normalizeEntropyPolicySuccessionInventoryHeader(v)); }
export function decodeEntropyPolicySuccessionInventoryHeader(v: Hex): EntropyPolicySuccessionInventoryHeader { return normalizeEntropyPolicySuccessionInventoryHeader(decoded(ENTROPY_POLICY_SUCCESSION_INVENTORY_HEADER_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionPolicyInput(v: EntropyPolicySuccessionPolicyInput): EntropyPolicySuccessionPolicyInput { return normalize(ENTROPY_POLICY_SUCCESSION_POLICY_INPUT_TUPLE, v); }
export function encodeEntropyPolicySuccessionPolicyInput(v: EntropyPolicySuccessionPolicyInput): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_POLICY_INPUT_TUPLE, normalizeEntropyPolicySuccessionPolicyInput(v)); }
export function decodeEntropyPolicySuccessionPolicyInput(v: Hex): EntropyPolicySuccessionPolicyInput { return normalizeEntropyPolicySuccessionPolicyInput(decoded(ENTROPY_POLICY_SUCCESSION_POLICY_INPUT_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionPolicyRecord(v: EntropyPolicySuccessionPolicyRecord): EntropyPolicySuccessionPolicyRecord { return normalize(ENTROPY_POLICY_SUCCESSION_POLICY_RECORD_TUPLE, v); }
export function encodeEntropyPolicySuccessionPolicyRecord(v: EntropyPolicySuccessionPolicyRecord): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_POLICY_RECORD_TUPLE, normalizeEntropyPolicySuccessionPolicyRecord(v)); }
export function decodeEntropyPolicySuccessionPolicyRecord(v: Hex): EntropyPolicySuccessionPolicyRecord { return normalizeEntropyPolicySuccessionPolicyRecord(decoded(ENTROPY_POLICY_SUCCESSION_POLICY_RECORD_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionCollectionRecovery(v: EntropyPolicySuccessionCollectionRecovery): EntropyPolicySuccessionCollectionRecovery { return normalize(ENTROPY_POLICY_SUCCESSION_COLLECTION_RECOVERY_TUPLE, v); }
export function encodeEntropyPolicySuccessionCollectionRecovery(v: EntropyPolicySuccessionCollectionRecovery): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_COLLECTION_RECOVERY_TUPLE, normalizeEntropyPolicySuccessionCollectionRecovery(v)); }
export function decodeEntropyPolicySuccessionCollectionRecovery(v: Hex): EntropyPolicySuccessionCollectionRecovery { return normalizeEntropyPolicySuccessionCollectionRecovery(decoded(ENTROPY_POLICY_SUCCESSION_COLLECTION_RECOVERY_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionPolicyExport(v: EntropyPolicySuccessionPolicyExport): EntropyPolicySuccessionPolicyExport { return normalize(ENTROPY_POLICY_SUCCESSION_POLICY_EXPORT_TUPLE, v); }
export function encodeEntropyPolicySuccessionPolicyExport(v: EntropyPolicySuccessionPolicyExport): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_POLICY_EXPORT_TUPLE, normalizeEntropyPolicySuccessionPolicyExport(v)); }
export function decodeEntropyPolicySuccessionPolicyExport(v: Hex): EntropyPolicySuccessionPolicyExport { return normalizeEntropyPolicySuccessionPolicyExport(decoded(ENTROPY_POLICY_SUCCESSION_POLICY_EXPORT_TUPLE, v, 1184)); }
export function normalizeEntropyPolicySuccessionRecoveryStep(v: EntropyPolicySuccessionRecoveryStep): EntropyPolicySuccessionRecoveryStep { return normalize(ENTROPY_POLICY_SUCCESSION_RECOVERY_STEP_TUPLE, v); }
export function encodeEntropyPolicySuccessionRecoveryStep(v: EntropyPolicySuccessionRecoveryStep): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_RECOVERY_STEP_TUPLE, normalizeEntropyPolicySuccessionRecoveryStep(v)); }
export function decodeEntropyPolicySuccessionRecoveryStep(v: Hex): EntropyPolicySuccessionRecoveryStep { return normalizeEntropyPolicySuccessionRecoveryStep(decoded(ENTROPY_POLICY_SUCCESSION_RECOVERY_STEP_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionRecoveryPolicy(v: EntropyPolicySuccessionRecoveryPolicy): EntropyPolicySuccessionRecoveryPolicy { return normalize(ENTROPY_POLICY_SUCCESSION_RECOVERY_POLICY_TUPLE, v); }
export function encodeEntropyPolicySuccessionRecoveryPolicy(v: EntropyPolicySuccessionRecoveryPolicy): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_RECOVERY_POLICY_TUPLE, normalizeEntropyPolicySuccessionRecoveryPolicy(v)); }
export function decodeEntropyPolicySuccessionRecoveryPolicy(v: Hex): EntropyPolicySuccessionRecoveryPolicy { return normalizeEntropyPolicySuccessionRecoveryPolicy(decoded(ENTROPY_POLICY_SUCCESSION_RECOVERY_POLICY_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionRecoveryExport(v: EntropyPolicySuccessionRecoveryExport): EntropyPolicySuccessionRecoveryExport { return normalize(ENTROPY_POLICY_SUCCESSION_RECOVERY_EXPORT_TUPLE, v); }
export function encodeEntropyPolicySuccessionRecoveryExport(v: EntropyPolicySuccessionRecoveryExport): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_RECOVERY_EXPORT_TUPLE, normalizeEntropyPolicySuccessionRecoveryExport(v)); }
export function decodeEntropyPolicySuccessionRecoveryExport(v: Hex): EntropyPolicySuccessionRecoveryExport { return normalizeEntropyPolicySuccessionRecoveryExport(decoded(ENTROPY_POLICY_SUCCESSION_RECOVERY_EXPORT_TUPLE, v, 5696)); }
export function normalizeEntropyPolicySuccessionImportReceipt(v: EntropyPolicySuccessionImportReceipt): EntropyPolicySuccessionImportReceipt { return normalize(ENTROPY_POLICY_SUCCESSION_IMPORT_RECEIPT_TUPLE, v); }
export function encodeEntropyPolicySuccessionImportReceipt(v: EntropyPolicySuccessionImportReceipt): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_IMPORT_RECEIPT_TUPLE, normalizeEntropyPolicySuccessionImportReceipt(v)); }
export function decodeEntropyPolicySuccessionImportReceipt(v: Hex): EntropyPolicySuccessionImportReceipt { return normalizeEntropyPolicySuccessionImportReceipt(decoded(ENTROPY_POLICY_SUCCESSION_IMPORT_RECEIPT_TUPLE, v, 544)); }
export function normalizeEntropyPolicySuccessionImportedPolicy(v: EntropyPolicySuccessionImportedPolicy): EntropyPolicySuccessionImportedPolicy { return normalize(ENTROPY_POLICY_SUCCESSION_IMPORTED_POLICY_TUPLE, v); }
export function encodeEntropyPolicySuccessionImportedPolicy(v: EntropyPolicySuccessionImportedPolicy): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_IMPORTED_POLICY_TUPLE, normalizeEntropyPolicySuccessionImportedPolicy(v)); }
export function decodeEntropyPolicySuccessionImportedPolicy(v: Hex): EntropyPolicySuccessionImportedPolicy { return normalizeEntropyPolicySuccessionImportedPolicy(decoded(ENTROPY_POLICY_SUCCESSION_IMPORTED_POLICY_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionAdmission(v: EntropyPolicySuccessionAdmission): EntropyPolicySuccessionAdmission { return normalize(ENTROPY_POLICY_SUCCESSION_ADMISSION_TUPLE, v); }
export function encodeEntropyPolicySuccessionAdmission(v: EntropyPolicySuccessionAdmission): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_ADMISSION_TUPLE, normalizeEntropyPolicySuccessionAdmission(v)); }
export function decodeEntropyPolicySuccessionAdmission(v: Hex): EntropyPolicySuccessionAdmission { return normalizeEntropyPolicySuccessionAdmission(decoded(ENTROPY_POLICY_SUCCESSION_ADMISSION_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionRequestPolicySnapshot(v: EntropyPolicySuccessionRequestPolicySnapshot): EntropyPolicySuccessionRequestPolicySnapshot { return normalize(ENTROPY_POLICY_SUCCESSION_REQUEST_POLICY_SNAPSHOT_TUPLE, v); }
export function encodeEntropyPolicySuccessionRequestPolicySnapshot(v: EntropyPolicySuccessionRequestPolicySnapshot): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_REQUEST_POLICY_SNAPSHOT_TUPLE, normalizeEntropyPolicySuccessionRequestPolicySnapshot(v)); }
export function decodeEntropyPolicySuccessionRequestPolicySnapshot(v: Hex): EntropyPolicySuccessionRequestPolicySnapshot { return normalizeEntropyPolicySuccessionRequestPolicySnapshot(decoded(ENTROPY_POLICY_SUCCESSION_REQUEST_POLICY_SNAPSHOT_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionRelayInput(v: EntropyPolicySuccessionRelayInput): EntropyPolicySuccessionRelayInput { return normalize(ENTROPY_POLICY_SUCCESSION_RELAY_INPUT_TUPLE, v); }
export function encodeEntropyPolicySuccessionRelayInput(v: EntropyPolicySuccessionRelayInput): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_RELAY_INPUT_TUPLE, normalizeEntropyPolicySuccessionRelayInput(v)); }
export function decodeEntropyPolicySuccessionRelayInput(v: Hex): EntropyPolicySuccessionRelayInput { return normalizeEntropyPolicySuccessionRelayInput(decoded(ENTROPY_POLICY_SUCCESSION_RELAY_INPUT_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionRelayResult(v: EntropyPolicySuccessionRelayResult): EntropyPolicySuccessionRelayResult { return normalize(ENTROPY_POLICY_SUCCESSION_RELAY_RESULT_TUPLE, v); }
export function encodeEntropyPolicySuccessionRelayResult(v: EntropyPolicySuccessionRelayResult): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_RELAY_RESULT_TUPLE, normalizeEntropyPolicySuccessionRelayResult(v)); }
export function decodeEntropyPolicySuccessionRelayResult(v: Hex): EntropyPolicySuccessionRelayResult { return normalizeEntropyPolicySuccessionRelayResult(decoded(ENTROPY_POLICY_SUCCESSION_RELAY_RESULT_TUPLE, v, 544)); }
export function normalizeEntropyPolicySuccessionRegistration(v: EntropyPolicySuccessionRegistration): EntropyPolicySuccessionRegistration { return normalize(ENTROPY_POLICY_SUCCESSION_REGISTRATION_TUPLE, v); }
export function encodeEntropyPolicySuccessionRegistration(v: EntropyPolicySuccessionRegistration): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_REGISTRATION_TUPLE, normalizeEntropyPolicySuccessionRegistration(v)); }
export function decodeEntropyPolicySuccessionRegistration(v: Hex): EntropyPolicySuccessionRegistration { return normalizeEntropyPolicySuccessionRegistration(decoded(ENTROPY_POLICY_SUCCESSION_REGISTRATION_TUPLE, v, 65536)); }
export function normalizeEntropyPolicySuccessionCatalogRow(v: EntropyPolicySuccessionCatalogRow): EntropyPolicySuccessionCatalogRow { return normalize(ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE, v); }
export function encodeEntropyPolicySuccessionCatalogRow(v: EntropyPolicySuccessionCatalogRow): Hex { return encoded(ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE, normalizeEntropyPolicySuccessionCatalogRow(v)); }
export function decodeEntropyPolicySuccessionCatalogRow(v: Hex): EntropyPolicySuccessionCatalogRow { return normalizeEntropyPolicySuccessionCatalogRow(decoded(ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE, v, 65536)); }

export const ENTROPY_POLICY_SUCCESSION_INITIAL_ID_DIGEST = id("6529STREAM_ENTROPY_POLICY_INVENTORY_IDS_INITIAL_V1") as Hex;
export function entropyPolicySuccessionInventoryAppend(previous: Hex, index: bigint, collectionId: bigint): Hex { return hash(["bytes32", "bytes32", "uint256", "uint256"], [id("6529STREAM_ENTROPY_POLICY_INVENTORY_IDS_APPEND_V1"), hex(previous, 32), uint(index, 256), uint(collectionId, 256)]); }
/** Inventory order is authoritative insertion order, not numerical collection order. */
export function entropyPolicySuccessionInventory(ids: readonly bigint[], serial: bigint): EntropyPolicySuccessionInventoryHeader { const rows = dense(ids, ENTROPY_POLICY_SUCCESSION_MAX_INVENTORY).map(v => uint(v, 256)), s = uint(serial, 64); if (s < BigInt(rows.length) || new Set(rows).size !== rows.length) throw Error("Invalid inventory count/serial or duplicate collection"); let digest = ENTROPY_POLICY_SUCCESSION_INITIAL_ID_DIGEST; rows.forEach((v, i) => { digest = entropyPolicySuccessionInventoryAppend(digest, BigInt(i), v); }); return Object.freeze({ count: BigInt(rows.length), serial: s, idDigest: digest }); }
export function entropyPolicySuccessionImportHash(configuration: EntropyPolicySuccessionConfiguration, receipt: EntropyPolicySuccessionImportReceipt): Hex { const c = normalizeEntropyPolicySuccessionConfiguration(configuration), r = normalizeEntropyPolicySuccessionImportReceipt(receipt); return hash(["bytes32", "uint256", "address", "bytes32", "address", "uint64", "address", "bytes32", "uint64", "uint256", "uint64", "bytes32", "bytes32"], [id("6529STREAM_ENTROPY_POLICY_IMPORT_V1"), c.chainId, c.candidate, c.candidateCodeHash, c.core, r.nonce, r.predecessor, r.predecessorCodeHash, r.pointerRevision, r.count, r.serial, r.idDigest, r.manifestHash]); }
export function entropyPolicySuccessionInitialExportDigest(importHash: Hex): Hex { return hash(["bytes32", "bytes32"], [id("6529STREAM_ENTROPY_POLICY_IMPORT_EXPORTS_V1"), hex(importHash, 32)]); }
export function entropyPolicySuccessionAppendExportDigest(previous: Hex, index: bigint, collectionId: bigint, exportHash: Hex, recoveryExportHash: Hex): Hex { return hash(["bytes32", "bytes32", "uint256", "uint256", "bytes32", "bytes32"], [id("6529STREAM_ENTROPY_POLICY_IMPORT_EXPORT_APPEND_V1"), hex(previous, 32), uint(index, 256), uint(collectionId, 256), hex(exportHash, 32), hex(recoveryExportHash, 32)]); }
export function entropyPolicySuccessionExportHash(v: EntropyPolicySuccessionPolicyExport): Hex { return keccak256(encodeEntropyPolicySuccessionPolicyExport(v)) as Hex; }
export function entropyPolicySuccessionRecoveryExportHash(v: EntropyPolicySuccessionRecoveryExport): Hex { return keccak256(encodeEntropyPolicySuccessionRecoveryExport(v)) as Hex; }
export function entropyPolicySuccessionLegacySaltHash(chainId: bigint, core: Address, value: EntropyPolicySuccessionPolicyExport): Hex { const p = normalizeEntropyPolicySuccessionPolicyExport(value); return !p.policy.reveal.declared ? zeroHash : hash(["bytes32", "uint256", "address", "address", "uint256", "bytes32"], [id("6529STREAM_ENTROPY_COLLECTION_SALT_V1"), uint(chainId, 256), p.policyOrigin, address(core), p.collectionId, p.policy.collectionSalt]); }
export function entropyPolicySuccessionPolicyHash(chainId: bigint, core: Address, value: EntropyPolicySuccessionPolicyExport): Hex {
  const p = normalizeEntropyPolicySuccessionPolicyExport(value), chain = uint(chainId, 256), host = address(core), i = p.policy, r = p.record, recovery = p.recovery;
  if (p.profile === 1n) return hash(["bytes32", "uint256", "address", "address", "uint256", "uint8", "uint8", "uint8", "address", "bytes32", "bytes32", "uint32", "bytes32", "bool", "uint64", "bool", "uint8", "bytes32", "uint64", "bytes32", "bytes32", "uint16"], [id("6529STREAM_ENTROPY_COLLECTION_POLICY_V2"), chain, p.policyOrigin, host, p.collectionId, r.mode, r.securityClass, r.renderRequirement, i.provider, p.providerCodeHash, p.providerConfigHash, r.providerEpoch, i.collectionSalt, i.publicRequests, i.timeoutBlocks, i.reveal.declared, i.reveal.requestMode, i.reveal.revealOwnerRole, i.reveal.requestSLOBlocks, recovery.policyId, recovery.policyHash, recovery.maxFreshRecoveryAttempts]);
  if (!i.reveal.declared) return zeroHash;
  const provider = hash(["bytes32", "address", "bytes32", "uint32", "bytes32", "bytes32", "bool", "uint64"], [id("6529STREAM_ENTROPY_SINGLE_PROVIDER_POLICY_V1"), i.provider, p.providerCodeHash, r.providerEpoch, p.providerConfigHash, entropyPolicySuccessionLegacySaltHash(chain, host, p), i.publicRequests, i.timeoutBlocks]);
  const reveal = hash(["bytes32", "uint8", "bytes32", "uint64"], [id("6529STREAM_ENTROPY_DECLARED_REVEAL_POLICY_V1"), i.reveal.requestMode, i.reveal.revealOwnerRole, i.reveal.requestSLOBlocks]);
  if (recovery.maxFreshRecoveryAttempts !== 0n) return hash(["bytes32", "uint256", "address", "address", "uint256", "bytes32", "bytes32", "bytes32", "bytes32", "uint16"], [id("6529STREAM_ENTROPY_FINALITY_FRESH_POLICY_V1"), chain, p.policyOrigin, host, p.collectionId, provider, reveal, recovery.policyId, recovery.policyHash, recovery.maxFreshRecoveryAttempts]);
  return hash(["bytes32", "uint256", "address", "address", "uint256", "bytes32", "bytes32", "bytes32"], [id("6529STREAM_ENTROPY_FINALITY_POLICY_V1"), chain, p.policyOrigin, host, p.collectionId, id(r.providerEpoch === 1n ? "6529STREAM_ENTROPY_EPOCH1_NO_FRESH_RECOVERY_V1" : "6529STREAM_ENTROPY_PREMINT_EPOCHS_NO_FRESH_RECOVERY_V1"), provider, reveal]);
}
export function entropyPolicySuccessionContentStateHash(policyHash: Hex, frozen: boolean): Hex { if (typeof frozen !== "boolean") throw Error("Expected frozen boolean"); return hash(["bytes32", "bytes32", "bool"], [id("6529STREAM_ENTROPY_CONFIGURATION_V1"), hex(policyHash, 32), frozen]); }
export function entropyPolicySuccessionRecoveryHash(chainId: bigint, core: Address, value: EntropyPolicySuccessionRecoveryExport): Hex {
  const r = normalizeEntropyPolicySuccessionRecoveryExport(value), chain = uint(chainId, 256), host = address(core), p = r.policy;
  const steps = hash(["bytes32", `${ENTROPY_POLICY_SUCCESSION_RECOVERY_STEP_TUPLE}[]`], [id("6529STREAM_ENTROPY_FRESH_RECOVERY_STEPS_V1"), p.steps]);
  const original = hash(["bytes32", "uint256", "address", "bytes32", "uint16", "bytes32", "bytes32", "bytes32", "bytes32"], [id("6529STREAM_ENTROPY_FRESH_RECOVERY_POLICY_V1"), chain, r.policyOrigin, r.policyId, p.maxFreshRecoveryAttempts, p.incidentDeclarerRole, p.reasonSchemaHash, p.policyManifestHash, steps]);
  return r.successor === ZeroAddress ? original : hash(["bytes32", "uint256", "address", "address", "bytes32", "bytes32", "address", "bytes32"], [id("6529STREAM_ENTROPY_FRESH_RECOVERY_POLICY_V2"), chain, r.policyOrigin, host, r.policyId, original, r.successor, r.successorCodeHash]);
}
function bindingShape(p: EntropyPolicySuccessionPolicyExport): void { const r = p.recovery; if (p.policy.recoveryPolicyId !== r.policyId || p.policy.maxFreshRecoveryAttempts !== r.maxFreshRecoveryAttempts || (r.revision === 0n) !== (r.lastActionId === ZeroHash)) throw Error("Recovery binding differs from policy input"); if (r.maxFreshRecoveryAttempts === 0n) { if (r.policyId !== ZeroHash || r.policyHash !== ZeroHash) throw Error("Removed binding must retain zero policy identity"); } else if (r.policyId === ZeroHash || r.policyHash === ZeroHash || r.revision === 0n || r.maxFreshRecoveryAttempts > 32n) throw Error("Invalid bound recovery shape"); }
function emptyReveal(r: policy.EntropyCollectionPolicyReveal): void { if (r.declared || r.requestMode !== 0n || r.revealOwnerRole !== ZeroHash || r.requestSLOBlocks !== 0n || r.revealFeePerTokenWei !== 0n) throw Error("Expected undeclared empty reveal"); }
function declaredReveal(r: policy.EntropyCollectionPolicyReveal): void { if (!r.declared || r.requestMode > 1n || r.revealOwnerRole !== id("ROLE_ENTROPY_REVEAL_OWNER") || r.requestSLOBlocks === 0n) throw Error("Invalid original declared reveal"); }
function providerShape(p: EntropyPolicySuccessionPolicyExport): void { if (p.policy.provider === ZeroAddress || p.providerCodeHash === ZeroHash || p.providerConfigHash === ZeroHash || p.record.providerEpoch === 0n) throw Error("Invalid original provider binding"); }
/** Original pure import validator. Runtime pins, provider lifecycle and authority are separately observed. */
export function validateEntropyPolicySuccessionPolicy(chainId: bigint, core: Address, value: EntropyPolicySuccessionPolicyExport): EntropyPolicySuccessionPolicyExport {
  const p = normalizeEntropyPolicySuccessionPolicyExport(value), r = p.record, i = p.policy; address(core, true); address(p.policyOrigin, true); nz(p.policyOriginCodeHash);
  if (!r.configured || r.mode !== i.mode || r.securityClass !== i.securityClass || r.renderRequirement !== i.renderRequirement) throw Error("Policy and record disagree"); bindingShape(p);
  if (p.profile === 0n) { if (r.explicitPolicy || r.revision !== 0n || r.lastActionId !== ZeroHash || r.artistConsentRecord !== ZeroHash || r.mode !== 2n || r.securityClass !== 0n || r.renderRequirement !== 1n) throw Error("Invalid legacy profile"); providerShape(p); if (!i.timeoutBlocks) throw Error("Legacy requires timeout"); if (i.reveal.declared) declaredReveal(i.reveal); else emptyReveal(i.reveal); }
  else { if (!r.explicitPolicy || !r.revision || r.lastActionId === ZeroHash || r.artistConsentRecord === ZeroHash) throw Error("Explicit profile lacks original receipts");
    if (i.mode === 0n) { if (i.renderRequirement !== 0n || i.provider !== ZeroAddress || p.providerCodeHash !== ZeroHash || p.providerConfigHash !== ZeroHash || i.collectionSalt !== ZeroHash || i.publicRequests || i.timeoutBlocks !== 0n || i.maxFreshRecoveryAttempts !== 0n) throw Error("Invalid disabled import"); emptyReveal(i.reveal); }
    else if (i.mode === 1n) { providerShape(p); if (i.securityClass !== 1n || i.timeoutBlocks !== 0n || i.maxFreshRecoveryAttempts !== 0n) throw Error("Invalid instant import"); emptyReveal(i.reveal); }
    else { providerShape(p); if (!i.timeoutBlocks) throw Error("Async requires timeout"); declaredReveal(i.reveal); }
  }
  if (r.policyHash !== entropyPolicySuccessionPolicyHash(chainId, core, p) || r.contentStateHash !== entropyPolicySuccessionContentStateHash(r.policyHash, r.frozen)) throw Error("Original policy/content commitment mismatch"); return p;
}
export function validateEntropyPolicySuccessionRecovery(chainId: bigint, core: Address, value: EntropyPolicySuccessionRecoveryExport): EntropyPolicySuccessionRecoveryExport {
  const r = normalizeEntropyPolicySuccessionRecoveryExport(value), p = r.policy; address(core, true); address(r.policyOrigin, true); nz(r.policyOriginCodeHash); nz(r.policyId); nz(r.policyHash); nz(r.lastActionId);
  if (!r.revision || !p.exists || !p.frozen || !p.maxFreshRecoveryAttempts || BigInt(p.steps.length) < p.maxFreshRecoveryAttempts || p.incidentDeclarerRole !== id("ROLE_ENTROPY_INCIDENT_DECLARER") || p.reasonSchemaHash === ZeroHash || p.policyManifestHash === ZeroHash) throw Error("Invalid frozen recovery definition");
  for (const step of p.steps) { address(step.provider, true); nz(step.providerConfigHash); if (!step.providerEpoch || !step.notBeforeBlocks) throw Error("Invalid recovery step"); }
  if (r.successor === ZeroAddress ? r.successorCodeHash !== ZeroHash : r.successor === r.policyOrigin || r.successorCodeHash === ZeroHash) throw Error("Invalid original recovery replacement");
  if (r.policyHash !== entropyPolicySuccessionRecoveryHash(chainId, core, r)) throw Error("Original recovery hash mismatch"); return r;
}
export function verifyEntropyPolicySuccessionRecoveryBinding(policyExport: EntropyPolicySuccessionPolicyExport, recoveryExport: EntropyPolicySuccessionRecoveryExport): void { const p = normalizeEntropyPolicySuccessionPolicyExport(policyExport), r = normalizeEntropyPolicySuccessionRecoveryExport(recoveryExport); bindingShape(p); const attempts = p.recovery.maxFreshRecoveryAttempts; if (!attempts) return; if (r.policyId !== p.recovery.policyId || r.policyHash !== p.recovery.policyHash || r.policyHash === ZeroHash || !r.policy.exists || !r.policy.frozen || attempts > r.policy.maxFreshRecoveryAttempts || attempts > BigInt(r.policy.steps.length)) throw Error("Recovery definition binding mismatch"); let epoch = p.record.providerEpoch; for (let i = 0; i < Number(attempts); i++) { const next = r.policy.steps[i]!.providerEpoch; if (next <= epoch) throw Error("Consumed recovery epochs must strictly increase"); epoch = next; } }
export function entropyPolicySuccessionRouteRequired(value: EntropyPolicySuccessionPolicyExport): boolean { const p = normalizeEntropyPolicySuccessionPolicyExport(value).policy; return p.mode !== 0n && !(p.mode === 1n && p.renderRequirement === 0n); }
/** Original relay identities only; this module does not compose relay request/delivery transactions. */
export function entropyPolicySuccessionRelayContext(core: Address, value: EntropyPolicySuccessionRelayInput): Hex { const r = normalizeEntropyPolicySuccessionRelayInput(value); return coder.encode(["uint16", "address", "uint256", "uint256", "bytes32", "uint32", "bytes32", "uint16", "bytes32"], [r.scopeId === ZeroHash ? 1n : 2n, address(core), r.collectionId, r.tokenId, r.scopeId, r.policy.providerEpoch, r.policy.providerConfigHash, r.policy.requestAttempt, r.policy.inputsHash]) as Hex; }
export function entropyPolicySuccessionRequestKey(chainId: bigint, core: Address, successor: Address, value: EntropyPolicySuccessionRelayInput): Hex { const r = normalizeEntropyPolicySuccessionRelayInput(value), common = [uint(chainId, 256), address(successor), address(core), r.collectionId]; return r.scopeId === ZeroHash ? hash(["bytes32", "uint256", "address", "address", "uint256", "uint256", "address", "uint32", "bytes32", "uint16"], [id("6529STREAM_ENTROPY_REQUEST_V1"), ...common, r.tokenId, r.policy.provider, r.policy.providerEpoch, r.policy.providerConfigHash, r.policy.requestAttempt]) : hash(["bytes32", "uint256", "address", "address", "uint256", "bytes32", "address", "uint32", "bytes32", "bytes32", "uint16"], [id("6529STREAM_ENTROPY_SCOPE_REQUEST_V1"), ...common, r.scopeId, r.policy.provider, r.policy.providerEpoch, r.policy.providerConfigHash, r.policy.inputsHash, r.policy.requestAttempt]); }
export function entropyPolicySuccessionRelayId(chainId: bigint, core: Address, origin: Address, successor: EntropyPolicySuccessionRuntime, value: EntropyPolicySuccessionRelayInput): Hex { const r = normalizeEntropyPolicySuccessionRelayInput(value), s = normalizeEntropyPolicySuccessionRuntime(successor); return hash(["bytes32", "uint256", "address", "address", "bytes32", "bytes32", "uint256", "bytes32", "bytes32"], [id("6529STREAM_ENTROPY_RELAY_V1"), uint(chainId, 256), address(origin), s.target, s.codeHash, r.importHash, r.collectionId, r.successorRequestKey, keccak256(entropyPolicySuccessionRelayContext(core, r))]); }
export function entropyPolicySuccessionRelayWitnessHash(chainId: bigint, core: Address, origin: EntropyPolicySuccessionRuntime, successor: EntropyPolicySuccessionRuntime, value: EntropyPolicySuccessionRelayInput): Hex { const r = normalizeEntropyPolicySuccessionRelayInput(value), o = normalizeEntropyPolicySuccessionRuntime(origin), s = normalizeEntropyPolicySuccessionRuntime(successor); return hash(["bytes32", "uint256", "address", "address", "bytes32", "address", "bytes32", ENTROPY_POLICY_SUCCESSION_RELAY_INPUT_TUPLE], [id("6529STREAM_ENTROPY_RELAY_WITNESS_V1"), uint(chainId, 256), address(core), s.target, s.codeHash, o.target, o.codeHash, r]); }

export const CURRENT_ENTROPY_POLICY_SUCCESSION_ABI = Object.freeze([
  `function extendGovernanceActionPolicy(uint64 expectedRevision,bytes32 expectedOldCatalogHash,bytes32 expectedNewCatalogHash,${ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE}[] additions)`,
  "function activateEntropyPolicyImport()",
  "function beginEntropyPolicyImport(address predecessor, bytes32 manifestHash)",
  "function confirmEntropyRelayRoute(uint256 collectionId)",
  "function entropyPolicyCollectionAt(uint256 index) view returns (uint256 collectionId)",
  "function entropyPolicyImport() view returns ((uint8 state, uint64 nonce, address predecessor, bytes32 predecessorCodeHash, uint64 pointerRevision, uint256 count, uint64 serial, bytes32 idDigest, bytes32 manifestHash, uint256 nextIndex, bytes32 exportDigest, uint256 requiredRelayCount, uint256 confirmedRelayCount, bytes32 importHash, bytes32 beginActionId, bytes32 sealActionId, bytes32 activationActionId))",
  "function entropyPolicyImportActivationTransition() view returns (bytes32 scope, bytes32 oldHash, bytes32 newHash)",
  "function entropyPolicyImportReady(address predecessor, bytes32 predecessorCodeHash, uint64 pointerRevision, uint256 count, uint64 serial, bytes32 idDigest) view returns (bool)",
  "function entropyPolicyImportSealTransition() view returns (bytes32 scope, bytes32 oldHash, bytes32 newHash)",
  "function entropyPolicyImportTransition(address predecessor, bytes32 manifestHash) view returns (bytes32 scope, bytes32 oldHash, bytes32 newHash)",
  "function entropyPolicyInventory() view returns (uint256 count, uint64 serial, bytes32 idDigest)",
  "function exportEntropyPolicy(uint256 collectionId) view returns ((uint256 collectionId, uint8 profile, address policyOrigin, bytes32 policyOriginCodeHash, (bool configured, bool explicitPolicy, bool frozen, uint8 mode, uint8 securityClass, uint8 renderRequirement, uint64 revision, uint32 providerEpoch, bytes32 policyHash, bytes32 contentStateHash, bytes32 lastActionId, bytes32 artistConsentRecord) record, (uint8 mode, uint8 securityClass, uint8 renderRequirement, address provider, bytes32 collectionSalt, bool publicRequests, uint64 timeoutBlocks, (bool declared, uint8 requestMode, bytes32 revealOwnerRole, uint64 requestSLOBlocks, uint256 revealFeePerTokenWei) reveal, uint16 maxFreshRecoveryAttempts, bytes32 recoveryPolicyId) policy, bytes32 providerCodeHash, bytes32 providerConfigHash, (bytes32 policyId, bytes32 policyHash, uint16 maxFreshRecoveryAttempts, uint64 revision, bytes32 lastActionId) recovery))",
  "function exportEntropyRecovery(bytes32 policyId) view returns ((bytes32 policyId, (bool exists, bool frozen, uint16 maxFreshRecoveryAttempts, bytes32 incidentDeclarerRole, bytes32 reasonSchemaHash, bytes32 policyManifestHash, (address provider, uint32 providerEpoch, bytes32 providerConfigHash, uint64 notBeforeBlocks, bool acceptLateOriginalFulfillment)[] steps) policy, bytes32 policyHash, uint64 revision, bytes32 lastActionId, address policyOrigin, bytes32 policyOriginCodeHash, address successor, bytes32 successorCodeHash))",
  "function importedEntropyPolicy(uint256 collectionId) view returns (bytes32 importHash, bytes32 exportHash, address policyOrigin, bytes32 policyOriginCodeHash, bytes32 policyHash)",
  "function importNextEntropyPolicy(uint256 expectedIndex)",
  "function sealEntropyPolicyImport()",
  "function admitEntropyRelay(uint256 collectionId, address successor, bytes32 importHash)",
  "function entropyRelayAdmission(uint256 collectionId, address successor) view returns (bytes32 successorCodeHash, bytes32 importHash, bytes32 policyHash)",
  "function entropyRelayAdmissionTransition(uint256 collectionId, address successor, bytes32 importHash) view returns (bytes32 scope, bytes32 oldHash, bytes32 newHash)",
  "function updateSatellitePointer(bytes32 pointerType, address newTarget)",
  "function publishStreamSystemManifest(address payloadPointer, (bytes32 manifestHash, string manifestURI, bytes32 eventCatalogHash, bytes32 compatibilityMatrixHash, bytes32 numericIdCatalogHash, bytes32 schemaCatalogHash, bytes32 canonicalizationCatalogHash, bytes32 specBundleHash, bytes32 reconstructionClientHash) update)",
]);
const abi = new Interface(CURRENT_ENTROPY_POLICY_SUCCESSION_ABI), governanceAbi = new Interface(CURRENT_ARTIST_RECOVERY_GOVERNANCE_ABI);
export const ENTROPY_POLICY_SUCCESSION_CONTINUITY_INTERFACE_ID = "0x93452dd9" as Hex;
export const ENTROPY_POLICY_SUCCESSION_ORIGIN_RELAY_INTERFACE_ID = "0x5667ccb2" as Hex;
export const ENTROPY_POLICY_SUCCESSION_COORDINATOR_INTERFACE_ID = "0x979b977f" as Hex;

export function entropyPolicySuccessionImportScope(configuration: EntropyPolicySuccessionConfiguration, selector: Hex): Hex { const c = normalizeEntropyPolicySuccessionConfiguration(configuration); return hash(["bytes32", "uint256", "address", "address", "bytes4"], [id("6529STREAM_ENTROPY_POLICY_IMPORT_SCOPE_V1"), c.chainId, c.candidate, c.core, hex(selector, 4)]); }
export function entropyPolicySuccessionImportStateHash(scope: Hex, receipt: EntropyPolicySuccessionImportReceipt): Hex { const r = normalizeEntropyPolicySuccessionImportReceipt(receipt); return hash(["bytes32", "bytes32", "uint8", "uint64", "bytes32", "uint256", "bytes32", "uint256", "uint256"], [id("6529STREAM_ENTROPY_POLICY_IMPORT_STATE_V1"), hex(scope, 32), r.state, r.nonce, r.importHash, r.nextIndex, r.exportDigest, r.requiredRelayCount, r.confirmedRelayCount]); }
export function entropyPolicySuccessionRelayAdmissionScope(configuration: EntropyPolicySuccessionConfiguration, origin: Address, collectionId: bigint): Hex { const c = normalizeEntropyPolicySuccessionConfiguration(configuration); return hash(["bytes32", "uint256", "address", "address", "uint256", "address", "bytes4"], [id("6529STREAM_ENTROPY_RELAY_ADMISSION_SCOPE_V1"), c.chainId, address(origin), c.core, uint(collectionId, 256), c.candidate, abi.getFunction("admitEntropyRelay")!.selector]); }
export function entropyPolicySuccessionRelayAdmissionStateHash(scope: Hex, admission: EntropyPolicySuccessionAdmission, exportHash: Hex): Hex { const a = normalizeEntropyPolicySuccessionAdmission(admission); return hash(["bytes32", "bytes32", "bytes32", "bytes32", "bytes32", "bytes32"], [id("6529STREAM_ENTROPY_RELAY_ADMISSION_STATE_V1"), hex(scope, 32), a.successorCodeHash, a.importHash, a.policyHash, hex(exportHash, 32)]); }
function transition(scope: Hex, oldHash: Hex, newHash: Hex): EntropyPolicySuccessionTransition { return Object.freeze({ scope, oldHash, newHash }); }
function importPhase(c: EntropyPolicySuccessionConfiguration, selector: string, r: EntropyPolicySuccessionImportReceipt, next: 2n | 3n): EntropyPolicySuccessionTransition { const scope = entropyPolicySuccessionImportScope(c, abi.getFunction(selector)!.selector as Hex); return transition(scope, entropyPolicySuccessionImportStateHash(scope, r), entropyPolicySuccessionImportStateHash(scope, { ...r, state: next })); }
function headerValid(input: EntropyPolicySuccessionInventoryHeader): EntropyPolicySuccessionInventoryHeader { const h = normalizeEntropyPolicySuccessionInventoryHeader(input); if (h.serial < h.count || h.idDigest === ZeroHash || h.count === 0n && h.idDigest !== ENTROPY_POLICY_SUCCESSION_INITIAL_ID_DIGEST) throw Error("Invalid inventory header"); return h; }
function receiptSource(c: EntropyPolicySuccessionConfiguration, receipt: EntropyPolicySuccessionImportReceipt, source: EntropyPolicySuccessionInventoryHeader): EntropyPolicySuccessionImportReceipt { const r = normalizeEntropyPolicySuccessionImportReceipt(receipt), h = headerValid(source); if (r.nonce !== 1n || r.predecessor !== c.predecessor || r.predecessorCodeHash !== c.predecessorCodeHash || r.pointerRevision === (1n << 64n) - 1n || r.manifestHash === ZeroHash || r.importHash !== entropyPolicySuccessionImportHash(c, r) || r.count !== h.count || r.serial !== h.serial || r.idDigest !== h.idDigest) throw Error("Import receipt differs from frozen source"); return r; }
function complete(r: EntropyPolicySuccessionImportReceipt, candidate: EntropyPolicySuccessionInventoryHeader): void { const h = headerValid(candidate); if (r.nextIndex !== r.count || r.requiredRelayCount !== r.confirmedRelayCount || h.count !== r.count || h.idDigest !== r.idDigest) throw Error("Incomplete import or relay confirmations"); }
/** Original local readiness predicate; ACTIVE remains a receipt, never a second SEALED readiness state. */
export function entropyPolicySuccessionImportReady(receipt: EntropyPolicySuccessionImportReceipt, predecessor: Address, predecessorCodeHash: Hex, pointerRevision: bigint, inventory: EntropyPolicySuccessionInventoryHeader): boolean { const r = normalizeEntropyPolicySuccessionImportReceipt(receipt), h = normalizeEntropyPolicySuccessionInventoryHeader(inventory); return r.state === 2n && r.importHash !== ZeroHash && r.predecessor === address(predecessor) && r.predecessorCodeHash === hex(predecessorCodeHash, 32) && r.pointerRevision === uint(pointerRevision, 64) && r.count === h.count && r.serial === h.serial && r.idDigest === h.idDigest && r.nextIndex === r.count && r.requiredRelayCount === r.confirmedRelayCount; }
export function entropyPolicySuccessionBeginReceipt(configuration: EntropyPolicySuccessionConfiguration, inventory: EntropyPolicySuccessionInventoryHeader, pointerRevision: bigint, manifestHash: Hex): EntropyPolicySuccessionImportReceipt { const c = normalizeEntropyPolicySuccessionConfiguration(configuration), h = headerValid(inventory), rev = uint(pointerRevision, 64); if (rev === (1n << 64n) - 1n) throw Error("Pointer revision exhausted"); let r: EntropyPolicySuccessionImportReceipt = { state: 1n, nonce: 1n, predecessor: c.predecessor, predecessorCodeHash: c.predecessorCodeHash, pointerRevision: rev, count: h.count, serial: h.serial, idDigest: h.idDigest, manifestHash: nz(hex(manifestHash, 32)), nextIndex: 0n, exportDigest: zeroHash, requiredRelayCount: 0n, confirmedRelayCount: 0n, importHash: zeroHash, beginActionId: zeroHash, sealActionId: zeroHash, activationActionId: zeroHash }; r = { ...r, importHash: entropyPolicySuccessionImportHash(c, r) }; return Object.freeze({ ...r, exportDigest: entropyPolicySuccessionInitialExportDigest(r.importHash) }); }
export type EntropyPolicySuccessionRequest =
  | { readonly kind: "begin"; readonly receipt: EntropyPolicySuccessionImportReceipt; readonly predecessorInventory: EntropyPolicySuccessionInventoryHeader; readonly candidateInventory: EntropyPolicySuccessionInventoryHeader; readonly pointer: EntropyPolicySuccessionPointer; readonly manifestHash: Hex }
  | { readonly kind: "copy"; readonly expectedIndex: bigint }
  | { readonly kind: "confirm-route"; readonly collectionId: bigint }
  | { readonly kind: "seal"; readonly receipt: EntropyPolicySuccessionImportReceipt; readonly predecessorInventory: EntropyPolicySuccessionInventoryHeader; readonly candidateInventory: EntropyPolicySuccessionInventoryHeader }
  | { readonly kind: "admit-route"; readonly origin: EntropyPolicySuccessionRuntime; readonly receipt: EntropyPolicySuccessionImportReceipt; readonly policy: EntropyPolicySuccessionPolicyExport; readonly recovery: EntropyPolicySuccessionRecoveryExport | null; readonly importedPolicy: EntropyPolicySuccessionImportedPolicy; readonly currentAdmission: EntropyPolicySuccessionAdmission; readonly predecessorAdmission: EntropyPolicySuccessionAdmission | null }
  | { readonly kind: "catalog"; readonly inventory: EntropyPolicySuccessionCatalogInventory; readonly baseHistory: EntropyPolicySuccessionCatalogHistory; readonly origins: readonly EntropyPolicySuccessionRuntime[]; readonly deploymentHash: Hex; readonly completedRows: bigint; readonly catalogState: EntropyPolicySuccessionCatalogState; readonly manifestState: EntropyPolicySuccessionManifestState; readonly payload: Address; readonly update: EntropyPolicySuccessionManifestUpdate }
  | { readonly kind: "cutover"; readonly receipt: EntropyPolicySuccessionImportReceipt; readonly predecessorInventory: EntropyPolicySuccessionInventoryHeader; readonly candidateInventory: EntropyPolicySuccessionInventoryHeader; readonly pointer: EntropyPolicySuccessionPointer; readonly registration: EntropyPolicySuccessionRegistration; readonly registrationStatus: bigint; readonly manifestState: EntropyPolicySuccessionManifestState; readonly payload: Address; readonly update: EntropyPolicySuccessionManifestUpdate };
export interface EntropyPolicySuccessionPlan { readonly configuration: EntropyPolicySuccessionConfiguration; readonly request: EntropyPolicySuccessionRequest; readonly actionClass: 1n | 3n | null; readonly calls: readonly EntropyPolicySuccessionGovernanceCall[]; readonly callDatas: readonly Hex[]; readonly targetCalls: readonly UnsignedCall[]; readonly factsVerified: false }
function targetCall(target: Address, method: string, args: readonly unknown[]): UnsignedCall { return Object.freeze({ to: target, value: 0n, data: abi.encodeFunctionData(method, args) as Hex }); }
function governed(call: UnsignedCall, t: EntropyPolicySuccessionTransition): EntropyPolicySuccessionGovernanceCall { return Object.freeze({ target: call.to, value: 0n, selector: call.data.slice(0, 10) as Hex, callDataHash: keccak256(call.data) as Hex, scopeHash: t.scope, oldValueHash: t.oldHash, newValueHash: t.newHash }); }
export function entropyPolicySuccessionPointerTransition(configuration: EntropyPolicySuccessionConfiguration, previous: EntropyPolicySuccessionPointer, next: EntropyPolicySuccessionPointer): EntropyPolicySuccessionTransition { const c = normalizeEntropyPolicySuccessionConfiguration(configuration), p = normalizeEntropyPolicySuccessionPointer(previous), n = normalizeEntropyPolicySuccessionPointer(next), scope = hash(["bytes32", "uint256", "address", "bytes32"], ["0xf4a381d3d4c51db07c19830799ea01c544326118ea1db1fb59d54af5f637bdbb", c.chainId, c.core, ENTROPY_POLICY_SUCCESSION_KIND]); const state = (v: EntropyPolicySuccessionPointer) => hash(["bytes32", "bytes32", ...ParamType.from(ENTROPY_POLICY_SUCCESSION_POINTER_TUPLE).components!], ["0x1fdde0a7122d0fc7c237e721e372e43082581dcc6bd2babca4e09bb1e6b3d043", scope, ...Object.values(v)]); return transition(scope, state(p), state(n)); }
export function entropyPolicySuccessionManifestTransition(configuration: EntropyPolicySuccessionConfiguration, before: EntropyPolicySuccessionManifestState, payload: Address, update: EntropyPolicySuccessionManifestUpdate): EntropyPolicySuccessionTransition {
  return manifestTransition(configuration, before, payload, update, true);
}
function manifestTransition(configuration: EntropyPolicySuccessionConfiguration, before: EntropyPolicySuccessionManifestState, payload: Address, update: EntropyPolicySuccessionManifestUpdate, cutover: boolean): EntropyPolicySuccessionTransition {
  const c = normalizeEntropyPolicySuccessionConfiguration(configuration), b = normalizeEntropyPolicySuccessionManifestState(before), u = normalizeEntropyPolicySuccessionManifestUpdate(update), target = address(payload, true);
  if (b.modules.moduleRegistry !== c.moduleRegistry || cutover && b.modules.entropyCoordinator !== c.predecessor) throw Error("Current manifest dependency mismatch");
  const scope = hash(["bytes32", "uint256", "address"], ["0xf73b4d7b4d260fce0823707f836fdf29a1767a2a2a9cfbce14ec8c5e49e47841", c.chainId, c.manifest]);
  const moduleKeys = Object.keys(b.modules), discoveryKeys = Object.keys(b.discovery);
  const state = (manifestHash: Hex, uri: string, pointer: Address, modules: fallback.MintFallbackManifestModules, discovery: fallback.MintFallbackManifestDiscovery, revision: bigint) => hash(["bytes32", "bytes32", "bytes32", "bytes32", "address", "bytes32", "bytes32", "uint64"], ["0x3764ccb415d0aac07f1bddb8d4841ad6d4c2f9b2fe7ce7d221c586bc056aaf60", scope, manifestHash, keccak256(toUtf8Bytes(uri)), pointer, hash(moduleKeys.map(() => "address"), moduleKeys.map(k => Reflect.get(modules, k))), hash(discoveryKeys.map(() => "bytes32"), discoveryKeys.map(k => Reflect.get(discovery, k))), revision]);
  return transition(scope, state(b.manifestHash, b.manifestURI, b.payloadRoot, b.modules, b.discovery, b.revision), state(u.manifestHash, u.manifestURI, target, cutover ? { ...b.modules, entropyCoordinator: c.candidate } : b.modules, u, next64(b.revision)));
}
/** Canonical finite planner. Supplied observations do not prove unused candidate state, code or authority. */
export function prepareEntropyPolicySuccessionPlan(configuration: EntropyPolicySuccessionConfiguration, input: EntropyPolicySuccessionRequest): EntropyPolicySuccessionPlan {
  const c = normalizeEntropyPolicySuccessionConfiguration(configuration); let request: EntropyPolicySuccessionRequest, actionClass: 1n | 3n | null, targets: UnsignedCall[], transitions: EntropyPolicySuccessionTransition[] = [];
  switch (input.kind) {
    case "begin": {
      exact(input, ["kind", "receipt", "predecessorInventory", "candidateInventory", "pointer", "manifestHash"]);
      const r = normalizeEntropyPolicySuccessionImportReceipt(input.receipt), h = headerValid(input.predecessorInventory), own = headerValid(input.candidateInventory), pointer = normalizeEntropyPolicySuccessionPointer(input.pointer), manifestHash = nz(hex(input.manifestHash, 32));
      if (r.state !== 0n || own.count !== 0n || pointer.target !== c.predecessor || pointer.codeHash !== c.predecessorCodeHash || pointer.registryStatus !== 1n || pointer.revision === 0n) throw Error("Begin requires unused inventory and selected predecessor");
      const next = entropyPolicySuccessionBeginReceipt(c, h, pointer.revision, manifestHash), scope = entropyPolicySuccessionImportScope(c, abi.getFunction("beginEntropyPolicyImport")!.selector as Hex);
      transitions = [transition(scope, entropyPolicySuccessionImportStateHash(scope, r), entropyPolicySuccessionImportStateHash(scope, next))]; targets = [targetCall(c.candidate, "beginEntropyPolicyImport", [c.predecessor, manifestHash])]; actionClass = 1n;
      request = Object.freeze({ kind: input.kind, receipt: r, predecessorInventory: h, candidateInventory: own, pointer, manifestHash }); break;
    }
    case "copy": exact(input, ["kind", "expectedIndex"]); request = Object.freeze({ kind: input.kind, expectedIndex: uint(input.expectedIndex, 256) }); actionClass = null; targets = [targetCall(c.candidate, "importNextEntropyPolicy", [request.expectedIndex])]; break;
    case "confirm-route": exact(input, ["kind", "collectionId"]); request = Object.freeze({ kind: input.kind, collectionId: uint(input.collectionId, 256) }); actionClass = null; targets = [targetCall(c.candidate, "confirmEntropyRelayRoute", [request.collectionId])]; break;
    case "seal": {
      exact(input, ["kind", "receipt", "predecessorInventory", "candidateInventory"]); const h = headerValid(input.predecessorInventory), own = headerValid(input.candidateInventory), r = receiptSource(c, input.receipt, h); if (r.state !== 1n) throw Error("Seal requires STAGING"); complete(r, own);
      transitions = [importPhase(c, "sealEntropyPolicyImport", r, 2n)]; targets = [targetCall(c.candidate, "sealEntropyPolicyImport", [])]; actionClass = 1n; request = Object.freeze({ kind: input.kind, receipt: r, predecessorInventory: h, candidateInventory: own }); break;
    }
    case "admit-route": {
      exact(input, ["kind", "origin", "receipt", "policy", "recovery", "importedPolicy", "currentAdmission", "predecessorAdmission"]);
      const origin = normalizeEntropyPolicySuccessionRuntime(input.origin), r = normalizeEntropyPolicySuccessionImportReceipt(input.receipt), p = validateEntropyPolicySuccessionPolicy(c.chainId, c.core, input.policy), imported = normalizeEntropyPolicySuccessionImportedPolicy(input.importedPolicy), current = normalizeEntropyPolicySuccessionAdmission(input.currentAdmission), prior = input.predecessorAdmission === null ? null : normalizeEntropyPolicySuccessionAdmission(input.predecessorAdmission), recovery = input.recovery === null ? null : validateEntropyPolicySuccessionRecovery(c.chainId, c.core, input.recovery);
      const exportHash = entropyPolicySuccessionExportHash(p);
      if (origin.target === c.candidate || (r.state !== 1n && r.state !== 2n) || r.nonce === 0n || r.beginActionId === ZeroHash || r.manifestHash === ZeroHash || r.nextIndex === 0n || r.nextIndex > r.count || r.predecessor !== c.predecessor || r.predecessorCodeHash !== c.predecessorCodeHash || r.importHash !== entropyPolicySuccessionImportHash(c, r) || r.importHash === ZeroHash || p.policyOrigin !== origin.target || p.policyOriginCodeHash !== origin.codeHash || !entropyPolicySuccessionRouteRequired(p) || current.importHash !== ZeroHash) throw Error("Invalid route admission source");
      if (imported.importHash !== r.importHash || imported.exportHash !== exportHash || imported.policyOrigin !== origin.target || imported.policyOriginCodeHash !== origin.codeHash || imported.policyHash !== p.record.policyHash) throw Error("Copied export receipt mismatch");
      if (origin.target !== c.predecessor && (!prior || prior.successorCodeHash !== c.predecessorCodeHash || prior.policyHash !== p.record.policyHash || prior.importHash === ZeroHash)) throw Error("Missing original predecessor route");
      if (p.recovery.maxFreshRecoveryAttempts !== 0n) { if (!recovery || recovery.policyOrigin !== origin.target || recovery.policyOriginCodeHash !== origin.codeHash) throw Error("Missing original recovery export"); verifyEntropyPolicySuccessionRecoveryBinding(p, recovery); }
      else if (recovery !== null) throw Error("Unexpected recovery export for empty binding");
      const scope = entropyPolicySuccessionRelayAdmissionScope(c, origin.target, p.collectionId), empty = { successorCodeHash: zeroHash, importHash: zeroHash, policyHash: zeroHash }, next = { successorCodeHash: c.candidateCodeHash, importHash: r.importHash, policyHash: p.record.policyHash };
      transitions = [transition(scope, entropyPolicySuccessionRelayAdmissionStateHash(scope, empty, zeroHash), entropyPolicySuccessionRelayAdmissionStateHash(scope, next, exportHash))]; targets = [targetCall(origin.target, "admitEntropyRelay", [p.collectionId, c.candidate, r.importHash])]; actionClass = 1n;
      request = Object.freeze({ kind: input.kind, origin, receipt: r, policy: p, recovery, importedPolicy: imported, currentAdmission: current, predecessorAdmission: prior }); break;
    }
    case "catalog": {
      exact(input, ["kind", "inventory", "baseHistory", "origins", "deploymentHash", "completedRows", "catalogState", "manifestState", "payload", "update"]);
      const inventory = normalizeEntropyPolicySuccessionCatalogInventory(input.inventory), baseHistory = normalizeEntropyPolicySuccessionCatalogHistory(input.baseHistory), origins = Object.freeze(dense(input.origins, 1021).map(o => normalizeEntropyPolicySuccessionRuntime(o as EntropyPolicySuccessionRuntime))), deploymentHash = nz(hex(input.deploymentHash, 32)), completedRows = uint(input.completedRows, 256), current = normalizeEntropyPolicySuccessionCatalogState(input.catalogState), manifestState = normalizeEntropyPolicySuccessionManifestState(input.manifestState), payload = address(input.payload, true), update = normalizeEntropyPolicySuccessionManifestUpdate(input.update);
      const expected = entropyPolicySuccessionCatalogInventory(c, inventory.executorCodeHash, inventory.candidateProfileHash, baseHistory, origins, deploymentHash);
      if (!same(inventory, expected) || completedRows >= BigInt(inventory.additions.length) || completedRows % 64n !== 0n) throw Error("Invalid saved canonical catalog stage");
      let stage: EntropyPolicySuccessionCatalogState = { candidateProfileHash: inventory.candidateProfileHash, catalogHash: inventory.baseCatalogHash, entryCount: inventory.baseEntryCount, revision: inventory.baseRevision };
      for (let offset = 0; offset < Number(completedRows); offset += 64) stage = entropyPolicySuccessionCatalogExtension(c.chainId, c.executor, stage, inventory.additions.slice(offset, offset + 64)).state;
      if (!same(stage, current)) throw Error("Catalog stage aggregate differs from saved progress");
      const rows = inventory.additions.slice(Number(completedRows), Number(completedRows) + 64), extension = entropyPolicySuccessionCatalogExtension(c.chainId, c.executor, current, rows);
      transitions = [extension.transition, manifestTransition(c, manifestState, payload, update, false)]; targets = [targetCall(c.executor, "extendGovernanceActionPolicy", [current.revision, current.catalogHash, extension.state.catalogHash, rows]), targetCall(c.manifest, "publishStreamSystemManifest", [payload, update])]; actionClass = 3n;
      request = Object.freeze({ kind: input.kind, inventory, baseHistory, origins, deploymentHash, completedRows, catalogState: current, manifestState, payload, update }); break;
    }
    case "cutover": {
      exact(input, ["kind", "receipt", "predecessorInventory", "candidateInventory", "pointer", "registration", "registrationStatus", "manifestState", "payload", "update"]);
      const h = headerValid(input.predecessorInventory), own = headerValid(input.candidateInventory), r = receiptSource(c, input.receipt, h), pointer = normalizeEntropyPolicySuccessionPointer(input.pointer), registration = normalizeEntropyPolicySuccessionRegistration(input.registration), status = uint(input.registrationStatus, 8), current = normalizeEntropyPolicySuccessionManifestState(input.manifestState), payload = address(input.payload, true), update = normalizeEntropyPolicySuccessionManifestUpdate(input.update);
      complete(r, own); if (!entropyPolicySuccessionImportReady(r, c.predecessor, c.predecessorCodeHash, pointer.revision, h) || pointer.frozen || pointer.target !== c.predecessor || pointer.codeHash !== c.predecessorCodeHash || status !== 1n || registration.module !== c.candidate || registration.expectedRuntimeCodeHash !== c.candidateCodeHash || registration.moduleType !== ENTROPY_POLICY_SUCCESSION_KIND || registration.interfaceId !== ENTROPY_POLICY_SUCCESSION_COORDINATOR_INTERFACE_ID) throw Error("Cutover requires exact sealed import and ACTIVE candidate registration");
      const next: EntropyPolicySuccessionPointer = Object.freeze({ target: c.candidate, codeHash: c.candidateCodeHash, frozen: false, moduleType: registration.moduleType, interfaceId: registration.interfaceId, registry: c.moduleRegistry, registryStatus: 1n, moduleManifestHash: registration.moduleManifestHash, deploymentManifestHash: registration.deploymentManifestHash, revision: next64(pointer.revision) });
      transitions = [entropyPolicySuccessionPointerTransition(c, pointer, next), importPhase(c, "activateEntropyPolicyImport", r, 3n), entropyPolicySuccessionManifestTransition(c, current, payload, update)];
      targets = [targetCall(c.core, "updateSatellitePointer", [ENTROPY_POLICY_SUCCESSION_KIND, c.candidate]), targetCall(c.candidate, "activateEntropyPolicyImport", []), targetCall(c.manifest, "publishStreamSystemManifest", [payload, update])]; actionClass = 3n;
      request = Object.freeze({ kind: input.kind, receipt: r, predecessorInventory: h, candidateInventory: own, pointer, registration, registrationStatus: status, manifestState: current, payload, update }); break;
    }
    default: throw Error("Unknown succession plan kind");
  }
  return Object.freeze({ configuration: c, request, actionClass, calls: Object.freeze(transitions.map((t, i) => governed(targets[i]!, t))), callDatas: Object.freeze(targets.map(v => v.data)), targetCalls: Object.freeze(targets), factsVerified: false });
}
export function normalizeEntropyPolicySuccessionPlan(value: EntropyPolicySuccessionPlan): EntropyPolicySuccessionPlan { exact(value, ["configuration", "request", "actionClass", "calls", "callDatas", "targetCalls", "factsVerified"]); const expected = prepareEntropyPolicySuccessionPlan(value.configuration, value.request); if (!same(expected, value)) throw Error("Succession plan differs from reconstruction"); return expected; }
/** Only genuine additions: no historical catalog merge, no deduplication and no invented admission authority. */
export function entropyPolicySuccessionCatalogRows(candidate: EntropyPolicySuccessionRuntime, origins: readonly EntropyPolicySuccessionRuntime[], deploymentHash: Hex): readonly EntropyPolicySuccessionCatalogRow[] {
  const c = normalizeEntropyPolicySuccessionRuntime(candidate), d = nz(hex(deploymentHash, 32)), os = dense(origins, 1021).map(x => normalizeEntropyPolicySuccessionRuntime(x as EntropyPolicySuccessionRuntime));
  const row = (actionClass: bigint, r: EntropyPolicySuccessionRuntime, method: string): EntropyPolicySuccessionCatalogRow => Object.freeze({ actionClass, target: r.target, selector: abi.getFunction(method)!.selector as Hex, targetCodeHash: r.codeHash, targetProfileHash: hash(["bytes32", "address"], [d, r.target]), callType: 1n, valuePolicy: 0n, valueLimit: 0n, valueSemanticsHash: zeroHash });
  const rows = [row(1n, c, "beginEntropyPolicyImport"), row(1n, c, "sealEntropyPolicyImport"), row(3n, c, "activateEntropyPolicyImport"), ...os.map(o => { if (o.target === c.target) throw Error("Origin and candidate must differ"); return row(1n, o, "admitEntropyRelay"); })];
  const key = (v: EntropyPolicySuccessionCatalogRow) => BigInt(entropyPolicySuccessionCatalogKey(v)); rows.sort((a, b) => key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : 0);
  for (let i = 1; i < rows.length; i++) if (key(rows[i - 1]!) === key(rows[i]!)) throw Error("Duplicate origin admission"); return Object.freeze(rows);
}
export function entropyPolicySuccessionCatalogKey(value: EntropyPolicySuccessionCatalogRow): Hex { const r = normalizeEntropyPolicySuccessionCatalogRow(value); return hash(["uint8", "address", "bytes4"], [r.actionClass, r.target, r.selector]); }
function catalogRows(value: readonly EntropyPolicySuccessionCatalogRow[], max: number): readonly EntropyPolicySuccessionCatalogRow[] {
  const rows = dense(value, max).map(v => normalizeEntropyPolicySuccessionCatalogRow(v as EntropyPolicySuccessionCatalogRow)); if (!rows.length) throw Error("Catalog rows must not be empty"); let previous = -1n;
  for (const r of rows) {
    const direct = r.callType === 1n, native = r.callType === 2n;
    if (r.actionClass > 5n || r.target === ZeroAddress || r.targetProfileHash === ZeroHash || (direct ? r.selector === "0x00000000" || r.targetCodeHash === ZeroHash : !native || r.selector !== "0x00000000" || r.valuePolicy === 0n)) throw Error("Invalid original catalog entry");
    if (r.valuePolicy === 0n ? r.valueLimit !== 0n || r.valueSemanticsHash !== ZeroHash : (r.valuePolicy !== 1n && r.valuePolicy !== 2n) || r.valueLimit === 0n || r.valueSemanticsHash !== id("6529STREAM_NATIVE_VALUE_CALLER_EXACT_TARGET_ATOMIC_REVERT_SURPLUS_V1")) throw Error("Invalid catalog value semantics");
    const key = BigInt(entropyPolicySuccessionCatalogKey(r)); if (key <= previous) throw Error("Catalog keys must strictly increase"); previous = key;
  }
  return Object.freeze(rows);
}
export function normalizeEntropyPolicySuccessionCatalogState(v: EntropyPolicySuccessionCatalogState): EntropyPolicySuccessionCatalogState { const s = normalize(ENTROPY_POLICY_SUCCESSION_CATALOG_STATE_TUPLE, v); if (!s.entryCount || s.entryCount > 1024n || s.candidateProfileHash === ZeroHash || s.catalogHash === ZeroHash) throw Error("Invalid bound catalog state"); return s; }
export function normalizeEntropyPolicySuccessionCatalogHistory(v: EntropyPolicySuccessionCatalogHistory): EntropyPolicySuccessionCatalogHistory { exact(v, ["initialRows", "extensions"]); const initialRows = catalogRows(v.initialRows, 1024), extensions = Object.freeze(dense(v.extensions, 1023).map(rows => catalogRows(rows as readonly EntropyPolicySuccessionCatalogRow[], 64))); const all = [...initialRows, ...extensions.flat()]; if (all.length > 1024 || new Set(all.map(entropyPolicySuccessionCatalogKey)).size !== all.length) throw Error("Catalog history exceeds capacity or repeats a key"); return Object.freeze({ initialRows, extensions }); }
export function normalizeEntropyPolicySuccessionCatalogInventory(v: EntropyPolicySuccessionCatalogInventory): EntropyPolicySuccessionCatalogInventory { const i = normalize(ENTROPY_POLICY_SUCCESSION_CATALOG_INVENTORY_TUPLE, v), additions = catalogRows(i.additions, 1024); address(i.executor, true); nz(i.executorCodeHash); nz(i.candidateProfileHash); nz(i.baseCatalogHash); if (i.baseEntryCount > 1024n || i.baseEntryCount + BigInt(additions.length) > 1024n) throw Error("Catalog capacity exceeded"); return Object.freeze({ ...i, additions }); }
export function entropyPolicySuccessionCatalogHash(chainId: bigint, executor: Address, candidateProfileHash: Hex, entries: readonly EntropyPolicySuccessionCatalogRow[]): Hex {
  const rows = catalogRows(entries, 1024); let chain = zeroHash;
  rows.forEach((r, i) => { const entry = hash(["bytes32", "uint64", ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE], [id("6529STREAM_GOVERNANCE_ACTION_POLICY_ENTRY_V1"), BigInt(i), r]); chain = hash(["bytes32", "bytes32", "bytes32", "uint64"], [id("6529STREAM_GOVERNANCE_ACTION_POLICY_CHAIN_V1"), chain, entry, BigInt(i)]); });
  return hash(["bytes32", "uint256", "address", "bytes32", "uint64", "bytes32"], [id("6529STREAM_GOVERNANCE_ACTION_POLICY_CATALOG_V1"), uint(chainId, 256), address(executor, true), nz(hex(candidateProfileHash, 32)), BigInt(rows.length), chain]);
}
/** Original extension transition, which deliberately differs from rebinding a flattened catalog. */
export function entropyPolicySuccessionCatalogExtension(chainId: bigint, executor: Address, previous: EntropyPolicySuccessionCatalogState, additions: readonly EntropyPolicySuccessionCatalogRow[]): Readonly<{ state: EntropyPolicySuccessionCatalogState; transition: EntropyPolicySuccessionTransition }> {
  const chain = uint(chainId, 256), target = address(executor, true), p = normalizeEntropyPolicySuccessionCatalogState(previous), rows = catalogRows(additions, 64), revision = next64(p.revision), entryCount = p.entryCount + BigInt(rows.length); if (entryCount > 1024n) throw Error("Catalog capacity exceeded");
  const catalogHash = hash(["bytes32", "uint256", "address", "bytes32", "uint64", "bytes32", "uint256", "bytes32"], [id("6529STREAM_GOVERNANCE_ACTION_POLICY_EXTENSION_V1"), chain, target, p.candidateProfileHash, revision, p.catalogHash, p.entryCount, hash([`${ENTROPY_POLICY_SUCCESSION_CATALOG_ROW_TUPLE}[]`], [rows])]);
  const scope = hash(["bytes32", "uint256", "address"], [id("6529STREAM_GOVERNANCE_ACTION_POLICY_SCOPE_V1"), chain, target]);
  const stateHash = (s: EntropyPolicySuccessionCatalogState) => hash(["bytes32", "bytes32", "bytes32", "uint64", "bytes32", "uint256"], [id("6529STREAM_GOVERNANCE_ACTION_POLICY_STATE_V1"), scope, s.candidateProfileHash, s.revision, s.catalogHash, s.entryCount]);
  const state = Object.freeze({ candidateProfileHash: p.candidateProfileHash, catalogHash, entryCount, revision }); return Object.freeze({ state, transition: transition(scope, stateHash(p), stateHash(state)) });
}
export function entropyPolicySuccessionCatalogHistory(chainId: bigint, executor: Address, candidateProfileHash: Hex, value: EntropyPolicySuccessionCatalogHistory): Readonly<{ history: EntropyPolicySuccessionCatalogHistory; state: EntropyPolicySuccessionCatalogState; rows: readonly EntropyPolicySuccessionCatalogRow[] }> {
  const history = normalizeEntropyPolicySuccessionCatalogHistory(value), profile = nz(hex(candidateProfileHash, 32)); let state: EntropyPolicySuccessionCatalogState = Object.freeze({ candidateProfileHash: profile, catalogHash: entropyPolicySuccessionCatalogHash(chainId, executor, profile, history.initialRows), entryCount: BigInt(history.initialRows.length), revision: 0n });
  for (const rows of history.extensions) state = entropyPolicySuccessionCatalogExtension(chainId, executor, state, rows).state;
  return Object.freeze({ history, state, rows: Object.freeze([...history.initialRows, ...history.extensions.flat()]) });
}
/** Reconstructs the complete saved base and removes only exact already-retained canonical rows. */
export function entropyPolicySuccessionCatalogInventory(configuration: EntropyPolicySuccessionConfiguration, executorCodeHash: Hex, candidateProfileHash: Hex, baseHistory: EntropyPolicySuccessionCatalogHistory, origins: readonly EntropyPolicySuccessionRuntime[], deploymentHash: Hex): EntropyPolicySuccessionCatalogInventory {
  const c = normalizeEntropyPolicySuccessionConfiguration(configuration), base = entropyPolicySuccessionCatalogHistory(c.chainId, c.executor, candidateProfileHash, baseHistory), retained = new Map(base.rows.map(r => [entropyPolicySuccessionCatalogKey(r), r]));
  const additions = entropyPolicySuccessionCatalogRows({ target: c.candidate, codeHash: c.candidateCodeHash }, origins, deploymentHash).filter(row => { const prior = retained.get(entropyPolicySuccessionCatalogKey(row)); if (prior && !same(prior, row)) throw Error("Retained catalog key has different original row"); return !prior; });
  return normalizeEntropyPolicySuccessionCatalogInventory({ chainId: c.chainId, executor: c.executor, executorCodeHash: nz(hex(executorCodeHash, 32)), candidateProfileHash: base.state.candidateProfileHash, baseCatalogHash: base.state.catalogHash, baseEntryCount: base.state.entryCount, baseRevision: base.state.revision, additions });
}
export function entropyPolicySuccessionCatalogInventoryHash(v: EntropyPolicySuccessionCatalogInventory): Hex { return hash([ENTROPY_POLICY_SUCCESSION_CATALOG_INVENTORY_TUPLE], [normalizeEntropyPolicySuccessionCatalogInventory(v)]); }

export interface EntropyPolicySuccessionGovernanceBatch { readonly plan: EntropyPolicySuccessionPlan; readonly nonce: bigint; readonly window: EntropyPolicySuccessionGovernanceWindow; readonly callsHash: Hex; readonly scopeHash: Hex; readonly oldValueHash: Hex; readonly newValueHash: Hex; readonly actionId: Hex; readonly publicationKey: Hex; readonly publicationCall: UnsignedCall; readonly scheduleCall: UnsignedCall; readonly executionCall: UnsignedCall; readonly factsVerified: false }
/** Original class-1/class-3 clock constraints. This does not establish proposer or execution authority. */
export function assertEntropyPolicySuccessionGovernanceWindow(window: EntropyPolicySuccessionGovernanceWindow, scheduleTimestamp: bigint): void { const w = normalizeEntropyPolicySuccessionGovernanceWindow(window), now = uint(scheduleTimestamp, 64); if (now > (1n << 64n) - 1n - 31536000n || w.notBefore < now + 172800n || w.expiresAfter - w.notBefore < 604800n || w.expiresAfter > now + 31536000n) throw Error("Original governance time window rejected"); }
export function entropyPolicySuccessionGovernanceBatch(input: EntropyPolicySuccessionPlan, nonce: bigint, window: EntropyPolicySuccessionGovernanceWindow): EntropyPolicySuccessionGovernanceBatch {
  const plan = normalizeEntropyPolicySuccessionPlan(input), n = uint(nonce, 256), w = normalizeEntropyPolicySuccessionGovernanceWindow(window), c = plan.configuration; if (plan.actionClass === null) throw Error("Permissionless import progress is not a governed batch"); if (w.expiresAfter - w.notBefore < 604800n) throw Error("Governance open window below original floor");
  const callsHash = hash(["bytes32", `${ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE}[]`], ["0x10f09566fb70f7947b61639c2a53b3aec872069a8b46edd08ba14eb2b5942b70", plan.calls]);
  const aggregate = (domain: string, field: "scopeHash" | "oldValueHash" | "newValueHash") => hash(["bytes32", "bytes32", "bytes32[]"], [domain, callsHash, plan.calls.map(call => call[field])]);
  const scopeHash = aggregate("0x6cfd5dfd67f064adac45602c05057edddda810734779c0ebe11b447e6985e31c", "scopeHash"), oldValueHash = aggregate("0xc5029f937b44065c2ad92d9253e07f06117567480206189fcc1409d5509222b7", "oldValueHash"), newValueHash = aggregate("0xce958009248d20d9574439fa374bc00c142940af2b496896b5bdbc00b882e98b", "newValueHash");
  const actionId = hash(["bytes32", "uint256", "address", "uint8", "bytes32", "bytes32", "bytes32", "bytes32", "uint256", "uint64", "uint64", "bytes32", "bytes32"], ["0x214cd728538bb3775a7106caff5c761bace11866a984d4a4d97a98f51971ac4b", c.chainId, c.executor, plan.actionClass, callsHash, scopeHash, oldValueHash, newValueHash, n, w.notBefore, w.expiresAfter, w.reasonHash, w.manifestHash]);
  const call = (method: string, args: readonly unknown[]): UnsignedCall => Object.freeze({ to: c.executor, value: 0n, data: governanceAbi.encodeFunctionData(method, args) as Hex });
  return Object.freeze({ plan, nonce: n, window: w, callsHash, scopeHash, oldValueHash, newValueHash, actionId, publicationKey: keccak256(`0x${plan.calls.map(v => v.callDataHash.slice(2)).join("")}`) as Hex, publicationCall: call("publishGovernanceCallData", [plan.callDatas]), scheduleCall: call("scheduleGovernanceBatch", [plan.actionClass, plan.calls, scopeHash, oldValueHash, newValueHash, w.notBefore, w.expiresAfter, w.reasonHash, w.reasonURI, w.manifestHash]), executionCall: call("executeGovernanceBatch", [actionId, plan.calls, plan.callDatas]), factsVerified: false });
}
export function normalizeEntropyPolicySuccessionGovernanceBatch(v: EntropyPolicySuccessionGovernanceBatch): EntropyPolicySuccessionGovernanceBatch { exact(v, ["plan", "nonce", "window", "callsHash", "scopeHash", "oldValueHash", "newValueHash", "actionId", "publicationKey", "publicationCall", "scheduleCall", "executionCall", "factsVerified"]); const expected = entropyPolicySuccessionGovernanceBatch(v.plan, v.nonce, v.window); if (!same(expected, v)) throw Error("Governance batch differs from original reconstruction"); return expected; }
