import { AbiCoder, Interface, ParamType, ZeroAddress, ZeroHash, getAddress, id, isHexString, keccak256, toUtf8Bytes } from "ethers";
import type { Address, Hex } from "./generated/contracts.js";
import type { UnsignedCall } from "./binding.js";
import { buildSigningPayload } from "./signing-payload.js";
import { ARTIST_HYDRATION_SNAPSHOT_TUPLE, type ArtistHydrationSnapshot } from "./current-artist-authority-hydration.js";
import { normalizeMintPolicyGraceGovernanceWindow, type MintPolicyGraceGovernanceWindow, type MintPolicyGraceGovernanceCall } from "./current-mint-policy-grace.js";

/** Supplied fixed-suite coordinates. Normalization does not authenticate code or owner ancestry. */
export interface ArtistRecoveryAdjudicationCoordinates {
  readonly chainId: bigint; readonly registry: Address; readonly owner: Address; readonly ownerCodeHash: Hex;
  readonly coordinator: Address; readonly archive: Address; readonly core: Address; readonly mintManager: Address;
  readonly evidencePublisher: Address; readonly selectionPreparation: Address;
}
export interface ArtistRecoveryRequest { readonly artistId: Hex; readonly newAddress: Address; readonly vestedAuthorityClass: bigint; readonly expectedCauseHash: Hex; readonly expectedResolutionHash: Hex; readonly evidenceHash: Hex; readonly reasonHash: Hex; readonly supersededRecordHashes: readonly Hex[] }
export interface ArtistRecoveryAuthorization { readonly nonce: bigint; readonly time: bigint; readonly signature: Hex }
export interface ArtistRecoveryVestingReference { readonly transitionRecordHash: Hex; readonly vestingCommitment: Hex }
export interface ArtistRecoveryResolutionManifest {
  readonly artistId: Hex; readonly ownerRevision: bigint; readonly causeHash: Hex; readonly resolutionHash: Hex; readonly executedHead: Hex;
  readonly basis: 0n | 1n; readonly requestCommitment: Hex; readonly resolutionEvidenceHash: Hex;
  readonly contestedVestings: readonly ArtistRecoveryVestingReference[]; readonly supersededRecordHashes: readonly Hex[];
}
export interface ArtistRecoveryFinding { readonly guardianRecordHash: Hex; readonly parties: readonly Address[] }
export interface ArtistRecoveryAppealDocument { readonly resolutionManifestHash: Hex; readonly hostileFindingsHash: Hex; readonly findings: readonly ArtistRecoveryFinding[] }
export interface ArtistRecoveryHistoryHead { readonly count: bigint; readonly ownerRevision: bigint; readonly commitment: Hex }
export interface ArtistRecoveryHistorySnapshot { readonly artistId: Hex; readonly count: bigint; readonly historyCommitment: Hex; readonly associationHash: Hex }
export interface ArtistRecoverySelectionBasis { readonly manifestHash: Hex; readonly artistId: Hex; readonly ownerCodeHash: Hex; readonly history: ArtistRecoveryHistoryHead; readonly sourceCommitment: Hex }
export interface ArtistRecoverySelectionProgress { readonly processed: bigint; readonly lastOwnerRevision: bigint; readonly historyTip: Hex; readonly excludedSeen: bigint; readonly selectedRecordHash: Hex; readonly selectedDataHash: Hex; readonly selectedNonce: bigint; readonly complete: boolean }
export interface ArtistRecoverySelectionResult { readonly sourceKey: Hex; readonly selectedRecordHash: Hex; readonly selectedDataHash: Hex; readonly selectedNonce: bigint; readonly commitment: Hex }
export interface ArtistRecoveryTransition { readonly artistId: Hex; readonly recordHash: Hex; readonly stagedAt: bigint; readonly contestEndsAt: bigint; readonly executedAt: bigint; readonly postWindowEndsAt: bigint; readonly contestedAt: bigint; readonly phase: bigint }
export interface ArtistRecoveryContext { readonly scopeHash: Hex; readonly oldValueHash: Hex; readonly newValueHash: Hex; readonly causeHash: Hex; readonly incumbent: Address; readonly postContestSeconds: bigint; readonly standingTailSeconds: bigint; readonly timingRevision: bigint; readonly delegationEpoch: bigint; readonly abandonedTransition: ArtistRecoveryTransition }
export interface ArtistRecoveryEvidenceState { readonly manifestHash: Hex; readonly basisCommitment: Hex; readonly selectionCommitment: Hex; readonly requiredRole: Hex; readonly preparedFromOwnerRevision: bigint; readonly associationHash: Hex }
export interface ArtistRecoveryProvisional { readonly transitionRecordHash: Hex; readonly windowEndsAt: bigint }
export interface ArtistRecoveryGuardianRecord { readonly recordHash: Hex; readonly terms: { readonly artistId: Hex; readonly guardians: readonly Address[]; readonly approvalThreshold: bigint; readonly minContestSeconds: bigint }; readonly signer: Address; readonly authorityClass: bigint; readonly nonce: bigint; readonly signedAt: bigint; readonly previousOperativeRecordHash: Hex; readonly provisional: ArtistRecoveryProvisional }
export interface ArtistRecoveryActionWitness { readonly actionId: Hex; readonly callsHash: Hex; readonly callIndex: bigint; readonly callDataHash: Hex; readonly executor: Address; readonly executorCodeHash: Hex; readonly proposer: Address; readonly roleMutationHash: Hex; readonly roleRevision: bigint; readonly notBefore: bigint; readonly expiresAfter: bigint; readonly minimumDelay: bigint; readonly manifestHash: Hex }
export interface ArtistRecoveryActionAssociation { readonly associationHash: Hex; readonly artistId: Hex; readonly requestHash: Hex; readonly acceptanceHash: Hex; readonly contextHash: Hex; readonly action: ArtistRecoveryActionWitness; readonly guardian: ArtistRecoveryGuardianRecord; readonly preparedBy: Address; readonly preparedAt: bigint; readonly ownerRevision: bigint }
export interface ArtistRecoveryRecordFields { readonly artistId: Hex; readonly oldAddress: Address; readonly newAddress: Address; readonly vestedAuthorityClass: bigint; readonly evidenceHash: Hex; readonly reasonHash: Hex; readonly supersededRecordsHash: Hex; readonly governanceActionId: Hex; readonly recoveredAt: bigint }
export interface ArtistRecoveryRecord { readonly recordHash: Hex; readonly fields: ArtistRecoveryRecordFields; readonly terms: ArtistRecoveryRequest; readonly executor: Address; readonly proposer: Address; readonly governanceWitnessHash: Hex; readonly contextHash: Hex; readonly acceptanceDigest: Hex; readonly acceptanceNonce: bigint; readonly acceptanceDeadline: bigint; readonly postContestSeconds: bigint; readonly standingTailSeconds: bigint; readonly timingRevision: bigint; readonly delegationEpoch: bigint; readonly abandonedTransition: ArtistRecoveryTransition }
export interface ArtistRecoveryVesting { readonly artistId: Hex; readonly transitionRecordHash: Hex; readonly operationId: bigint; readonly ownerRevision: bigint; readonly executedAt: bigint; readonly oldAddress: Address; readonly newAddress: Address; readonly authorityClass: bigint; readonly guardians: ArtistRecoveryHistoryHead; readonly previousTransitionRecordHash: Hex; readonly previousCommitment: Hex; readonly commitment: Hex }
export interface ArtistRecoveryNotice { readonly recordHash: Hex; readonly terms: { readonly artistId: Hex; readonly evidenceHash: Hex; readonly reasonURI: string }; readonly incumbent: Address; readonly initiatedAt: bigint; readonly noticeEndsAt: bigint; readonly inactivitySeconds: bigint; readonly noticeSeconds: bigint; readonly timingRevision: bigint; readonly priorLivenessAt: bigint; readonly priorActivity: bigint; readonly actionId: Hex; readonly witnessHash: Hex }
export interface ArtistRecoveryDormancyPlan { readonly authority: Address; readonly authorityClass: bigint; readonly capabilities: bigint; readonly designation: Hex; readonly directive: Hex; readonly guardian: Hex; readonly stewardGrantRecordHash: Hex; readonly postSeconds: bigint; readonly standingTail: bigint }
export interface ArtistRecoveryTerminal { readonly recordHash: Hex; readonly noticeHash: Hex; readonly actor: Address; readonly authorityClass: bigint; readonly observedAt: bigint; readonly appointmentBlock: bigint; readonly plan: ArtistRecoveryDormancyPlan; readonly evidenceHash: Hex; readonly actionId: Hex; readonly witnessHash: Hex; readonly delegationEpoch: bigint }
/** Source-derived CurrentNotice.Facts; this is not the Archive notice payload. */
export interface ArtistRecoveryCurrentNoticeFacts { readonly notice: ArtistRecoveryNotice; readonly cancellation: ArtistRecoveryTerminal; readonly phase: bigint; readonly activity: bigint; readonly proof: Hex }
export interface ArtistRecoveryCause { readonly causeHash: Hex; readonly facts: { readonly artistId: Hex; readonly kind: bigint; readonly referenceHash: Hex; readonly actor: Address; readonly reasonHash: Hex; readonly evidenceHash: Hex; readonly enteredAt: bigint; readonly incumbent: Address; readonly authorityClass: bigint; readonly priorStatus: bigint; readonly pendingTransitionHash: Hex; readonly executedTransitionHash: Hex; readonly previousCauseHash: Hex; readonly previousResolutionHash: Hex; readonly actorRetirementHash: Hex } }
export interface ArtistRecoveryNoticeEvidence { readonly cause: ArtistRecoveryCause; readonly notice: ArtistRecoveryNotice; readonly phase: bigint; readonly terminal: ArtistRecoveryTerminal }
export interface ArtistRecoveryAppealAuthority { readonly executor: Address; readonly roles: Address; readonly root: Address; readonly rootCodeHash: Hex; readonly rootRevision: bigint; readonly roleMutationHash: Hex; readonly roleRevision: bigint }
export interface ArtistRecoveryDirectiveRecord { readonly recordHash: Hex; readonly terms: { readonly artistId: Hex; readonly grantedCapabilities: bigint; readonly forbiddenCapabilities: bigint; readonly directivePayloadHash: Hex }; readonly signer: Address; readonly authorityClass: bigint; readonly nonce: bigint; readonly signedAt: bigint; readonly provisional: ArtistRecoveryProvisional }
/** Source-derived Operations.Evidence, including all optional zero-valued branches. */
export interface ArtistRecoveryEvidence { readonly manifestHash: Hex; readonly manifest: ArtistRecoveryResolutionManifest; readonly appeal: ArtistRecoveryAppealDocument; readonly appealAuthority: ArtistRecoveryAppealAuthority; readonly directive: ArtistRecoveryDirectiveRecord }
export interface ArtistRecoverySignerApproval { readonly signer: Address; readonly digest: Hex; readonly direct: boolean }
export interface ArtistRecoveryGovernanceWitness { readonly actionId: Hex; readonly proposer: Address; readonly actionClass: bigint; readonly roleMutationHash: Hex; readonly roleRevision: bigint; readonly scopeHash: Hex; readonly oldValueHash: Hex; readonly newValueHash: Hex }
export interface ArtistRecoveryPreparationPayload { readonly request: ArtistRecoveryRequest; readonly acceptance: ArtistRecoveryAuthorization; readonly context: ArtistRecoveryContext; readonly association: ArtistRecoveryActionAssociation; readonly count: bigint; readonly history: ArtistRecoveryHistorySnapshot; readonly selection: ArtistRecoverySelectionResult; readonly restored: ArtistRecoveryGuardianRecord; readonly state: ArtistRecoveryEvidenceState; readonly evidence: ArtistRecoveryEvidence }
export interface ArtistRecoveryExecutionPayload { readonly request: ArtistRecoveryRequest; readonly acceptance: ArtistRecoveryAuthorization; readonly proof: ArtistRecoverySignerApproval; readonly governance: ArtistRecoveryGovernanceWitness; readonly context: ArtistRecoveryContext; readonly record: ArtistRecoveryRecord; readonly state: ArtistRecoveryEvidenceState; readonly evidence: ArtistRecoveryEvidence }
export interface ArtistRecoveryAcceptanceMessage { readonly artistId: Hex; readonly oldAddress: Address; readonly newAddress: Address; readonly nonce: bigint; readonly deadline: bigint }
export type ArtistRecoveryGovernanceCall = MintPolicyGraceGovernanceCall;
export type ArtistRecoveryGovernanceWindow = MintPolicyGraceGovernanceWindow;

export const ARTIST_RECOVERY_REQUEST_TUPLE = "tuple(bytes32 artistId,address newAddress,uint8 vestedAuthorityClass,bytes32 expectedCauseHash,bytes32 expectedResolutionHash,bytes32 evidenceHash,bytes32 reasonHash,bytes32[] supersededRecordHashes)";
export const ARTIST_RECOVERY_AUTHORIZATION_TUPLE = "tuple(uint256 nonce,uint64 time,bytes signature)";
export const ARTIST_RECOVERY_VESTING_REFERENCE_TUPLE = "tuple(bytes32 transitionRecordHash,bytes32 vestingCommitment)";
export const ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE = `tuple(bytes32 artistId,uint64 ownerRevision,bytes32 causeHash,bytes32 resolutionHash,bytes32 executedHead,uint8 basis,bytes32 requestCommitment,bytes32 resolutionEvidenceHash,${ARTIST_RECOVERY_VESTING_REFERENCE_TUPLE}[] contestedVestings,bytes32[] supersededRecordHashes)`;
export const ARTIST_RECOVERY_FINDING_TUPLE = "tuple(bytes32 guardianRecordHash,address[] parties)";
export const ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE = `tuple(bytes32 resolutionManifestHash,bytes32 hostileFindingsHash,${ARTIST_RECOVERY_FINDING_TUPLE}[] findings)`;
export const ARTIST_RECOVERY_HISTORY_HEAD_TUPLE = "tuple(uint64 count,uint64 ownerRevision,bytes32 commitment)";
export const ARTIST_RECOVERY_HISTORY_SNAPSHOT_TUPLE = "tuple(bytes32 artistId,uint64 count,bytes32 historyCommitment,bytes32 associationHash)";
export const ARTIST_RECOVERY_SELECTION_BASIS_TUPLE = `tuple(bytes32 manifestHash,bytes32 artistId,bytes32 ownerCodeHash,${ARTIST_RECOVERY_HISTORY_HEAD_TUPLE} history,bytes32 sourceCommitment)`;
export const ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE = "tuple(uint64 processed,uint64 lastOwnerRevision,bytes32 historyTip,uint64 excludedSeen,bytes32 selectedRecordHash,bytes32 selectedDataHash,uint256 selectedNonce,bool complete)";
export const ARTIST_RECOVERY_SELECTION_RESULT_TUPLE = "tuple(bytes32 sourceKey,bytes32 selectedRecordHash,bytes32 selectedDataHash,uint256 selectedNonce,bytes32 commitment)";
export const ARTIST_RECOVERY_TRANSITION_TUPLE = "tuple(bytes32 artistId,bytes32 recordHash,uint64 stagedAt,uint64 contestEndsAt,uint64 executedAt,uint64 postWindowEndsAt,uint64 contestedAt,uint8 phase)";
export const ARTIST_RECOVERY_CONTEXT_TUPLE = `tuple(bytes32 scopeHash,bytes32 oldValueHash,bytes32 newValueHash,bytes32 causeHash,address incumbent,uint64 postContestSeconds,uint64 standingTailSeconds,uint64 timingRevision,uint64 delegationEpoch,${ARTIST_RECOVERY_TRANSITION_TUPLE} abandonedTransition)`;
export const ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE = "tuple(bytes32 manifestHash,bytes32 basisCommitment,bytes32 selectionCommitment,bytes32 requiredRole,uint64 preparedFromOwnerRevision,bytes32 associationHash)";
export const ARTIST_RECOVERY_PROVISIONAL_TUPLE = "tuple(bytes32 transitionRecordHash,uint64 windowEndsAt)";
export const ARTIST_RECOVERY_GUARDIAN_RECORD_TUPLE = `tuple(bytes32 recordHash,tuple(bytes32 artistId,address[] guardians,uint32 approvalThreshold,uint64 minContestSeconds) terms,address signer,uint8 authorityClass,uint256 nonce,uint64 signedAt,bytes32 previousOperativeRecordHash,${ARTIST_RECOVERY_PROVISIONAL_TUPLE} provisional)`;
export const ARTIST_RECOVERY_ACTION_WITNESS_TUPLE = "tuple(bytes32 actionId,bytes32 callsHash,uint256 callIndex,bytes32 callDataHash,address executor,bytes32 executorCodeHash,address proposer,bytes32 roleMutationHash,uint64 roleRevision,uint64 notBefore,uint64 expiresAfter,uint64 minimumDelay,bytes32 manifestHash)";
export const ARTIST_RECOVERY_ACTION_ASSOCIATION_TUPLE = `tuple(bytes32 associationHash,bytes32 artistId,bytes32 requestHash,bytes32 acceptanceHash,bytes32 contextHash,${ARTIST_RECOVERY_ACTION_WITNESS_TUPLE} action,${ARTIST_RECOVERY_GUARDIAN_RECORD_TUPLE} guardian,address preparedBy,uint64 preparedAt,uint64 ownerRevision)`;
export const ARTIST_RECOVERY_RECORD_FIELDS_TUPLE = "tuple(bytes32 artistId,address oldAddress,address newAddress,uint8 vestedAuthorityClass,bytes32 evidenceHash,bytes32 reasonHash,bytes32 supersededRecordsHash,bytes32 governanceActionId,uint64 recoveredAt)";
export const ARTIST_RECOVERY_RECORD_TUPLE = `tuple(bytes32 recordHash,${ARTIST_RECOVERY_RECORD_FIELDS_TUPLE} fields,${ARTIST_RECOVERY_REQUEST_TUPLE} terms,address executor,address proposer,bytes32 governanceWitnessHash,bytes32 contextHash,bytes32 acceptanceDigest,uint256 acceptanceNonce,uint64 acceptanceDeadline,uint64 postContestSeconds,uint64 standingTailSeconds,uint64 timingRevision,uint64 delegationEpoch,${ARTIST_RECOVERY_TRANSITION_TUPLE} abandonedTransition)`;
export const ARTIST_RECOVERY_VESTING_TUPLE = `tuple(bytes32 artistId,bytes32 transitionRecordHash,uint16 operationId,uint64 ownerRevision,uint64 executedAt,address oldAddress,address newAddress,uint8 authorityClass,${ARTIST_RECOVERY_HISTORY_HEAD_TUPLE} guardians,bytes32 previousTransitionRecordHash,bytes32 previousCommitment,bytes32 commitment)`;
export const ARTIST_RECOVERY_NOTICE_TUPLE = "tuple(bytes32 recordHash,tuple(bytes32 artistId,bytes32 evidenceHash,string reasonURI) terms,address incumbent,uint64 initiatedAt,uint64 noticeEndsAt,uint64 inactivitySeconds,uint64 noticeSeconds,uint64 timingRevision,uint64 priorLivenessAt,uint256 priorActivity,bytes32 actionId,bytes32 witnessHash)";
export const ARTIST_RECOVERY_DORMANCY_PLAN_TUPLE = "tuple(address authority,uint8 authorityClass,uint32 capabilities,bytes32 designation,bytes32 directive,bytes32 guardian,bytes32 stewardGrantRecordHash,uint64 postSeconds,uint64 standingTail)";
export const ARTIST_RECOVERY_TERMINAL_TUPLE = `tuple(bytes32 recordHash,bytes32 noticeHash,address actor,uint8 authorityClass,uint64 observedAt,uint64 appointmentBlock,${ARTIST_RECOVERY_DORMANCY_PLAN_TUPLE} plan,bytes32 evidenceHash,bytes32 actionId,bytes32 witnessHash,uint64 delegationEpoch)`;
export const ARTIST_RECOVERY_CURRENT_NOTICE_FACTS_TUPLE = `tuple(${ARTIST_RECOVERY_NOTICE_TUPLE} notice,${ARTIST_RECOVERY_TERMINAL_TUPLE} cancellation,uint8 phase,uint256 activity,bytes32 proof)`;
export const ARTIST_RECOVERY_CAUSE_TUPLE = "tuple(bytes32 causeHash,tuple(bytes32 artistId,uint8 kind,bytes32 referenceHash,address actor,bytes32 reasonHash,bytes32 evidenceHash,uint64 enteredAt,address incumbent,uint8 authorityClass,uint8 priorStatus,bytes32 pendingTransitionHash,bytes32 executedTransitionHash,bytes32 previousCauseHash,bytes32 previousResolutionHash,bytes32 actorRetirementHash) facts)";
export const ARTIST_RECOVERY_NOTICE_EVIDENCE_TUPLE = `tuple(${ARTIST_RECOVERY_CAUSE_TUPLE} cause,${ARTIST_RECOVERY_NOTICE_TUPLE} notice,uint8 phase,${ARTIST_RECOVERY_TERMINAL_TUPLE} terminal)`;
export const ARTIST_RECOVERY_APPEAL_AUTHORITY_TUPLE = "tuple(address executor,address roles,address root,bytes32 rootCodeHash,uint64 rootRevision,bytes32 roleMutationHash,uint64 roleRevision)";
export const ARTIST_RECOVERY_DIRECTIVE_RECORD_TUPLE = `tuple(bytes32 recordHash,tuple(bytes32 artistId,uint32 grantedCapabilities,uint32 forbiddenCapabilities,bytes32 directivePayloadHash) terms,address signer,uint8 authorityClass,uint256 nonce,uint64 signedAt,${ARTIST_RECOVERY_PROVISIONAL_TUPLE} provisional)`;
export const ARTIST_RECOVERY_EVIDENCE_TUPLE = `tuple(bytes32 manifestHash,${ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE} manifest,${ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE} appeal,${ARTIST_RECOVERY_APPEAL_AUTHORITY_TUPLE} appealAuthority,${ARTIST_RECOVERY_DIRECTIVE_RECORD_TUPLE} directive)`;
export const ARTIST_RECOVERY_SIGNER_APPROVAL_TUPLE = "tuple(address signer,bytes32 digest,bool direct)";
export const ARTIST_RECOVERY_GOVERNANCE_WITNESS_TUPLE = "tuple(bytes32 actionId,address proposer,uint8 actionClass,bytes32 roleMutationHash,uint64 roleRevision,bytes32 scopeHash,bytes32 oldValueHash,bytes32 newValueHash)";
export const ARTIST_RECOVERY_PREPARATION_PAYLOAD_TUPLE = `tuple(${ARTIST_RECOVERY_REQUEST_TUPLE} request,${ARTIST_RECOVERY_AUTHORIZATION_TUPLE} acceptance,${ARTIST_RECOVERY_CONTEXT_TUPLE} context,${ARTIST_RECOVERY_ACTION_ASSOCIATION_TUPLE} association,uint64 count,${ARTIST_RECOVERY_HISTORY_SNAPSHOT_TUPLE} history,${ARTIST_RECOVERY_SELECTION_RESULT_TUPLE} selection,${ARTIST_RECOVERY_GUARDIAN_RECORD_TUPLE} restored,${ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE} state,${ARTIST_RECOVERY_EVIDENCE_TUPLE} evidence)`;
export const ARTIST_RECOVERY_EXECUTION_PAYLOAD_TUPLE = `tuple(${ARTIST_RECOVERY_REQUEST_TUPLE} request,${ARTIST_RECOVERY_AUTHORIZATION_TUPLE} acceptance,${ARTIST_RECOVERY_SIGNER_APPROVAL_TUPLE} proof,${ARTIST_RECOVERY_GOVERNANCE_WITNESS_TUPLE} governance,${ARTIST_RECOVERY_CONTEXT_TUPLE} context,${ARTIST_RECOVERY_RECORD_TUPLE} record,${ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE} state,${ARTIST_RECOVERY_EVIDENCE_TUPLE} evidence)`;
export const ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE = "tuple(address target,uint256 value,bytes4 selector,bytes32 callDataHash,bytes32 scopeHash,bytes32 oldValueHash,bytes32 newValueHash)";
export const ARTIST_RECOVERY_PREPARATION_NOTICE_TAG = id("6529STREAM_ARTIST_CURRENT_NOTICE_RECOVERY_PREPARATION_V1") as Hex;
export const ARTIST_RECOVERY_EXECUTION_NOTICE_TAG = id("6529STREAM_ARTIST_CURRENT_NOTICE_RECOVERY_EXECUTION_V1") as Hex;
export const ARTIST_RECOVERY_ARBITER_ROLE = id("ROLE_ATTRIBUTION_ARBITER") as Hex;
export const ARTIST_RECOVERY_APPEAL_ROLE = id("ROLE_ATTRIBUTION_APPEAL") as Hex;

const coder = AbiCoder.defaultAbiCoder();
/** Explicit client allocation ceiling; the contract's Archive ceiling is observed separately. */
export const ARTIST_RECOVERY_CODEC_MAX_BYTES = 524288;
function exact(value: unknown, keys: readonly string[], label: string): void { if (!value || typeof value !== "object" || Array.isArray(value)) throw Error(`${label} must be an object`); const actual = Reflect.ownKeys(value); if (actual.length !== keys.length || actual.some(k => typeof k !== "string" || !keys.includes(k))) throw Error(`${label} has missing or unknown fields`); }
function uint(value: unknown, bits: number): bigint { if (typeof value !== "bigint" || value < 0n || value >= 1n << BigInt(bits)) throw Error(`Expected uint${bits} bigint`); return value; }
function hex(value: unknown, size?: number): Hex { if (typeof value !== "string" || !isHexString(value, size) || value.length % 2 !== 0) throw Error("Expected hex bytes"); return value.toLowerCase() as Hex; }
function bounded(value: Hex): Hex { if (value.length > 2 + ARTIST_RECOVERY_CODEC_MAX_BYTES * 2) throw Error("Complete encoding exceeds client bound"); return value; }
function nz(value: Hex): Hex { if (value === ZeroHash) throw Error("Expected nonzero commitment"); return value; }
function address(value: unknown, nonzero = false): Address { if (typeof value !== "string") throw Error("Expected address"); const a = getAddress(value) as Address; if (nonzero && a === ZeroAddress) throw Error("Expected nonzero address"); return a; }
function dense(value: unknown, maximum: number): readonly unknown[] { if (!Array.isArray(value) || value.length > maximum || Reflect.ownKeys(value).length !== value.length + 1 || Array.from({ length: value.length }, (_, i) => i).some(i => !Object.hasOwn(value, i))) throw Error("Expected bounded dense array"); return value; }
function normal(p: ParamType, value: unknown, decoded = false): unknown {
  if (p.baseType === "array") { const a = dense(value, p.arrayLength === -1 ? (p.name === "parties" || p.name === "guardians" ? 8 : 64) : p.arrayLength!); if (p.arrayLength !== -1 && a.length !== p.arrayLength) throw Error("Wrong fixed array length"); return Object.freeze(a.map(x => normal(p.arrayChildren!, x, decoded))); }
  if (p.baseType === "tuple") { if (!decoded) exact(value, p.components!.map(f => f.name), "Original tuple"); return Object.freeze(Object.fromEntries(p.components!.map((f, i) => [f.name, normal(f, decoded ? (value as readonly unknown[])[i] : Reflect.get(value as object, f.name), decoded)]))); }
  if (p.type === "address") return address(value);
  if (p.type === "bool") { if (typeof value !== "boolean") throw Error("Expected boolean"); return value; }
  if (p.type.startsWith("uint")) { const v = uint(value, Number(p.type.slice(4))); if (p.name === "basis" && v > 1n) throw Error("Unknown original vesting basis"); return v; }
  if (p.type === "bytes") { const b = hex(value); if (b.length > 2 + (p.name === "signature" ? 4096 : ARTIST_RECOVERY_CODEC_MAX_BYTES) * 2) throw Error("Byte string exceeds bound"); return b; }
  if (p.type.startsWith("bytes")) return hex(value, Number(p.type.slice(5)));
  if (p.type === "string") { if (typeof value !== "string" || /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(value) || toUtf8Bytes(value).length > 2048) throw Error("Expected bounded Unicode text"); return value; }
  throw Error("Unsupported original ABI type");
}
function normalize<T>(type: string, value: T): T { return normal(ParamType.from(type), value) as T; }
function encode(type: string, value: unknown, flattened = false): Hex { const p = ParamType.from(type), v = normalize(type, value); const out = flattened ? coder.encode(p.components!, p.components!.map(f => Reflect.get(v as object, f.name))) : coder.encode([p], [v]); if (out.length > 2 + ARTIST_RECOVERY_CODEC_MAX_BYTES * 2) throw Error("Encoded content exceeds client bound"); return out as Hex; }
function decode<T>(type: string, raw: Hex, flattened = false): T { const b = hex(raw); if (b.length > 2 + ARTIST_RECOVERY_CODEC_MAX_BYTES * 2) throw Error("Encoded content exceeds client bound"); const p = ParamType.from(type), value = normal(p, flattened ? coder.decode(p.components!, b) : coder.decode([p], b)[0], true) as T; if (encode(type, value, flattened) !== b) throw Error("Noncanonical ABI encoding"); return value; }
function digest(types: readonly (string | ParamType)[], values: readonly unknown[]): Hex { return keccak256(coder.encode(types, values)) as Hex; }
function same(a: unknown, b: unknown): boolean { if (a === b) return true; if (!a || !b || typeof a !== "object" || typeof b !== "object") return false; const keys = Reflect.ownKeys(a), other = Reflect.ownKeys(b); return keys.length === other.length && keys.every(k => other.includes(k) && same(Reflect.get(a, k), Reflect.get(b, k))); }
function sortedHashes(value: readonly Hex[]): readonly Hex[] { const list = dense(value, 64).map(v => hex(v, 32)); let previous = 0n; for (const item of list) { if (BigInt(item) <= previous) throw Error("Hashes must be strictly increasing and nonzero"); previous = BigInt(item); } return Object.freeze(list); }
export function normalizeArtistRecoveryAdjudicationCoordinates(v: ArtistRecoveryAdjudicationCoordinates): ArtistRecoveryAdjudicationCoordinates { exact(v, ["chainId", "registry", "owner", "ownerCodeHash", "coordinator", "archive", "core", "mintManager", "evidencePublisher", "selectionPreparation"], "Recovery coordinates"); const result = Object.freeze({ chainId: uint(v.chainId, 256), registry: address(v.registry, true), owner: address(v.owner, true), ownerCodeHash: nz(hex(v.ownerCodeHash, 32)), coordinator: address(v.coordinator, true), archive: address(v.archive, true), core: address(v.core, true), mintManager: address(v.mintManager, true), evidencePublisher: address(v.evidencePublisher, true), selectionPreparation: address(v.selectionPreparation, true) }); if (result.registry === result.owner) throw Error("Registry and Identity owner must differ"); return result; }
export function normalizeArtistRecoveryRequest(v: ArtistRecoveryRequest): ArtistRecoveryRequest { const p = normalize(ARTIST_RECOVERY_REQUEST_TUPLE, v); return Object.freeze({ ...p, supersededRecordHashes: sortedHashes(p.supersededRecordHashes) }); }
export function normalizeArtistRecoveryAuthorization(v: ArtistRecoveryAuthorization): ArtistRecoveryAuthorization { return normalize(ARTIST_RECOVERY_AUTHORIZATION_TUPLE, v); }
/** Publisher grammar only; no caller-supplied ancestry is treated as authenticated. */
export function normalizeArtistRecoveryResolutionManifest(v: ArtistRecoveryResolutionManifest): ArtistRecoveryResolutionManifest {
  const m = normalize(ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE, v); nz(m.artistId); nz(m.causeHash); nz(m.requestCommitment); nz(m.resolutionEvidenceHash);
  if (!m.ownerRevision || (m.basis !== 0n && m.basis !== 1n) || (m.basis === 0n ? m.contestedVestings.length !== 0 : m.contestedVestings.length === 0 || m.executedHead === ZeroHash)) throw Error("Invalid resolution manifest shape");
  const records = new Set<string>(), commitments = new Set<string>(); for (const r of m.contestedVestings) { nz(r.transitionRecordHash); nz(r.vestingCommitment); if (records.has(r.transitionRecordHash) || commitments.has(r.vestingCommitment)) throw Error("Duplicate declared vesting"); records.add(r.transitionRecordHash); commitments.add(r.vestingCommitment); }
  return Object.freeze({ ...m, supersededRecordHashes: sortedHashes(m.supersededRecordHashes) });
}
/** Does not require a retained manifest or interpret the hostile-finding content. */
export function normalizeArtistRecoveryAppealDocument(v: ArtistRecoveryAppealDocument): ArtistRecoveryAppealDocument { const d = normalize(ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE, v); nz(d.resolutionManifestHash); nz(d.hostileFindingsHash); if (!d.findings.length) throw Error("Appeal requires findings"); let previous = 0n; for (const f of d.findings) { if (BigInt(f.guardianRecordHash) <= previous || !f.parties.length) throw Error("Findings must be strictly increasing and nonempty"); previous = BigInt(f.guardianRecordHash); let prior = 0n; for (const a of f.parties) { if (BigInt(a) <= prior) throw Error("Parties must be strictly increasing and nonzero"); prior = BigInt(a); } } return d; }

export function normalizeArtistRecoveryHistoryHead(v: ArtistRecoveryHistoryHead): ArtistRecoveryHistoryHead { return normalize(ARTIST_RECOVERY_HISTORY_HEAD_TUPLE, v); }
export function normalizeArtistRecoveryHistorySnapshot(v: ArtistRecoveryHistorySnapshot): ArtistRecoveryHistorySnapshot { return normalize(ARTIST_RECOVERY_HISTORY_SNAPSHOT_TUPLE, v); }
export function normalizeArtistRecoverySelectionBasis(v: ArtistRecoverySelectionBasis): ArtistRecoverySelectionBasis { return normalize(ARTIST_RECOVERY_SELECTION_BASIS_TUPLE, v); }
export function normalizeArtistRecoverySelectionProgress(v: ArtistRecoverySelectionProgress): ArtistRecoverySelectionProgress { return normalize(ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE, v); }
export function normalizeArtistRecoverySelectionResult(v: ArtistRecoverySelectionResult): ArtistRecoverySelectionResult { return normalize(ARTIST_RECOVERY_SELECTION_RESULT_TUPLE, v); }
export function normalizeArtistRecoveryTransition(v: ArtistRecoveryTransition): ArtistRecoveryTransition { return normalize(ARTIST_RECOVERY_TRANSITION_TUPLE, v); }
export function normalizeArtistRecoveryContext(v: ArtistRecoveryContext): ArtistRecoveryContext { return normalize(ARTIST_RECOVERY_CONTEXT_TUPLE, v); }
export function normalizeArtistRecoveryEvidenceState(v: ArtistRecoveryEvidenceState): ArtistRecoveryEvidenceState { return normalize(ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE, v); }
export function normalizeArtistRecoveryGuardianRecord(v: ArtistRecoveryGuardianRecord): ArtistRecoveryGuardianRecord { return normalize(ARTIST_RECOVERY_GUARDIAN_RECORD_TUPLE, v); }
export function normalizeArtistRecoveryActionWitness(v: ArtistRecoveryActionWitness): ArtistRecoveryActionWitness { return normalize(ARTIST_RECOVERY_ACTION_WITNESS_TUPLE, v); }
export function normalizeArtistRecoveryActionAssociation(v: ArtistRecoveryActionAssociation): ArtistRecoveryActionAssociation { return normalize(ARTIST_RECOVERY_ACTION_ASSOCIATION_TUPLE, v); }
export function normalizeArtistRecoveryRecordFields(v: ArtistRecoveryRecordFields): ArtistRecoveryRecordFields { return normalize(ARTIST_RECOVERY_RECORD_FIELDS_TUPLE, v); }
export function normalizeArtistRecoveryRecord(v: ArtistRecoveryRecord): ArtistRecoveryRecord { return normalize(ARTIST_RECOVERY_RECORD_TUPLE, v); }
export function normalizeArtistRecoveryVesting(v: ArtistRecoveryVesting): ArtistRecoveryVesting { return normalize(ARTIST_RECOVERY_VESTING_TUPLE, v); }
export function normalizeArtistRecoveryNotice(v: ArtistRecoveryNotice): ArtistRecoveryNotice { return normalize(ARTIST_RECOVERY_NOTICE_TUPLE, v); }
export function normalizeArtistRecoveryTerminal(v: ArtistRecoveryTerminal): ArtistRecoveryTerminal { return normalize(ARTIST_RECOVERY_TERMINAL_TUPLE, v); }
export function normalizeArtistRecoveryCurrentNoticeFacts(v: ArtistRecoveryCurrentNoticeFacts): ArtistRecoveryCurrentNoticeFacts { return normalize(ARTIST_RECOVERY_CURRENT_NOTICE_FACTS_TUPLE, v); }
export function normalizeArtistRecoveryCause(v: ArtistRecoveryCause): ArtistRecoveryCause { return normalize(ARTIST_RECOVERY_CAUSE_TUPLE, v); }
export function normalizeArtistRecoveryNoticeEvidence(v: ArtistRecoveryNoticeEvidence): ArtistRecoveryNoticeEvidence { return normalize(ARTIST_RECOVERY_NOTICE_EVIDENCE_TUPLE, v); }
export function normalizeArtistRecoveryAppealAuthority(v: ArtistRecoveryAppealAuthority): ArtistRecoveryAppealAuthority { return normalize(ARTIST_RECOVERY_APPEAL_AUTHORITY_TUPLE, v); }
export function normalizeArtistRecoveryDirectiveRecord(v: ArtistRecoveryDirectiveRecord): ArtistRecoveryDirectiveRecord { return normalize(ARTIST_RECOVERY_DIRECTIVE_RECORD_TUPLE, v); }
export function normalizeArtistRecoveryEvidence(v: ArtistRecoveryEvidence): ArtistRecoveryEvidence { return normalize(ARTIST_RECOVERY_EVIDENCE_TUPLE, v); }
export function normalizeArtistRecoverySignerApproval(v: ArtistRecoverySignerApproval): ArtistRecoverySignerApproval { return normalize(ARTIST_RECOVERY_SIGNER_APPROVAL_TUPLE, v); }
export function normalizeArtistRecoveryGovernanceWitness(v: ArtistRecoveryGovernanceWitness): ArtistRecoveryGovernanceWitness { return normalize(ARTIST_RECOVERY_GOVERNANCE_WITNESS_TUPLE, v); }
export function normalizeArtistRecoveryPreparationPayload(v: ArtistRecoveryPreparationPayload): ArtistRecoveryPreparationPayload { return normalize(ARTIST_RECOVERY_PREPARATION_PAYLOAD_TUPLE, v); }
export function normalizeArtistRecoveryExecutionPayload(v: ArtistRecoveryExecutionPayload): ArtistRecoveryExecutionPayload { return normalize(ARTIST_RECOVERY_EXECUTION_PAYLOAD_TUPLE, v); }
export function encodeArtistRecoveryRequest(v: ArtistRecoveryRequest): Hex { return encode(ARTIST_RECOVERY_REQUEST_TUPLE, normalizeArtistRecoveryRequest(v)); }
export function decodeArtistRecoveryRequest(v: Hex): ArtistRecoveryRequest { return normalizeArtistRecoveryRequest(decode<ArtistRecoveryRequest>(ARTIST_RECOVERY_REQUEST_TUPLE, v)); }
export function encodeArtistRecoveryAuthorization(v: ArtistRecoveryAuthorization): Hex { return encode(ARTIST_RECOVERY_AUTHORIZATION_TUPLE, normalizeArtistRecoveryAuthorization(v)); }
export function decodeArtistRecoveryAuthorization(v: Hex): ArtistRecoveryAuthorization { return normalizeArtistRecoveryAuthorization(decode<ArtistRecoveryAuthorization>(ARTIST_RECOVERY_AUTHORIZATION_TUPLE, v)); }
export function encodeArtistRecoveryResolutionManifest(v: ArtistRecoveryResolutionManifest): Hex { return encode(ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE, normalizeArtistRecoveryResolutionManifest(v)); }
export function decodeArtistRecoveryResolutionManifest(v: Hex): ArtistRecoveryResolutionManifest { return normalizeArtistRecoveryResolutionManifest(decode<ArtistRecoveryResolutionManifest>(ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE, v)); }
export function encodeArtistRecoveryAppealDocument(v: ArtistRecoveryAppealDocument): Hex { return encode(ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE, normalizeArtistRecoveryAppealDocument(v)); }
export function decodeArtistRecoveryAppealDocument(v: Hex): ArtistRecoveryAppealDocument { return normalizeArtistRecoveryAppealDocument(decode<ArtistRecoveryAppealDocument>(ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE, v)); }
export function encodeArtistRecoveryHistoryHead(v: ArtistRecoveryHistoryHead): Hex { return encode(ARTIST_RECOVERY_HISTORY_HEAD_TUPLE, normalizeArtistRecoveryHistoryHead(v)); }
export function decodeArtistRecoveryHistoryHead(v: Hex): ArtistRecoveryHistoryHead { return normalizeArtistRecoveryHistoryHead(decode<ArtistRecoveryHistoryHead>(ARTIST_RECOVERY_HISTORY_HEAD_TUPLE, v)); }
export function encodeArtistRecoveryHistorySnapshot(v: ArtistRecoveryHistorySnapshot): Hex { return encode(ARTIST_RECOVERY_HISTORY_SNAPSHOT_TUPLE, normalizeArtistRecoveryHistorySnapshot(v)); }
export function decodeArtistRecoveryHistorySnapshot(v: Hex): ArtistRecoveryHistorySnapshot { return normalizeArtistRecoveryHistorySnapshot(decode<ArtistRecoveryHistorySnapshot>(ARTIST_RECOVERY_HISTORY_SNAPSHOT_TUPLE, v)); }
export function encodeArtistRecoverySelectionBasis(v: ArtistRecoverySelectionBasis): Hex { return encode(ARTIST_RECOVERY_SELECTION_BASIS_TUPLE, normalizeArtistRecoverySelectionBasis(v)); }
export function decodeArtistRecoverySelectionBasis(v: Hex): ArtistRecoverySelectionBasis { return normalizeArtistRecoverySelectionBasis(decode<ArtistRecoverySelectionBasis>(ARTIST_RECOVERY_SELECTION_BASIS_TUPLE, v)); }
export function encodeArtistRecoverySelectionProgress(v: ArtistRecoverySelectionProgress): Hex { return encode(ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE, normalizeArtistRecoverySelectionProgress(v)); }
export function decodeArtistRecoverySelectionProgress(v: Hex): ArtistRecoverySelectionProgress { return normalizeArtistRecoverySelectionProgress(decode<ArtistRecoverySelectionProgress>(ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE, v)); }
export function encodeArtistRecoverySelectionResult(v: ArtistRecoverySelectionResult): Hex { return encode(ARTIST_RECOVERY_SELECTION_RESULT_TUPLE, normalizeArtistRecoverySelectionResult(v)); }
export function decodeArtistRecoverySelectionResult(v: Hex): ArtistRecoverySelectionResult { return normalizeArtistRecoverySelectionResult(decode<ArtistRecoverySelectionResult>(ARTIST_RECOVERY_SELECTION_RESULT_TUPLE, v)); }
export function encodeArtistRecoveryTransition(v: ArtistRecoveryTransition): Hex { return encode(ARTIST_RECOVERY_TRANSITION_TUPLE, normalizeArtistRecoveryTransition(v)); }
export function decodeArtistRecoveryTransition(v: Hex): ArtistRecoveryTransition { return normalizeArtistRecoveryTransition(decode<ArtistRecoveryTransition>(ARTIST_RECOVERY_TRANSITION_TUPLE, v)); }
export function encodeArtistRecoveryContext(v: ArtistRecoveryContext): Hex { return encode(ARTIST_RECOVERY_CONTEXT_TUPLE, normalizeArtistRecoveryContext(v)); }
export function decodeArtistRecoveryContext(v: Hex): ArtistRecoveryContext { return normalizeArtistRecoveryContext(decode<ArtistRecoveryContext>(ARTIST_RECOVERY_CONTEXT_TUPLE, v)); }
export function encodeArtistRecoveryEvidenceState(v: ArtistRecoveryEvidenceState): Hex { return encode(ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE, normalizeArtistRecoveryEvidenceState(v)); }
export function decodeArtistRecoveryEvidenceState(v: Hex): ArtistRecoveryEvidenceState { return normalizeArtistRecoveryEvidenceState(decode<ArtistRecoveryEvidenceState>(ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE, v)); }
export function encodeArtistRecoveryGuardianRecord(v: ArtistRecoveryGuardianRecord): Hex { return encode(ARTIST_RECOVERY_GUARDIAN_RECORD_TUPLE, normalizeArtistRecoveryGuardianRecord(v)); }
export function decodeArtistRecoveryGuardianRecord(v: Hex): ArtistRecoveryGuardianRecord { return normalizeArtistRecoveryGuardianRecord(decode<ArtistRecoveryGuardianRecord>(ARTIST_RECOVERY_GUARDIAN_RECORD_TUPLE, v)); }
export function encodeArtistRecoveryActionWitness(v: ArtistRecoveryActionWitness): Hex { return encode(ARTIST_RECOVERY_ACTION_WITNESS_TUPLE, normalizeArtistRecoveryActionWitness(v)); }
export function decodeArtistRecoveryActionWitness(v: Hex): ArtistRecoveryActionWitness { return normalizeArtistRecoveryActionWitness(decode<ArtistRecoveryActionWitness>(ARTIST_RECOVERY_ACTION_WITNESS_TUPLE, v)); }
export function encodeArtistRecoveryActionAssociation(v: ArtistRecoveryActionAssociation): Hex { return encode(ARTIST_RECOVERY_ACTION_ASSOCIATION_TUPLE, normalizeArtistRecoveryActionAssociation(v)); }
export function decodeArtistRecoveryActionAssociation(v: Hex): ArtistRecoveryActionAssociation { return normalizeArtistRecoveryActionAssociation(decode<ArtistRecoveryActionAssociation>(ARTIST_RECOVERY_ACTION_ASSOCIATION_TUPLE, v)); }
export function encodeArtistRecoveryRecordFields(v: ArtistRecoveryRecordFields): Hex { return encode(ARTIST_RECOVERY_RECORD_FIELDS_TUPLE, normalizeArtistRecoveryRecordFields(v)); }
export function decodeArtistRecoveryRecordFields(v: Hex): ArtistRecoveryRecordFields { return normalizeArtistRecoveryRecordFields(decode<ArtistRecoveryRecordFields>(ARTIST_RECOVERY_RECORD_FIELDS_TUPLE, v)); }
export function encodeArtistRecoveryRecord(v: ArtistRecoveryRecord): Hex { return encode(ARTIST_RECOVERY_RECORD_TUPLE, normalizeArtistRecoveryRecord(v)); }
export function decodeArtistRecoveryRecord(v: Hex): ArtistRecoveryRecord { return normalizeArtistRecoveryRecord(decode<ArtistRecoveryRecord>(ARTIST_RECOVERY_RECORD_TUPLE, v)); }
export function encodeArtistRecoveryVesting(v: ArtistRecoveryVesting): Hex { return encode(ARTIST_RECOVERY_VESTING_TUPLE, normalizeArtistRecoveryVesting(v)); }
export function decodeArtistRecoveryVesting(v: Hex): ArtistRecoveryVesting { return normalizeArtistRecoveryVesting(decode<ArtistRecoveryVesting>(ARTIST_RECOVERY_VESTING_TUPLE, v)); }
export function encodeArtistRecoveryNotice(v: ArtistRecoveryNotice): Hex { return encode(ARTIST_RECOVERY_NOTICE_TUPLE, normalizeArtistRecoveryNotice(v)); }
export function decodeArtistRecoveryNotice(v: Hex): ArtistRecoveryNotice { return normalizeArtistRecoveryNotice(decode<ArtistRecoveryNotice>(ARTIST_RECOVERY_NOTICE_TUPLE, v)); }
export function encodeArtistRecoveryTerminal(v: ArtistRecoveryTerminal): Hex { return encode(ARTIST_RECOVERY_TERMINAL_TUPLE, normalizeArtistRecoveryTerminal(v)); }
export function decodeArtistRecoveryTerminal(v: Hex): ArtistRecoveryTerminal { return normalizeArtistRecoveryTerminal(decode<ArtistRecoveryTerminal>(ARTIST_RECOVERY_TERMINAL_TUPLE, v)); }
export function encodeArtistRecoveryCurrentNoticeFacts(v: ArtistRecoveryCurrentNoticeFacts): Hex { return encode(ARTIST_RECOVERY_CURRENT_NOTICE_FACTS_TUPLE, normalizeArtistRecoveryCurrentNoticeFacts(v)); }
export function decodeArtistRecoveryCurrentNoticeFacts(v: Hex): ArtistRecoveryCurrentNoticeFacts { return normalizeArtistRecoveryCurrentNoticeFacts(decode<ArtistRecoveryCurrentNoticeFacts>(ARTIST_RECOVERY_CURRENT_NOTICE_FACTS_TUPLE, v)); }
export function encodeArtistRecoveryCause(v: ArtistRecoveryCause): Hex { return encode(ARTIST_RECOVERY_CAUSE_TUPLE, normalizeArtistRecoveryCause(v)); }
export function decodeArtistRecoveryCause(v: Hex): ArtistRecoveryCause { return normalizeArtistRecoveryCause(decode<ArtistRecoveryCause>(ARTIST_RECOVERY_CAUSE_TUPLE, v)); }
export function encodeArtistRecoveryNoticeEvidence(v: ArtistRecoveryNoticeEvidence): Hex { return encode(ARTIST_RECOVERY_NOTICE_EVIDENCE_TUPLE, normalizeArtistRecoveryNoticeEvidence(v), true); }
export function decodeArtistRecoveryNoticeEvidence(v: Hex): ArtistRecoveryNoticeEvidence { return normalizeArtistRecoveryNoticeEvidence(decode<ArtistRecoveryNoticeEvidence>(ARTIST_RECOVERY_NOTICE_EVIDENCE_TUPLE, v, true)); }
export function encodeArtistRecoveryAppealAuthority(v: ArtistRecoveryAppealAuthority): Hex { return encode(ARTIST_RECOVERY_APPEAL_AUTHORITY_TUPLE, normalizeArtistRecoveryAppealAuthority(v)); }
export function decodeArtistRecoveryAppealAuthority(v: Hex): ArtistRecoveryAppealAuthority { return normalizeArtistRecoveryAppealAuthority(decode<ArtistRecoveryAppealAuthority>(ARTIST_RECOVERY_APPEAL_AUTHORITY_TUPLE, v)); }
export function encodeArtistRecoveryDirectiveRecord(v: ArtistRecoveryDirectiveRecord): Hex { return encode(ARTIST_RECOVERY_DIRECTIVE_RECORD_TUPLE, normalizeArtistRecoveryDirectiveRecord(v)); }
export function decodeArtistRecoveryDirectiveRecord(v: Hex): ArtistRecoveryDirectiveRecord { return normalizeArtistRecoveryDirectiveRecord(decode<ArtistRecoveryDirectiveRecord>(ARTIST_RECOVERY_DIRECTIVE_RECORD_TUPLE, v)); }
export function encodeArtistRecoveryEvidence(v: ArtistRecoveryEvidence): Hex { return encode(ARTIST_RECOVERY_EVIDENCE_TUPLE, normalizeArtistRecoveryEvidence(v)); }
export function decodeArtistRecoveryEvidence(v: Hex): ArtistRecoveryEvidence { return normalizeArtistRecoveryEvidence(decode<ArtistRecoveryEvidence>(ARTIST_RECOVERY_EVIDENCE_TUPLE, v)); }
export function encodeArtistRecoverySignerApproval(v: ArtistRecoverySignerApproval): Hex { return encode(ARTIST_RECOVERY_SIGNER_APPROVAL_TUPLE, normalizeArtistRecoverySignerApproval(v)); }
export function decodeArtistRecoverySignerApproval(v: Hex): ArtistRecoverySignerApproval { return normalizeArtistRecoverySignerApproval(decode<ArtistRecoverySignerApproval>(ARTIST_RECOVERY_SIGNER_APPROVAL_TUPLE, v)); }
export function encodeArtistRecoveryGovernanceWitness(v: ArtistRecoveryGovernanceWitness): Hex { return encode(ARTIST_RECOVERY_GOVERNANCE_WITNESS_TUPLE, normalizeArtistRecoveryGovernanceWitness(v)); }
export function decodeArtistRecoveryGovernanceWitness(v: Hex): ArtistRecoveryGovernanceWitness { return normalizeArtistRecoveryGovernanceWitness(decode<ArtistRecoveryGovernanceWitness>(ARTIST_RECOVERY_GOVERNANCE_WITNESS_TUPLE, v)); }
export function encodeArtistRecoveryPreparationPayload(v: ArtistRecoveryPreparationPayload): Hex { return encode(ARTIST_RECOVERY_PREPARATION_PAYLOAD_TUPLE, normalizeArtistRecoveryPreparationPayload(v), true); }
export function decodeArtistRecoveryPreparationPayload(v: Hex): ArtistRecoveryPreparationPayload { return normalizeArtistRecoveryPreparationPayload(decode<ArtistRecoveryPreparationPayload>(ARTIST_RECOVERY_PREPARATION_PAYLOAD_TUPLE, v, true)); }
export function encodeArtistRecoveryExecutionPayload(v: ArtistRecoveryExecutionPayload): Hex { return encode(ARTIST_RECOVERY_EXECUTION_PAYLOAD_TUPLE, normalizeArtistRecoveryExecutionPayload(v), true); }
export function decodeArtistRecoveryExecutionPayload(v: Hex): ArtistRecoveryExecutionPayload { return normalizeArtistRecoveryExecutionPayload(decode<ArtistRecoveryExecutionPayload>(ARTIST_RECOVERY_EXECUTION_PAYLOAD_TUPLE, v, true)); }

export const CURRENT_ARTIST_RECOVERY_EVIDENCE_ABI: readonly string[] = Object.freeze([
  `function publishResolutionManifest(${ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE} manifest) returns(bytes32)`,
  `function resolutionManifest(bytes32 manifestHash) view returns(${ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE},bytes32 ownerCodeHash)`,
  `function publishAppealV2(${ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE} document) returns(bytes32)`,
  `function appealEvidenceV2(bytes32 documentHash) view returns(${ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE},bytes32 ownerCodeHash)`,
]);
export const CURRENT_ARTIST_RECOVERY_SELECTION_ABI: readonly string[] = Object.freeze([
  "function beginSelectionV2(bytes32 manifestHash) returns(bytes32 key)",
  `function continueSelectionV2(bytes32 key,uint64 maximumRecords) returns(${ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE})`,
  `function requireSelectionV2(bytes32 manifestHash) view returns(${ARTIST_RECOVERY_SELECTION_RESULT_TUPLE})`,
  `function selectionV2(bytes32 key) view returns(${ARTIST_RECOVERY_SELECTION_BASIS_TUPLE},${ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE})`,
  "function retainedMemberV2(bytes32 key,address actor) view returns(bool)",
]);
export const CURRENT_ARTIST_RECOVERY_ADJUDICATION_ABI: readonly string[] = Object.freeze([
  `function identityRecoveryContextV2(${ARTIST_RECOVERY_REQUEST_TUPLE} request,${ARTIST_RECOVERY_AUTHORIZATION_TUPLE} acceptance,bytes32 manifestHash) view returns(${ARTIST_RECOVERY_CONTEXT_TUPLE})`,
  `function registerIdentityRecoveryActionV2(bytes32 actionId,${ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE}[] calls,${ARTIST_RECOVERY_REQUEST_TUPLE} request,${ARTIST_RECOVERY_AUTHORIZATION_TUPLE} acceptance,bytes32 manifestHash) returns(bytes32)`,
  `function recoverArtistIdentityV2(${ARTIST_RECOVERY_REQUEST_TUPLE} request,${ARTIST_RECOVERY_AUTHORIZATION_TUPLE} acceptance,bytes32 manifestHash) returns(bytes32)`,
  `function identityRecoveryEvidenceState(bytes32 artistId,bytes32 actionId) view returns(${ARTIST_RECOVERY_EVIDENCE_STATE_TUPLE})`,
]);
export const CURRENT_ARTIST_RECOVERY_GOVERNANCE_ABI: readonly string[] = Object.freeze([
  "function publishGovernanceCallData(bytes[] callDatas) returns(address)",
  `function scheduleGovernanceBatch(uint8 actionClass,${ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE}[] calls,bytes32 scopeHash,bytes32 oldValueHash,bytes32 newValueHash,uint64 notBefore,uint64 expiresAfter,bytes32 reasonHash,string reasonURI,bytes32 manifestHash) returns(bytes32)`,
  `function executeGovernanceBatch(bytes32 actionId,${ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE}[] calls,bytes[] callDatas) payable`,
]);
const evidenceAbi = new Interface(CURRENT_ARTIST_RECOVERY_EVIDENCE_ABI), selectionAbi = new Interface(CURRENT_ARTIST_RECOVERY_SELECTION_ABI), recoveryAbi = new Interface(CURRENT_ARTIST_RECOVERY_ADJUDICATION_ABI), governanceAbi = new Interface(CURRENT_ARTIST_RECOVERY_GOVERNANCE_ABI);
function call(to: Address, intf: Interface, method: string, args: readonly unknown[]): UnsignedCall { return Object.freeze({ to, data: intf.encodeFunctionData(method, args) as Hex, value: 0n }); }
export function artistRecoveryRequestCommitment(input: ArtistRecoveryRequest): Hex {
  const p = normalizeArtistRecoveryRequest(input);
  return digest(["bytes32", "uint16", "bytes32", "address", "uint8", "bytes32", "bytes32", "bytes32", "bytes32", "bytes32[]"], [id("6529STREAM_ARTIST_GUARDIAN_APPEAL_REQUEST_V1"), 1n, p.artistId, p.newAddress, p.vestedAuthorityClass, p.expectedCauseHash, p.expectedResolutionHash, ZeroHash, p.reasonHash, p.supersededRecordHashes]);
}
export function artistRecoveryResolutionManifestHash(coordinates: ArtistRecoveryAdjudicationCoordinates, input: ArtistRecoveryResolutionManifest): Hex {
  const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates), m = normalizeArtistRecoveryResolutionManifest(input);
  return digest(["bytes32", "uint16", "uint256", "address", "address", "bytes32", "address", "address", "address", "address", ARTIST_RECOVERY_RESOLUTION_MANIFEST_TUPLE], [id("6529STREAM_ARTIST_RECOVERY_RESOLUTION_MANIFEST_V1"), 1n, c.chainId, c.registry, c.owner, c.ownerCodeHash, c.coordinator, c.archive, c.core, c.mintManager, m]);
}
export function artistRecoveryAppealHash(coordinates: ArtistRecoveryAdjudicationCoordinates, input: ArtistRecoveryAppealDocument): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates); return digest(["bytes32", "uint16", "uint256", "address", "address", ARTIST_RECOVERY_APPEAL_DOCUMENT_TUPLE], [id("6529STREAM_ARTIST_HOSTILE_GUARDIAN_EVIDENCE_V2"), 2n, c.chainId, c.registry, c.owner, normalizeArtistRecoveryAppealDocument(input)]); }
export function artistRecoverySelectionKey(coordinates: ArtistRecoveryAdjudicationCoordinates, basis: ArtistRecoverySelectionBasis): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates); return digest(["bytes32", "uint256", "address", "address", ARTIST_RECOVERY_SELECTION_BASIS_TUPLE], [id("6529STREAM_ARTIST_GUARDIAN_SELECTION_SOURCE_V2"), c.chainId, c.registry, c.owner, normalizeArtistRecoverySelectionBasis(basis)]); }
/** Reconstructs a completed result from supplied progress, without authenticating the scanned history. */
export function artistRecoverySelectionResult(coordinates: ArtistRecoveryAdjudicationCoordinates, basis: ArtistRecoverySelectionBasis, progress: ArtistRecoverySelectionProgress): ArtistRecoverySelectionResult {
  const b = normalizeArtistRecoverySelectionBasis(basis), p = normalizeArtistRecoverySelectionProgress(progress); nz(b.manifestHash); nz(b.artistId); nz(b.ownerCodeHash); nz(b.sourceCommitment);
  if (b.history.count === 0n ? b.history.ownerRevision !== 0n || b.history.commitment !== ZeroHash : b.history.ownerRevision === 0n || b.history.commitment === ZeroHash) throw Error("Invalid selection history head");
  if (!p.complete || p.processed !== b.history.count || p.lastOwnerRevision !== b.history.ownerRevision || p.historyTip !== b.history.commitment) throw Error("Selection is incomplete or differs from its history head");
  if (p.selectedRecordHash === ZeroHash && (p.selectedDataHash !== ZeroHash || p.selectedNonce !== 0n)) throw Error("Empty selection has nonempty selected facts");
  const sourceKey = artistRecoverySelectionKey(coordinates, b);
  return Object.freeze({ sourceKey, selectedRecordHash: p.selectedRecordHash, selectedDataHash: p.selectedDataHash, selectedNonce: p.selectedNonce, commitment: digest(["bytes32", "bytes32", ARTIST_RECOVERY_SELECTION_BASIS_TUPLE, ARTIST_RECOVERY_SELECTION_PROGRESS_TUPLE], [id("6529STREAM_ARTIST_GUARDIAN_SELECTION_RESULT_V2"), sourceKey, b, p]) });
}
export function artistRecoveryAcceptancePayload(chainId: bigint, registry: Address, request: ArtistRecoveryRequest, incumbent: Address, acceptance: ArtistRecoveryAuthorization) {
  const p = normalizeArtistRecoveryRequest(request), a = normalizeArtistRecoveryAuthorization(acceptance);
  const fields = [{ name: "artistId", type: "bytes32" }, { name: "oldAddress", type: "address" }, { name: "newAddress", type: "address" }, { name: "nonce", type: "uint256" }, { name: "deadline", type: "uint64" }];
  return buildSigningPayload<ArtistRecoveryAcceptanceMessage>(chainId, address(registry, true), "6529StreamArtistRegistry", "StreamArtistRotationAcceptance", fields, { artistId: p.artistId, oldAddress: address(incumbent, true), newAddress: address(p.newAddress, true), nonce: a.nonce, deadline: a.time });
}
export function artistRecoverySupersededRecordsHash(records: readonly Hex[]): Hex { return digest(["bytes32", "bytes32[]"], ["0x0c8573762967a1af597f2a7afc4b655a87b3e22d2b11fbab6cf13c6f7b1396ae", sortedHashes(records)]); }
export function artistRecoveryRecordHash(chainId: bigint, registry: Address, fields: ArtistRecoveryRecordFields): Hex { return digest(["bytes32", "uint256", "address", ARTIST_RECOVERY_RECORD_FIELDS_TUPLE], ["0x459749364fd07c3a8f1998b82d893d33ef0942c30d94666b42dac1e37ba5feff", uint(chainId, 256), address(registry), normalizeArtistRecoveryRecordFields(fields)]); }
export function artistRecoveryVestingCommitment(coordinates: ArtistRecoveryAdjudicationCoordinates, input: ArtistRecoveryVesting): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates), v = normalizeArtistRecoveryVesting(input); return digest(["bytes32", "uint256", "address", "address", "bytes32", "bytes32", "uint16", "uint64", "uint64", "address", "address", "uint8", ARTIST_RECOVERY_HISTORY_HEAD_TUPLE, "bytes32", "bytes32"], [id("6529STREAM_ARTIST_GUARDIAN_VESTING_V1"), c.chainId, c.registry, c.owner, v.artistId, v.transitionRecordHash, v.operationId, v.ownerRevision, v.executedAt, v.oldAddress, v.newAddress, v.authorityClass, v.guardians, v.previousTransitionRecordHash, v.previousCommitment]); }
export function artistRecoveryScopeHash(coordinates: ArtistRecoveryAdjudicationCoordinates, artistId: Hex): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates); return digest(["bytes32", "uint256", "address", "address", "bytes32"], [id("6529STREAM_ARTIST_IDENTITY_RECOVERY_SCOPE_V2"), c.chainId, c.registry, c.owner, hex(artistId, 32)]); }
export function artistRecoveryIntentHash(context: ArtistRecoveryContext, request: ArtistRecoveryRequest, acceptance: ArtistRecoveryAuthorization): Hex { const c = normalizeArtistRecoveryContext(context), p = normalizeArtistRecoveryRequest(request), a = normalizeArtistRecoveryAuthorization(acceptance); return digest(["bytes32", "bytes32", "bytes32", ARTIST_RECOVERY_REQUEST_TUPLE, "uint256", "uint64"], [id("6529STREAM_ARTIST_IDENTITY_RECOVERY_INTENT_V2"), c.scopeHash, c.oldValueHash, p, a.nonce, a.time]); }
export function artistRecoveryCurrentNoticeContextHash(originalHash: Hex, input: ArtistRecoveryCurrentNoticeFacts): Hex { const f = normalizeArtistRecoveryCurrentNoticeFacts(input), h = hex(originalHash, 32); return f.notice.recordHash === ZeroHash ? h : digest(["bytes32", "bytes32", ARTIST_RECOVERY_CURRENT_NOTICE_FACTS_TUPLE], [id("6529STREAM_ARTIST_RECOVERY_CURRENT_NOTICE_CONTEXT_V1"), h, f]); }
export function artistRecoveryCurrentNoticeSourceHash(originalHash: Hex, input: ArtistRecoveryCurrentNoticeFacts): Hex { const f = normalizeArtistRecoveryCurrentNoticeFacts(input), h = hex(originalHash, 32); return f.notice.recordHash === ZeroHash ? h : digest(["bytes32", "bytes32", ARTIST_RECOVERY_CURRENT_NOTICE_FACTS_TUPLE], [id("6529STREAM_ARTIST_RECOVERY_CURRENT_NOTICE_SOURCE_V1"), h, f]); }
export function artistRecoveryPreparationHash(coordinates: ArtistRecoveryAdjudicationCoordinates, previousAction: Hex, manifestHash: Hex, basisCommitment: Hex, selection: ArtistRecoverySelectionResult, association: ArtistRecoveryActionAssociation): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates), a = normalizeArtistRecoveryActionAssociation(association); return digest(["bytes32", "uint256", "address", "address", "address", "address", "bytes32", "bytes32", "bytes32", ARTIST_RECOVERY_SELECTION_RESULT_TUPLE, ARTIST_RECOVERY_ACTION_ASSOCIATION_TUPLE], [id("6529STREAM_ARTIST_RECOVERY_PREPARATION_V2"), c.chainId, c.registry, c.owner, c.coordinator, c.archive, hex(previousAction, 32), hex(manifestHash, 32), hex(basisCommitment, 32), normalizeArtistRecoverySelectionResult(selection), { ...a, associationHash: ZeroHash }]); }
/** Original cancellation hashes an otherwise empty Terminal before assigning recordHash. */
export function artistRecoveryCancellationHash(coordinates: ArtistRecoveryAdjudicationCoordinates, terminal: ArtistRecoveryTerminal, activity: bigint): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates), t = normalizeArtistRecoveryTerminal(terminal); const empty = decodeArtistRecoveryTerminal(`0x${"00".repeat(32 * 19)}` as Hex); const canonical = { ...empty, noticeHash: t.noticeHash, actor: t.actor, authorityClass: t.authorityClass, observedAt: t.observedAt }; if (!same({ ...t, recordHash: ZeroHash }, canonical)) throw Error("Cancellation must retain the original zero inactive Terminal fields"); return digest(["bytes32", "uint256", "address", "address", ARTIST_RECOVERY_TERMINAL_TUPLE, "uint256"], [id("6529STREAM_ARTIST_DORMANCY_CANCELLATION_V1"), c.chainId, c.registry, c.owner, canonical, uint(activity, 256)]); }

export type ArtistRecoveryAdjudicationInput =
  | { readonly kind: "publishResolutionManifest"; readonly manifest: ArtistRecoveryResolutionManifest }
  | { readonly kind: "resolutionManifest" | "beginSelectionV2" | "requireSelectionV2"; readonly manifestHash: Hex }
  | { readonly kind: "publishAppealV2"; readonly document: ArtistRecoveryAppealDocument }
  | { readonly kind: "appealEvidenceV2"; readonly documentHash: Hex }
  | { readonly kind: "continueSelectionV2"; readonly key: Hex; readonly maximumRecords: bigint }
  | { readonly kind: "selectionV2"; readonly key: Hex }
  | { readonly kind: "retainedMemberV2"; readonly key: Hex; readonly actor: Address }
  | { readonly kind: "identityRecoveryContextV2" | "recoverArtistIdentityV2"; readonly request: ArtistRecoveryRequest; readonly acceptance: ArtistRecoveryAuthorization; readonly manifestHash: Hex }
  | { readonly kind: "registerIdentityRecoveryActionV2"; readonly actionId: Hex; readonly calls: readonly ArtistRecoveryGovernanceCall[]; readonly request: ArtistRecoveryRequest; readonly acceptance: ArtistRecoveryAuthorization; readonly manifestHash: Hex }
  | { readonly kind: "identityRecoveryEvidenceState"; readonly artistId: Hex; readonly actionId: Hex };
export interface ArtistRecoveryAdjudicationCall { readonly coordinates: ArtistRecoveryAdjudicationCoordinates; readonly caller: Address; readonly input: ArtistRecoveryAdjudicationInput; readonly call: UnsignedCall; readonly expectedReturnHash: Hex | null; readonly factsVerified: false }
export function prepareArtistRecoveryAdjudicationCall(coordinates: ArtistRecoveryAdjudicationCoordinates, caller: Address, input: ArtistRecoveryAdjudicationInput): ArtistRecoveryAdjudicationCall {
  const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates), actor = address(caller, true); let v: ArtistRecoveryAdjudicationInput, target: Address, intf: Interface, args: readonly unknown[], expectedReturnHash: Hex | null = null;
  switch (input.kind) {
    case "publishResolutionManifest": exact(input, ["kind", "manifest"], input.kind); v = Object.freeze({ kind: input.kind, manifest: normalizeArtistRecoveryResolutionManifest(input.manifest) }); target = c.evidencePublisher; intf = evidenceAbi; args = [v.manifest]; expectedReturnHash = artistRecoveryResolutionManifestHash(c, v.manifest); break;
    case "publishAppealV2": exact(input, ["kind", "document"], input.kind); v = Object.freeze({ kind: input.kind, document: normalizeArtistRecoveryAppealDocument(input.document) }); target = c.evidencePublisher; intf = evidenceAbi; args = [v.document]; expectedReturnHash = artistRecoveryAppealHash(c, v.document); break;
    case "resolutionManifest": case "beginSelectionV2": case "requireSelectionV2": exact(input, ["kind", "manifestHash"], input.kind); v = Object.freeze({ kind: input.kind, manifestHash: nz(hex(input.manifestHash, 32)) }); target = input.kind === "resolutionManifest" ? c.evidencePublisher : c.selectionPreparation; intf = input.kind === "resolutionManifest" ? evidenceAbi : selectionAbi; args = [v.manifestHash]; break;
    case "appealEvidenceV2": exact(input, ["kind", "documentHash"], input.kind); v = Object.freeze({ kind: input.kind, documentHash: nz(hex(input.documentHash, 32)) }); target = c.evidencePublisher; intf = evidenceAbi; args = [v.documentHash]; break;
    case "continueSelectionV2": exact(input, ["kind", "key", "maximumRecords"], input.kind); v = Object.freeze({ kind: input.kind, key: nz(hex(input.key, 32)), maximumRecords: uint(input.maximumRecords, 64) }); if (!v.maximumRecords) throw Error("maximumRecords must be positive"); target = c.selectionPreparation; intf = selectionAbi; args = [v.key, v.maximumRecords]; break;
    case "selectionV2": exact(input, ["kind", "key"], input.kind); v = Object.freeze({ kind: input.kind, key: hex(input.key, 32) }); target = c.selectionPreparation; intf = selectionAbi; args = [v.key]; break;
    case "retainedMemberV2": exact(input, ["kind", "key", "actor"], input.kind); v = Object.freeze({ kind: input.kind, key: nz(hex(input.key, 32)), actor: address(input.actor) }); target = c.selectionPreparation; intf = selectionAbi; args = [v.key, v.actor]; break;
    case "identityRecoveryContextV2": case "recoverArtistIdentityV2": case "registerIdentityRecoveryActionV2": {
      exact(input, ["kind", "request", "acceptance", "manifestHash", ...(input.kind === "registerIdentityRecoveryActionV2" ? ["actionId", "calls"] : [])], input.kind);
      const request = normalizeArtistRecoveryRequest(input.request), acceptance = normalizeArtistRecoveryAuthorization(input.acceptance), manifestHash = nz(hex(input.manifestHash, 32));
      nz(request.artistId); nz(request.expectedCauseHash); nz(request.evidenceHash); nz(request.reasonHash); address(request.newAddress, true); if (request.vestedAuthorityClass !== 1n && request.vestedAuthorityClass !== 3n) throw Error("Only original living or estate V2 recovery is supported");
      if (input.kind === "registerIdentityRecoveryActionV2") { const calls = normalize(`${ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE}[]`, input.calls); v = Object.freeze({ kind: input.kind, actionId: nz(hex(input.actionId, 32)), calls, request, acceptance, manifestHash }); args = [v.actionId, calls, request, acceptance, manifestHash]; }
      else { v = Object.freeze({ kind: input.kind, request, acceptance, manifestHash }); args = [request, acceptance, manifestHash]; }
      target = c.registry; intf = recoveryAbi; break;
    }
    case "identityRecoveryEvidenceState": exact(input, ["kind", "artistId", "actionId"], input.kind); v = Object.freeze({ kind: input.kind, artistId: hex(input.artistId, 32), actionId: hex(input.actionId, 32) }); target = c.registry; intf = recoveryAbi; args = [v.artistId, v.actionId]; break;
    default: throw Error("Unknown recoveryV2 method");
  }
  return Object.freeze({ coordinates: c, caller: actor, input: v, call: call(target, intf, v.kind, args), expectedReturnHash, factsVerified: false });
}
export function normalizeArtistRecoveryAdjudicationCall(input: ArtistRecoveryAdjudicationCall): ArtistRecoveryAdjudicationCall { exact(input, ["coordinates", "caller", "input", "call", "expectedReturnHash", "factsVerified"], "Recovery prepared call"); const value = prepareArtistRecoveryAdjudicationCall(input.coordinates, input.caller, input.input); if (!same(value, input)) throw Error("Recovery call differs from original reconstruction"); return value; }

export interface ArtistRecoveryGovernanceBatch {
  readonly coordinates: ArtistRecoveryAdjudicationCoordinates; readonly request: ArtistRecoveryRequest; readonly acceptance: ArtistRecoveryAuthorization;
  readonly manifestHash: Hex; readonly context: ArtistRecoveryContext; readonly executor: Address; readonly nonce: bigint; readonly window: ArtistRecoveryGovernanceWindow;
  readonly targetCall: UnsignedCall; readonly governanceCall: ArtistRecoveryGovernanceCall; readonly actionClass: 2n;
  readonly callsHash: Hex; readonly scopeHash: Hex; readonly oldValueHash: Hex; readonly newValueHash: Hex; readonly actionId: Hex; readonly publicationKey: Hex;
  readonly publicationCall: UnsignedCall; readonly scheduleCall: UnsignedCall; readonly executionCall: UnsignedCall; readonly factsVerified: false;
}
export const normalizeArtistRecoveryGovernanceWindow = normalizeMintPolicyGraceGovernanceWindow;
/** Registration rechecks its own timestamp plus observed delay; a schedule-time check is insufficient. */
export function assertArtistRecoveryRegistrationWindow(acceptance: ArtistRecoveryAuthorization, window: ArtistRecoveryGovernanceWindow, registrationTimestamp: bigint, minimumDelay: bigint): void {
  const a = normalizeArtistRecoveryAuthorization(acceptance), w = normalizeArtistRecoveryGovernanceWindow(window), now = uint(registrationTimestamp, 64), delay = uint(minimumDelay, 64);
  if (!now || delay < 259200n || now + delay > w.notBefore || a.time < w.notBefore) throw Error("Recovery registration requires its own full governance delay and acceptance deadline");
}
/** Singleton original class2 batch. It does not establish scheduled state, proposer role or ancestry. */
export function artistRecoveryGovernanceBatch(coordinates: ArtistRecoveryAdjudicationCoordinates, request: ArtistRecoveryRequest, acceptance: ArtistRecoveryAuthorization, manifestHash: Hex, context: ArtistRecoveryContext, executor: Address, nonce: bigint, window: ArtistRecoveryGovernanceWindow): ArtistRecoveryGovernanceBatch {
  const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates), actor = address(executor, true), prepared = prepareArtistRecoveryAdjudicationCall(c, actor, { kind: "recoverArtistIdentityV2", request, acceptance, manifestHash }), p = prepared.input as Extract<ArtistRecoveryAdjudicationInput, { kind: "recoverArtistIdentityV2" | "identityRecoveryContextV2" }>;
  const x = normalizeArtistRecoveryContext(context), n = uint(nonce, 256), w = normalizeArtistRecoveryGovernanceWindow(window);
  if (x.causeHash !== p.request.expectedCauseHash || x.scopeHash !== artistRecoveryScopeHash(c, p.request.artistId) || x.newValueHash !== artistRecoveryIntentHash(x, p.request, p.acceptance) || w.reasonHash !== p.request.reasonHash || p.acceptance.time < w.notBefore) throw Error("Recovery context, reason or acceptance does not match the scheduled V2 request");
  const targetCall = prepared.call, governanceCall = Object.freeze({ target: targetCall.to, value: 0n, selector: targetCall.data.slice(0, 10) as Hex, callDataHash: keccak256(targetCall.data) as Hex, scopeHash: x.scopeHash, oldValueHash: x.oldValueHash, newValueHash: x.newValueHash });
  const calls = [governanceCall], datas = [targetCall.data], callsHash = digest(["bytes32", `${ARTIST_RECOVERY_GOVERNANCE_CALL_TUPLE}[]`], ["0x10f09566fb70f7947b61639c2a53b3aec872069a8b46edd08ba14eb2b5942b70", calls]);
  const aggregate = (domain: Hex, field: "scopeHash" | "oldValueHash" | "newValueHash") => digest(["bytes32", "bytes32", "bytes32[]"], [domain, callsHash, [governanceCall[field]]]);
  const scopeHash = aggregate("0x6cfd5dfd67f064adac45602c05057edddda810734779c0ebe11b447e6985e31c", "scopeHash"), oldValueHash = aggregate("0xc5029f937b44065c2ad92d9253e07f06117567480206189fcc1409d5509222b7", "oldValueHash"), newValueHash = aggregate("0xce958009248d20d9574439fa374bc00c142940af2b496896b5bdbc00b882e98b", "newValueHash");
  const actionId = digest(["bytes32", "uint256", "address", "tuple(uint8,bytes32,bytes32,bytes32,bytes32,uint256,uint64,uint64,bytes32,bytes32)"], ["0x214cd728538bb3775a7106caff5c761bace11866a984d4a4d97a98f51971ac4b", c.chainId, actor, [2n, callsHash, scopeHash, oldValueHash, newValueHash, n, w.notBefore, w.expiresAfter, w.reasonHash, w.manifestHash]]);
  return Object.freeze({ coordinates: c, request: p.request, acceptance: p.acceptance, manifestHash: p.manifestHash, context: x, executor: actor, nonce: n, window: w, targetCall, governanceCall, actionClass: 2n, callsHash, scopeHash, oldValueHash, newValueHash, actionId, publicationKey: keccak256(governanceCall.callDataHash) as Hex,
    publicationCall: call(actor, governanceAbi, "publishGovernanceCallData", [datas]), scheduleCall: call(actor, governanceAbi, "scheduleGovernanceBatch", [2n, calls, scopeHash, oldValueHash, newValueHash, w.notBefore, w.expiresAfter, w.reasonHash, w.reasonURI, w.manifestHash]), executionCall: call(actor, governanceAbi, "executeGovernanceBatch", [actionId, calls, datas]), factsVerified: false });
}
export function normalizeArtistRecoveryGovernanceBatch(input: ArtistRecoveryGovernanceBatch): ArtistRecoveryGovernanceBatch { exact(input, ["coordinates", "request", "acceptance", "manifestHash", "context", "executor", "nonce", "window", "targetCall", "governanceCall", "actionClass", "callsHash", "scopeHash", "oldValueHash", "newValueHash", "actionId", "publicationKey", "publicationCall", "scheduleCall", "executionCall", "factsVerified"], "Recovery governance batch"); const value = artistRecoveryGovernanceBatch(input.coordinates, input.request, input.acceptance, input.manifestHash, input.context, input.executor, input.nonce, input.window); if (!same(input, value)) throw Error("Recovery batch differs from reconstruction"); return value; }

export interface ArtistRecoveryPreparationEvidence { readonly payload: ArtistRecoveryPreparationPayload; readonly notice: ArtistRecoveryNoticeEvidence | null }
export interface ArtistRecoveryExecutionEvidence { readonly payload: ArtistRecoveryExecutionPayload; readonly noticeBefore: ArtistRecoveryNoticeEvidence | null; readonly noticeAfter: ArtistRecoveryNoticeEvidence | null }
/** Without a notice these retain the original untagged bytes exactly. */
export function encodeArtistRecoveryPreparationEvidence(input: ArtistRecoveryPreparationEvidence): Hex { exact(input, ["payload", "notice"], "Preparation evidence"); const base = encodeArtistRecoveryPreparationPayload(input.payload); return input.notice === null ? base : bounded(coder.encode(["bytes32", "bytes", "bytes"], [ARTIST_RECOVERY_PREPARATION_NOTICE_TAG, base, encodeArtistRecoveryNoticeEvidence(input.notice)]) as Hex); }
export function decodeArtistRecoveryPreparationEvidence(input: Hex): ArtistRecoveryPreparationEvidence { const raw = bounded(hex(input)); if (raw.slice(0, 66) !== ARTIST_RECOVERY_PREPARATION_NOTICE_TAG) return Object.freeze({ payload: decodeArtistRecoveryPreparationPayload(raw), notice: null }); const [tag, base, notice] = coder.decode(["bytes32", "bytes", "bytes"], raw); if (coder.encode(["bytes32", "bytes", "bytes"], [tag, base, notice]) !== raw) throw Error("Noncanonical tagged preparation"); return Object.freeze({ payload: decodeArtistRecoveryPreparationPayload(base), notice: decodeArtistRecoveryNoticeEvidence(notice) }); }
export function encodeArtistRecoveryExecutionEvidence(input: ArtistRecoveryExecutionEvidence): Hex { exact(input, ["payload", "noticeBefore", "noticeAfter"], "Execution evidence"); const base = encodeArtistRecoveryExecutionPayload(input.payload); if (input.noticeBefore === null && input.noticeAfter === null) return base; if (input.noticeBefore === null || input.noticeAfter === null) throw Error("Both exact notice observations are required"); return bounded(coder.encode(["bytes32", "bytes", "bytes", "bytes"], [ARTIST_RECOVERY_EXECUTION_NOTICE_TAG, base, encodeArtistRecoveryNoticeEvidence(input.noticeBefore), encodeArtistRecoveryNoticeEvidence(input.noticeAfter)]) as Hex); }
export function decodeArtistRecoveryExecutionEvidence(input: Hex): ArtistRecoveryExecutionEvidence { const raw = bounded(hex(input)); if (raw.slice(0, 66) !== ARTIST_RECOVERY_EXECUTION_NOTICE_TAG) return Object.freeze({ payload: decodeArtistRecoveryExecutionPayload(raw), noticeBefore: null, noticeAfter: null }); const [tag, base, before, after] = coder.decode(["bytes32", "bytes", "bytes", "bytes"], raw); if (coder.encode(["bytes32", "bytes", "bytes", "bytes"], [tag, base, before, after]) !== raw) throw Error("Noncanonical tagged execution"); return Object.freeze({ payload: decodeArtistRecoveryExecutionPayload(base), noticeBefore: decodeArtistRecoveryNoticeEvidence(before), noticeAfter: decodeArtistRecoveryNoticeEvidence(after) }); }
export interface ArtistRecoveryOperationEvidence { readonly schemaVersion: 1n; readonly configurationHash: Hex; readonly operation: 35n | 65534n; readonly actor: Address; readonly primaryRecordHash: Hex; readonly before: readonly ArtistHydrationSnapshot[]; readonly after: readonly ArtistHydrationSnapshot[]; readonly payload: Hex }
const operationEvidenceTypes = ["uint16", "bytes32", "uint16", "address", "bytes32", `${ARTIST_HYDRATION_SNAPSHOT_TUPLE}[7]`, `${ARTIST_HYDRATION_SNAPSHOT_TUPLE}[7]`, "bytes"];
export function encodeArtistRecoveryOperationEvidence(input: ArtistRecoveryOperationEvidence): Hex { exact(input, ["schemaVersion", "configurationHash", "operation", "actor", "primaryRecordHash", "before", "after", "payload"], "Operation evidence"); if (input.schemaVersion !== 1n || (input.operation !== 35n && input.operation !== 65534n) || (input.operation === 65534n && input.primaryRecordHash !== ZeroHash)) throw Error("Invalid original recovery operation envelope"); const before = normalize(`${ARTIST_HYDRATION_SNAPSHOT_TUPLE}[7]`, input.before), after = normalize(`${ARTIST_HYDRATION_SNAPSHOT_TUPLE}[7]`, input.after), payload = bounded(hex(input.payload)); return bounded(coder.encode(operationEvidenceTypes, [1n, hex(input.configurationHash, 32), input.operation, address(input.actor, true), hex(input.primaryRecordHash, 32), before, after, payload]) as Hex); }
export function decodeArtistRecoveryOperationEvidence(input: Hex): ArtistRecoveryOperationEvidence { const raw = hex(input); if (raw.length > 2 + ARTIST_RECOVERY_CODEC_MAX_BYTES * 2) throw Error("Envelope exceeds client bound"); const d = coder.decode(operationEvidenceTypes, raw), value = Object.freeze({ schemaVersion: d[0], configurationHash: d[1], operation: d[2], actor: address(d[3], true), primaryRecordHash: d[4], before: normal(ParamType.from(`${ARTIST_HYDRATION_SNAPSHOT_TUPLE}[7]`), d[5], true) as readonly ArtistHydrationSnapshot[], after: normal(ParamType.from(`${ARTIST_HYDRATION_SNAPSHOT_TUPLE}[7]`), d[6], true) as readonly ArtistHydrationSnapshot[], payload: d[7] }) as ArtistRecoveryOperationEvidence; if (encodeArtistRecoveryOperationEvidence(value) !== raw) throw Error("Noncanonical operation envelope"); return value; }
export function artistRecoveryOperationEvidenceId(coordinates: ArtistRecoveryAdjudicationCoordinates, operation: 35n | 65534n, actor: Address, commitment: Hex): Hex { const c = normalizeArtistRecoveryAdjudicationCoordinates(coordinates); if (operation !== 35n && operation !== 65534n) throw Error("Unsupported recovery operation"); return digest(["bytes32", "uint256", "address", "address", "uint16", "address", "bytes32"], [id("6529STREAM_ARTIST_ONBOARDING_OPERATION_EVIDENCE_V1"), c.chainId, c.registry, c.coordinator, operation, address(actor, true), hex(commitment, 32)]); }
